Repository kubermatic/docs, pull requests merged in 2019-12, with the labels that each got.

#209 Add comparison of kubeone and kubermatic
  content/kubermatic/master/concepts/kubeone-comparison/_index.en.md
  content/kubermatic/v2.12/concepts/kubeone-comparison/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#212 Replace custom links with global settings docs
  content/kubermatic/master/advanced/custom_links/_index.en.md
  static/img/advanced/custom_links/clean.png
  static/img/advanced/custom_links/custom_icons.png
  static/img/advanced/custom_links/default_icons.png
  static/img/advanced/settings/menu.png
  static/img/advanced/settings/view.png
Labels: approved, lgtm, size/L

#213 Added tutorial on node deployments
  content/kubermatic/master/tutorials/07-using-kubectl/_index.en.md
  content/kubermatic/master/tutorials/08-add-node-deployment/08-manage-node-deployments-edit-dialog.png
  content/kubermatic/master/tutorials/08-add-node-deployment/08-manage-node-deployments-edit.png
  content/kubermatic/master/tutorials/08-add-node-deployment/08-manage-node-deployments-overview.png
  content/kubermatic/master/tutorials/08-add-node-deployment/_index.en.md
  content/kubermatic/v2.12/tutorials/08-add-node-deployment/08-manage-node-deployments-edit-dialog.png
  content/kubermatic/v2.12/tutorials/08-add-node-deployment/08-manage-node-deployments-edit.png
  content/kubermatic/v2.12/tutorials/08-add-node-deployment/08-manage-node-deployments-overview.png
  content/kubermatic/v2.12/tutorials/08-add-node-deployment/_index.en.md
Labels: approved, lgtm, size/M

#219 Update Owner file
  OWNERS
Labels: approved, lgtm, size/XS

#217 Edits to the node deployment tutorial
  content/kubermatic/master/tutorials/08-add-node-deployment/_index.en.md
  content/kubermatic/v2.12/tutorials/08-add-node-deployment/_index.en.md
  tutorials-tests/cypress/integration/stories/tutorials.spec.ts
  tutorials-tests/cypress/pages/node-deployment-details.po.ts
  tutorials-tests/cypress/pages/projects.po.ts
Labels: approved, lgtm, size/M

#220 Redirect to docs.loodse.com
  static/_redirects
Labels: approved, lgtm, size/XS
