Repository kubermatic/docs, pull requests merged in 2020-05, with the labels that each got.

#306 Fix vSphere folder usage in KubeOne documentation
  content/kubeone/master/getting_started/vsphere.en.md
Labels: approved, lgtm, size/XS

#307 Document enforcePodSecurityPolicy for datacenters
  content/kubermatic/master/tutorials/13-psp/_index.en.md
Labels: approved, lgtm, size/S

#252 add missing AWS permisions for cloud controller manager creating LBs
  content/kubermatic/master/requirements/cloud_provider/_aws.en.md
  content/kubermatic/v2.12/requirements/cloud_provider/_aws.en.md
  content/kubermatic/v2.13/requirements/cloud_provider/_aws.en.md
Labels: approved, lgtm, size/S

#309 Update favicon
  config.toml
  layouts/partials/favicon.html
  static/img/favicon.ico
Labels: approved, lgtm, ok-to-test, size/XS

#312 Fix for responsive project tiles on homepage
  assets/css/main-header.css
  assets/css/projects.css
  assets/css/theme-kubermatic.css
  static/img/Kubermatic.svg
Labels: approved, lgtm, ok-to-test, size/M

#315 KubeOne: Update Kubernetes Versions Compatibility matrix
  content/kubeone/master/_index.en.md
Labels: approved, lgtm, size/XS

#313 Add mobile version of sidebar menu
  assets/css/main-header.css
  assets/css/theme-kubermatic.css
  layouts/partials/header.html
Labels: approved, lgtm, ok-to-test, size/M

#311 Fix search
  config.toml
  layouts/index.html
  layouts/partials/header.html
  layouts/section/list.json
  themes/hugo-theme-learn/layouts/partials/search.html
  themes/hugo-theme-learn/static/js/lunr.min.js
  themes/hugo-theme-learn/static/js/search.js
Labels: approved, lgtm, ok-to-test, size/L

#317 Add direct link to github for editing content in sections
  assets/css/theme-kubermatic.css
  config.toml
  layouts/partials/header.html
Labels: approved, lgtm, ok-to-test, size/S

#318 Change Domain to docs.kubermatic.com
  README.md
  config.toml
  content/kubeone/master/getting_started/aws.en.md
  content/kubeone/master/getting_started/azure.en.md
  content/kubeone/master/getting_started/digitalocean.en.md
  content/kubeone/master/getting_started/gce.en.md
  content/kubeone/master/getting_started/hetzner.en.md
  content/kubeone/master/getting_started/openstack.en.md
  content/kubeone/master/getting_started/packet.en.md
  content/kubeone/master/getting_started/vsphere.en.md
  data/kubermatic/master/runbook.json
  data/kubermatic/v2.12/runbook.json
  data/kubermatic/v2.13/runbook.json
  static/_redirects
  static/img/preview.png
Labels: approved, lgtm, size/XL

#316 Add ability to define Enterprise tag with title for nested sections
  assets/css/theme-kubermatic.css
  layouts/partials/header.html
Labels: approved, lgtm, ok-to-test, size/M

#321 Add .prow.yaml
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#322 Add auto redirect to current version of product based on products.yaml
  config.toml
  content/kubecarrier/_index.md
  content/kubeone/_index.md
  content/kubermatic/_index.md
  data/products.yaml
  layouts/partials/header.html
  layouts/shortcodes/redirect.html
  layouts/shortcodes/redirectkubecarrier.html
  layouts/shortcodes/redirectkubeone.html
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#324 Add note for docs in master branch
  assets/css/theme-kubermatic.css
  layouts/partials/header.html
  layouts/partials/logo.html
  layouts/partials/menu.html
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#325 Migrate style assets to Sass
  .gitignore
  .prow.yaml
  README.md
  assets/scss/_atom-one-dark-reasonable.scss
  assets/scss/_auto-complete.scss
  assets/scss/_featherlight.min.scss
  assets/scss/_fontawesome-all.min.scss
  assets/scss/_hugo-theme.scss
  assets/scss/_hybrid.scss
  assets/scss/_main-header.scss
  assets/scss/_nucleus.scss
  assets/scss/_perfect-scrollbar.min.scss
  assets/scss/_projects.scss
  assets/scss/_tags.scss
  assets/scss/_theme-kubermatic.scss
  assets/scss/_theme.scss
  assets/scss/app.scss
  layouts/partials/css-includes.html
  netlify.toml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/L
