Repository kubermatic/docs, pull requests merged in 2020-10, with the labels that each got.

#453 kubeone: refer to the vsphere-ccm-credentials secret
  content/kubeone/master/provisioning/_index.en.md
  content/kubeone/v1.0/provisioning/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#452 Document Helm 3 in KKP
  content/kubermatic/master/advanced/oidc_auth/_index.en.md
  content/kubermatic/master/installation/add_seed_cluster/_index.en.md
  content/kubermatic/master/installation/add_seed_cluster_ee/_index.en.md
  content/kubermatic/master/installation/logging_stack/_index.en.md
  content/kubermatic/master/installation/monitoring_stack/_index.en.md
  content/kubermatic/master/installation/securing_services/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/chart_migration/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/helm_2to3/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/kubermatic_chart/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/kubermatic_operator/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/L

#454 remove experimental notice note
  content/kubermatic/master/advanced/oidc_auth/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#456 Document -max-parallel-reconciles
  content/kubermatic/master/upgrading/_index.en.md
  content/kubermatic/master/upgrading/guidelines/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/L

#457 fix typo in version numbers
  content/kubermatic/master/upgrading/guidelines/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/XS

#458 update latest permissions at vsphere
  content/kubermatic/master/requirements/cloud_provider/_vsphere.en.md
  content/kubermatic/v2.14/requirements/cloud_provider/_vsphere.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#462 updated whitelist with latest dependencies + adding flatcar
  content/kubermatic/master/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/master/requirements/cloud_provider/_vsphere.en.md
  content/kubermatic/v2.14/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/v2.14/requirements/cloud_provider/_vsphere.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#360 improve minio doc
  content/kubermatic/master/installation/add_seed_cluster/_index.en.md
  content/kubermatic/master/installation/add_seed_cluster_ee/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/M

#461 Add datastore and datastore cluster docs for vSphere
  content/kubermatic/master/advanced/presets/_index.en.md
  content/kubermatic/master/data/seed.yaml
  content/kubermatic/master/requirements/cloud_provider/_vsphere.en.md
  content/kubermatic/v2.14/data/seed.yaml
  data/kubermatic/master/runbook.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#463 Fix missing page header
  content/kubermatic/v2.14/installation/securing_services/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/XS

#465 Remove 1.16 support from compatibility matrix for KKP 2.15
  content/kubermatic/master/installation/compatibility/_index.en.md
  content/kubermatic/v2.15/installation/compatibility/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/XS

#468 Etcd launcher
  content/kubermatic/master/operation/etcd/etcd-launcher/_index.en.md
  content/kubermatic/v2.15/operation/etcd/etcd-launcher/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#471 fix typo (copy of PR #455)
  content/kubermatic/master/concepts/kubeone-comparison/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#473 Kubeone apidoc regen
  content/kubeone/master/api_reference/v1beta1.en.md
  content/kubeone/master/infrastructure/custom_registry.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#472 Improve image-loader Docs
  content/kubermatic/master/advanced/addons/_index.en.md
  content/kubermatic/master/advanced/custom_links/_index.en.md
  content/kubermatic/master/advanced/custom_ui/_index.en.md
  content/kubermatic/master/advanced/dynamic_kubelet_config/_index.en.md
  content/kubermatic/master/advanced/offline_mode/_index.en.md
  content/kubermatic/master/advanced/oidc_auth/_index.en.md
  content/kubermatic/master/advanced/oidc_config/_index.en.md
  content/kubermatic/master/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/master/advanced/user_settings/_index.en.md
  content/kubermatic/master/advanced/versions_updates/_index.en.md
  content/kubermatic/v2.13/advanced/offline_mode/_index.en.md
  content/kubermatic/v2.14/advanced/addons/_index.en.md
  content/kubermatic/v2.14/advanced/custom_links/_index.en.md
  content/kubermatic/v2.14/advanced/custom_ui/_index.en.md
  content/kubermatic/v2.14/advanced/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.14/advanced/offline_mode/_index.en.md
  content/kubermatic/v2.14/advanced/oidc_auth/_index.en.md
  content/kubermatic/v2.14/advanced/oidc_config/_index.en.md
  content/kubermatic/v2.14/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/v2.14/advanced/user_settings/_index.en.md
  content/kubermatic/v2.14/advanced/versions_updates/_index.en.md
  content/kubermatic/v2.15/advanced/addons/_index.en.md
  content/kubermatic/v2.15/advanced/custom_links/_index.en.md
  content/kubermatic/v2.15/advanced/custom_ui/_index.en.md
  content/kubermatic/v2.15/advanced/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.15/advanced/offline_mode/_index.en.md
  content/kubermatic/v2.15/advanced/oidc_auth/_index.en.md
  content/kubermatic/v2.15/advanced/oidc_config/_index.en.md
  content/kubermatic/v2.15/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/v2.15/advanced/user_settings/_index.en.md
  content/kubermatic/v2.15/advanced/versions_updates/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/XL

#474 fix links to serviceaccount helper script
  content/kubermatic/master/installation/add_seed_cluster/_index.en.md
  content/kubermatic/master/installation/add_seed_cluster_ee/_index.en.md
  content/kubermatic/v2.15/installation/add_seed_cluster/_index.en.md
  content/kubermatic/v2.15/installation/add_seed_cluster_ee/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/XS

#469 Add google tag manager
  config.toml
  layouts/index.html
  layouts/partials/gtm-noscript.html
  layouts/partials/gtm-script.html
  layouts/partials/header.html
  themes/hugo-theme-learn/layouts/404.html
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#470 Add link items to main menu
  assets/scss/_main-header.scss
  assets/scss/_theme-kubermatic.scss
  config.toml
  data/mainMenu.yml
  layouts/index.html
  layouts/partials/header.html
  layouts/partials/main-header.html
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XL
