Repository kubermatic/docs, pull requests merged in 2020-11, with the labels that each got.

#475 Remove KKP Changelogs
  content/kubermatic/master/changelog/2.10/_index.en.md
  content/kubermatic/master/changelog/2.11/_index.en.md
  content/kubermatic/master/changelog/2.12/_index.en.md
  content/kubermatic/master/changelog/2.13/_index.en.md
  content/kubermatic/master/changelog/2.14/_index.en.md
  content/kubermatic/master/changelog/_index.en.md
  content/kubermatic/v2.12/changelog/2.10/_index.en.md
  content/kubermatic/v2.12/changelog/2.11/_index.en.md
  content/kubermatic/v2.12/changelog/2.12/_index.en.md
  content/kubermatic/v2.12/changelog/_index.en.md
  content/kubermatic/v2.13/changelog/2.10/_index.en.md
  content/kubermatic/v2.13/changelog/2.11/_index.en.md
  content/kubermatic/v2.13/changelog/2.12/_index.en.md
  content/kubermatic/v2.13/changelog/2.13/_index.en.md
  content/kubermatic/v2.13/changelog/_index.en.md
  content/kubermatic/v2.14/changelog/2.10/_index.en.md
  content/kubermatic/v2.14/changelog/2.11/_index.en.md
  content/kubermatic/v2.14/changelog/2.12/_index.en.md
  content/kubermatic/v2.14/changelog/2.13/_index.en.md
  content/kubermatic/v2.14/changelog/2.14/_index.en.md
  content/kubermatic/v2.14/changelog/_index.en.md
  content/kubermatic/v2.15/changelog/2.10/_index.en.md
  content/kubermatic/v2.15/changelog/2.11/_index.en.md
  content/kubermatic/v2.15/changelog/2.12/_index.en.md
  content/kubermatic/v2.15/changelog/2.13/_index.en.md
  content/kubermatic/v2.15/changelog/2.14/_index.en.md
  content/kubermatic/v2.15/changelog/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/XXL

#480 Update description of the addon form fields
  content/kubermatic/master/advanced/addons/_index.en.md
  static/img/kubermatic/master/advanced/addons/form.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#476 Document the new addon image tag suffix
  content/kubermatic/master/advanced/addons/_index.en.md
  content/kubermatic/v2.15/advanced/addons/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#478 Stay on the same page when switching between product versions
  layouts/partials/menu.html
Labels: KKP, KubeCarrier, KubeOne, approved, dco-signoff: yes, lgtm, size/L

#479 Document custom CA's in KKP
  content/kubermatic/master/advanced/custom_ca/_index.en.md
  content/kubermatic/v2.15/advanced/custom_ca/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/L
