Repository kubermatic/docs, pull requests merged in 2020-09, with the labels that each got.

#440 kubeone: notice about GCE terraform gymnastics
  content/kubeone/master/infrastructure/terraform_configs.en.md
  content/kubeone/master/provisioning/_index.en.md
  content/kubeone/v1.0/infrastructure/terraform_configs.en.md
  content/kubeone/v1.0/provisioning/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#442 Kubermatic Installer
  content/kubermatic/master/installation/add_seed_cluster/_index.en.md
  content/kubermatic/master/installation/add_seed_cluster_ee/_index.en.md
  content/kubermatic/master/installation/install_kubermatic/_index.en.md
  content/kubermatic/master/installation/install_kubermatic_ee/_index.en.md
  content/kubermatic/master/installation/logging_stack/_index.en.md
  content/kubermatic/master/installation/monitoring_stack/_index.en.md
  content/kubermatic/master/installation/securing_services/_index.en.md
  content/kubermatic/v2.15/installation/add_seed_cluster/_index.en.md
  content/kubermatic/v2.15/installation/add_seed_cluster_ee/_index.en.md
  content/kubermatic/v2.15/installation/install_kubermatic/_index.en.md
  content/kubermatic/v2.15/installation/install_kubermatic_ee/_index.en.md
  content/kubermatic/v2.15/installation/logging_stack/_index.en.md
  content/kubermatic/v2.15/installation/monitoring_stack/_index.en.md
  content/kubermatic/v2.15/installation/securing_services/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/XXL

#447 Kubermatic 2.15 Migration Paths
  content/kubermatic/master/upgrading/2.14_to_2.15/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/chart_migration/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/kubermatic_chart/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/kubermatic_operator/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/L

#446 Add Kubermatic Kubernetes compat matrix
  content/kubermatic/master/installation/compatibility/_index.en.md
  content/kubermatic/v2.15/installation/compatibility/_index.en.md
Labels: KKP, approved, dco-signoff: yes, lgtm, size/L
