Repository kubermatic/docs, pull requests merged in 2020-06, with the labels that each got.

#323 Add Open Policy Agent Gatekeeper
  content/kubermatic/master/advanced/addons/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#328 Add the KubeOne v1beta1 API migration docs and the API changelog
  content/kubeone/master/using_kubeone/api_migration.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#314 Update theming documentation
  .gitignore
  content/kubermatic/master/advanced/custom_ui/_index.en.md
  static/img/master/advanced/custom-ui/custom-theme.png
  static/img/master/advanced/custom-ui/customizing-account.png
  static/img/master/advanced/custom-ui/developer-tools.png
  static/img/master/advanced/custom-ui/result.png
  static/img/master/advanced/custom-ui/themes-dir.png
  static/img/master/advanced/custom-ui/view.png
Labels: approved, lgtm, size/L

#330 [Kubermatic] Document promtail upgrade steps
  content/kubermatic/master/upgrading/2.14_to_2.15/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#332 changelog for v2.14.0
  content/kubermatic/master/changelog/2.14/_index.en.md
  content/kubermatic/v2.14/changelog/2.14/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#333 update changelog for v2.13
  content/kubermatic/master/changelog/2.13/_index.en.md
  content/kubermatic/v2.13/changelog/2.13/_index.en.md
  content/kubermatic/v2.14/changelog/2.13/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#334 update changelog for v2.12
  content/kubermatic/master/changelog/2.12/_index.en.md
  content/kubermatic/v2.12/changelog/2.12/_index.en.md
  content/kubermatic/v2.13/changelog/2.12/_index.en.md
  content/kubermatic/v2.14/changelog/2.12/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#331 [Kubermatic] document the removed default credentials in Kubermatic
  content/kubermatic/master/upgrading/2.14_to_2.15/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#326 Add kubecarrier v0.1 release
  content/kubecarrier/v0.1/_index.md
  content/kubecarrier/v0.1/api_reference/_index.md
  content/kubecarrier/v0.1/architecture/_index.md
  content/kubecarrier/v0.1/getting_started/_index.md
  content/kubecarrier/v0.1/getting_started/accounts.md
  content/kubecarrier/v0.1/getting_started/catalogs.md
  content/kubecarrier/v0.1/getting_started/clusters.md
  content/kubecarrier/v0.1/getting_started/crds.md
  content/kubecarrier/v0.1/getting_started/installation.md
  content/kubecarrier/v0.1/getting_started/requirements.md
  content/kubecarrier/v0.1/glossary/_index.md
  content/kubecarrier/v0.1/img/KubeCarrier.png
  content/kubecarrier/v0.1/repository_organization/_index.md
  data/products.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#233 Add FAQ for Azure provider
  content/kubermatic/master/faq/_index.en.md
  content/kubermatic/master/faq/azure/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#340 Rework FAQ section
  content/kubermatic/master/faq/_index.en.md
  content/kubermatic/master/faq/azure/_index.en.md
  content/kubermatic/master/faq/dashboard/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#342 Fixed KubeOne doc
  content/kubeone/master/_index.en.md
  content/kubeone/master/getting_started/aws.en.md
  content/kubermatic/master/installation/install_kubernetes/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#337 [Kubermatic] cert-manager/Velero CRD handling
  content/kubermatic/master/installation/install_kubermatic/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#344 Change urls to point to v0.1.0
  content/kubecarrier/v0.1/getting_started/accounts.md
  content/kubecarrier/v0.1/getting_started/catalogs.md
  content/kubecarrier/v0.1/getting_started/clusters.md
  content/kubecarrier/v0.1/getting_started/crds.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#346 fix runbook generation
  Makefile
  OWNERS
  data/kubermatic/master/runbook.json
  hack/convert-runbook.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#345 Add apiserver docs, update api reference
  content/kubecarrier/master/api_reference/_index.md
  content/kubecarrier/master/architecture/_index.md
  content/kubecarrier/master/getting_started/10_requirements.md
  content/kubecarrier/master/getting_started/20_installation.md
  content/kubecarrier/master/getting_started/30_accounts.md
  content/kubecarrier/master/getting_started/40_clusters.md
  content/kubecarrier/master/getting_started/50_catalogs.md
  content/kubecarrier/master/getting_started/60_crds.md
  content/kubecarrier/master/getting_started/70_api_access.md
  content/kubecarrier/master/img/Swagger_apikey.png
Labels: approved, dco-signoff: yes, lgtm, size/XL

#347 Add KubeCarrier v0.2 release
  content/kubecarrier/v0.2/_index.md
  content/kubecarrier/v0.2/api_reference/_index.md
  content/kubecarrier/v0.2/architecture/_index.md
  content/kubecarrier/v0.2/getting_started/10_requirements.md
  content/kubecarrier/v0.2/getting_started/20_installation.md
  content/kubecarrier/v0.2/getting_started/30_accounts.md
  content/kubecarrier/v0.2/getting_started/40_clusters.md
  content/kubecarrier/v0.2/getting_started/50_catalogs.md
  content/kubecarrier/v0.2/getting_started/60_crds.md
  content/kubecarrier/v0.2/getting_started/70_api_access.md
  content/kubecarrier/v0.2/getting_started/_index.md
  content/kubecarrier/v0.2/glossary/_index.md
  content/kubecarrier/v0.2/img/KubeCarrier.png
  content/kubecarrier/v0.2/img/Swagger_apikey.png
  content/kubecarrier/v0.2/repository_organization/_index.md
  data/products.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#348 fix convert-runbook.sh permissions
  CODE_OF_CONDUCT.md
  NOTICE
  hack/convert-runbook.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#349 change make preview to docker based setup
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#351 add kubeone GCE service account description
  content/kubeone/master/getting_started/gce.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#343 Fixes for CE Kubermatic install
  content/kubermatic/master/installation/install_kubermatic/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S
