Repository kubermatic/docs, pull requests merged in 2020-04, with the labels that each got.

#244 update preset doc
  content/kubermatic/master/advanced/presets/_index.en.md
Labels: approved, lgtm, size/L

#261 Initial implementation of the KubeOne website
  config.toml
  content/kubeone/_index.md
  content/kubeone/master/_index.en.md
  content/kubeone/master/frequently_asked_questions/_index.en.md
  content/kubeone/master/getting_started/_index.en.md
  content/kubeone/master/getting_started/aws/_index.en.md
  content/kubeone/master/getting_started/azure/_index.en.md
  content/kubeone/master/getting_started/digitalocean/_index.en.md
  content/kubeone/master/getting_started/gce/_index.en.md
  content/kubeone/master/getting_started/hetzner/_index.en.md
  content/kubeone/master/getting_started/openstack/_index.en.md
  content/kubeone/master/getting_started/packet/_index.en.md
  content/kubeone/master/getting_started/vsphere/_index.en.md
  content/kubeone/master/using_kubeone/_index.en.md
  content/kubeone/master/using_kubeone/addons/_index.en.md
  content/kubeone/master/using_kubeone/api_migration/_index.en.md
  content/kubeone/master/using_kubeone/environment_variables/_index.en.md
  content/kubeone/master/using_kubeone/example_loadbalancer/_index.en.md
  content/kubeone/master/using_kubeone/manual_cluster_repair/_index.en.md
  content/kubeone/master/using_kubeone/proxy/_index.en.md
  content/kubeone/master/using_kubeone/ssh/_index.en.md
  content/kubeone/master/using_kubeone/upgrading_cluster/_index.en.md
  data/version.yaml
  layouts/shortcodes/redirectkubeone.html
Labels: approved, lgtm, size/XXL

#263 Update getting started docs
  content/kubermatic/master/getting_started/create_cluster/_index.en.md
  content/kubermatic/master/getting_started/manage_cluster/_index.en.md
  content/kubermatic/master/getting_started/manage_projects/_index.en.md
  content/kubermatic/v2.13/getting_started/create_cluster/_index.en.md
  content/kubermatic/v2.13/getting_started/manage_cluster/_index.en.md
  content/kubermatic/v2.13/getting_started/manage_projects/_index.en.md
  static/img/2.13/getting_started/create_cluster/wizard-dc.png
  static/img/2.13/getting_started/create_cluster/wizard-provider.png
  static/img/2.13/getting_started/create_cluster/wizard-settings.png
  static/img/2.13/getting_started/create_cluster/wizard-spec.png
  static/img/2.13/getting_started/create_cluster/wizard-summary.png
  static/img/2.13/getting_started/manage_cluster/cluster-add-nd.png
  static/img/2.13/getting_started/manage_cluster/cluster-details.png
  static/img/2.13/getting_started/manage_cluster/cluster-list.png
  static/img/2.13/getting_started/manage_projects/projects-add.png
  static/img/2.13/getting_started/manage_projects/projects-empty.png
  static/img/2.13/getting_started/manage_projects/projects-list.png
  static/img/2.13/getting_started/manage_projects/projects-member.png
  static/img/2.13/getting_started/manage_projects/projects-sa.png
  static/img/getting_started/create_cluster/kubermatic_00.png
  static/img/getting_started/create_cluster/kubermatic_01.png
  static/img/getting_started/create_cluster/kubermatic_02.png
  static/img/getting_started/create_cluster/kubermatic_03.png
  static/img/getting_started/create_cluster/kubermatic_04.png
  static/img/getting_started/create_cluster/kubermatic_05.png
  static/img/getting_started/manage_cluster/kubermatic_00.png
  static/img/getting_started/manage_cluster/kubermatic_01.png
  static/img/getting_started/manage_cluster/kubermatic_02.png
  static/img/getting_started/manage_cluster/kubermatic_03.png
  static/img/getting_started/manage_projects/projects_00.png
  static/img/getting_started/manage_projects/projects_01.png
  static/img/getting_started/manage_projects/projects_02.png
  static/img/getting_started/manage_projects/projects_03.png
  static/img/master/getting_started/create_cluster/wizard-dc.png
  static/img/master/getting_started/create_cluster/wizard-provider.png
  static/img/master/getting_started/create_cluster/wizard-settings.png
  static/img/master/getting_started/create_cluster/wizard-spec.png
  static/img/master/getting_started/create_cluster/wizard-summary.png
  static/img/master/getting_started/manage_cluster/cluster-add-nd.png
  static/img/master/getting_started/manage_cluster/cluster-details.png
  static/img/master/getting_started/manage_cluster/cluster-list.png
  static/img/master/getting_started/manage_projects/projects-add.png
  static/img/master/getting_started/manage_projects/projects-empty.png
  static/img/master/getting_started/manage_projects/projects-list.png
  static/img/master/getting_started/manage_projects/projects-member.png
  static/img/master/getting_started/manage_projects/projects-sa.png
Labels: approved, lgtm, size/L

#270 Switch logo depending on the product
  data/version.yaml
  layouts/partials/logo.html
  static/img/header-logo-kubeone.png
Labels: approved, lgtm, size/S

#264 document predefined user cluster roles and cluster roles
  content/kubermatic/master/advanced/oidc_auth/_index.en.md
  static/img/advanced/oidc_auth/add_binding_rbac.png
  static/img/advanced/oidc_auth/cluster_owner_rbac.png
Labels: approved, lgtm, size/S

#268 document user settings
  content/kubermatic/master/advanced/user_settings/_index.en.md
  content/kubermatic/v2.13/advanced/user_settings/_index.en.md
  static/img/advanced/user_settings/menu-v2-13.png
  static/img/advanced/user_settings/menu.png
  static/img/advanced/user_settings/view-v2-13.png
  static/img/advanced/user_settings/view.png
Labels: approved, lgtm, size/M

#271 Fix issues mentioned in #266
  content/kubermatic/master/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/master/changelog/2.13/_index.en.md
  content/kubermatic/v2.13/changelog/2.13/_index.en.md
Labels: approved, lgtm, size/XS

#273 Update the KubeOne FAQ
  content/kubeone/master/frequently_asked_questions/_index.en.md
Labels: approved, lgtm, size/L

#272 Update images
  content/kubermatic/master/advanced/addons/_index.en.md
  content/kubermatic/master/advanced/custom_links/_index.en.md
  content/kubermatic/master/advanced/oidc_auth/_index.en.md
  content/kubermatic/master/advanced/user_settings/_index.en.md
  content/kubermatic/master/getting_started/manage_projects/_index.en.md
  content/kubermatic/master/operation/control-plane/upgrading/_index.en.md
  content/kubermatic/v2.12/advanced/oidc_auth/_index.en.md
  content/kubermatic/v2.12/getting_started/create_cluster/_index.en.md
  content/kubermatic/v2.12/getting_started/manage_cluster/_index.en.md
  content/kubermatic/v2.12/getting_started/manage_projects/_index.en.md
  content/kubermatic/v2.12/operation/control-plane/upgrading/_index.en.md
  content/kubermatic/v2.13/advanced/addons/_index.en.md
  content/kubermatic/v2.13/advanced/custom_links/_index.en.md
  content/kubermatic/v2.13/advanced/oidc_auth/_index.en.md
  content/kubermatic/v2.13/advanced/user_settings/_index.en.md
  content/kubermatic/v2.13/getting_started/manage_projects/_index.en.md
  content/kubermatic/v2.13/operation/control-plane/upgrading/_index.en.md
  static/img/2.12/advanced/oidc-auth/share-cluster-modal.png
  static/img/2.12/advanced/oidc-auth/share-cluster.png
  static/img/2.12/getting_started/create_cluster/kubermatic_00.png
  static/img/2.12/getting_started/create_cluster/kubermatic_01.png
  static/img/2.12/getting_started/create_cluster/kubermatic_02.png
  static/img/2.12/getting_started/create_cluster/kubermatic_03.png
  static/img/2.12/getting_started/create_cluster/kubermatic_04.png
  static/img/2.12/getting_started/create_cluster/kubermatic_05.png
  static/img/2.12/getting_started/manage_cluster/kubermatic_00.png
  static/img/2.12/getting_started/manage_cluster/kubermatic_01.png
  static/img/2.12/getting_started/manage_cluster/kubermatic_02.png
  static/img/2.12/getting_started/manage_cluster/kubermatic_03.png
  static/img/2.12/getting_started/manage_projects/projects_00.png
  static/img/2.12/getting_started/manage_projects/projects_01.png
  static/img/2.12/getting_started/manage_projects/projects_02.png
  static/img/2.12/getting_started/manage_projects/projects_03.png
  static/img/2.12/operation/control-plane/upgrade-warning.png
  static/img/2.13/advanced/addons/form.png
  static/img/2.13/advanced/addons/view.png
  static/img/2.13/advanced/oidc-auth/share-cluster-modal.png
  static/img/2.13/advanced/oidc-auth/share-cluster.png
  static/img/2.13/advanced/settings/menu.png
  static/img/2.13/advanced/settings/view.png
  static/img/2.13/advanced/user-settings/menu.png
  static/img/2.13/advanced/user-settings/view.png
  static/img/2.13/operation/control-plane/upgrade-warning.png
  static/img/advanced/user_settings/menu-v2-13.png
  static/img/advanced/user_settings/view-v2-13.png
  static/img/master/advanced/addons/form.png
  static/img/master/advanced/addons/view.png
  static/img/master/advanced/oidc-auth/add-binding-rbac.png
  static/img/master/advanced/oidc-auth/cluster-owner-rbac.png
  static/img/master/advanced/oidc-auth/share-cluster-modal.png
  static/img/master/advanced/oidc-auth/share-cluster.png
  static/img/master/advanced/settings/menu.png
  static/img/master/advanced/settings/view.png
  static/img/master/advanced/user-settings/menu.png
  static/img/master/advanced/user-settings/view.png
  static/img/master/operation/control-plane/upgrade-warning.png
Labels: approved, lgtm, size/M

#276 Add the KubeOne landing page
  content/kubeone/master/_index.en.md
Labels: approved, lgtm, size/L

#277 Invert the condition of displaying the Table of contents
  content/kubeone/master/_index.en.md
  content/kubeone/master/frequently_asked_questions/_index.en.md
  content/kubeone/master/getting_started/_index.en.md
  content/kubeone/master/using_kubeone/_index.en.md
  layouts/partials/header.html
  static/css/theme-kubermatic.css
Labels: approved, lgtm, size/S

#279 Update Hugo to v0.68.3
  netlify.toml
Labels: approved, lgtm, size/XS

#280 change duplicate weights in advanced articles to unambiguous values
  content/kubermatic/master/advanced/addons/_index.en.md
  content/kubermatic/master/advanced/custom_links/_index.en.md
  content/kubermatic/master/advanced/custom_ui/_index.en.md
  content/kubermatic/master/advanced/oidc_auth/_index.en.md
  content/kubermatic/master/advanced/oidc_config/_index.en.md
  content/kubermatic/master/advanced/presets/_index.en.md
  content/kubermatic/master/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/master/advanced/service_account/_index.en.md
  content/kubermatic/master/advanced/user_settings/_index.en.md
  content/kubermatic/master/advanced/versions_updates/_index.en.md
Labels: approved, lgtm, size/S

#283 Update tutorial images for master version
  content/kubermatic/master/tutorials/02-add-ssh-key/02-add-ssh-key-dialog.png
  content/kubermatic/master/tutorials/02-add-ssh-key/02-add-ssh-key-overview.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-api-tokens.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-choose-name.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-choose-provider.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-choose-region.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-confirm.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-creation.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-node-settings.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-ssh-key-selected.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-ssh-key.png
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-start.png
  content/kubermatic/master/tutorials/04-upgrade-cluster/04-upgrade-cluster-arrow.png
  content/kubermatic/master/tutorials/04-upgrade-cluster/04-upgrade-cluster-select-version.png
  content/kubermatic/master/tutorials/05-delete-cluster/05-delete-cluster-confirm.png
  content/kubermatic/master/tutorials/05-delete-cluster/05-delete-cluster-delete-button.png
  content/kubermatic/master/tutorials/05-delete-cluster/05-delete-cluster-overview.png
  content/kubermatic/master/tutorials/06-download-kubeconfig/06-download-kubeconfig-button.png
  content/kubermatic/master/tutorials/06-download-kubeconfig/06-download-kubeconfig-more.png
  content/kubermatic/master/tutorials/06-download-kubeconfig/06-download-kubeconfig-revoke.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/08-manage-node-deployments-edit-dialog.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/08-manage-node-deployments-edit.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/08-manage-node-deployments-overview.png
Labels: approved, lgtm, size/XS

#278 Update theme documentation
  content/kubermatic/master/advanced/custom_ui/_index.en.md
  content/kubermatic/master/advanced/user_settings/_index.en.md
  content/kubermatic/v2.12/advanced/custom_ui/_index.en.md
  content/kubermatic/v2.13/advanced/custom_ui/_index.en.md
  static/img/2.12/advanced/custom-ui/result.png
  static/img/2.13/advanced/custom-ui/result.png
  static/img/master/advanced/custom-ui/result.png
  static/img/master/advanced/custom-ui/view.png
Labels: approved, lgtm, size/L

#282 Update the KubeOne AWS quickstart
  content/kubeone/master/getting_started/aws/_index.en.md
Labels: approved, lgtm, size/L

#284 added Dynamic Kubelet configuration page
  content/kubermatic/master/advanced/dynamic_kubelet_config/_index.en.md
  content/kubermatic/master/advanced/dynamic_kubelet_config/add_node.png
  content/kubermatic/v2.13/advanced/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.13/advanced/dynamic_kubelet_config/add_node.png
Labels: approved, lgtm, size/M

#274 Make logo redirect to the landing page
  layouts/partials/logo.html
Labels: approved, lgtm, size/S

#275 doc kubermatic rbac
  content/kubermatic/master/concepts/roles/_index.en.md
Labels: approved, lgtm, size/M

#285 [kubeone] pull docs from inside sections
  content/kubeone/master/getting_started/aws.en.md
  content/kubeone/master/getting_started/azure.en.md
  content/kubeone/master/getting_started/digitalocean.en.md
  content/kubeone/master/getting_started/gce.en.md
  content/kubeone/master/getting_started/hetzner.en.md
  content/kubeone/master/getting_started/openstack.en.md
  content/kubeone/master/getting_started/packet.en.md
  content/kubeone/master/getting_started/vsphere.en.md
  content/kubeone/master/using_kubeone/addons.en.md
  content/kubeone/master/using_kubeone/api_migration.en.md
  content/kubeone/master/using_kubeone/environment_variables.en.md
  content/kubeone/master/using_kubeone/example_loadbalancer.en.md
  content/kubeone/master/using_kubeone/manual_cluster_repair.en.md
  content/kubeone/master/using_kubeone/proxy.en.md
  content/kubeone/master/using_kubeone/ssh.en.md
  content/kubeone/master/using_kubeone/upgrading_cluster.en.md
Labels: approved, lgtm, size/S

#286 Update the KubeOne Azure quickstart
  content/kubeone/master/getting_started/aws.en.md
  content/kubeone/master/getting_started/azure.en.md
Labels: approved, lgtm, size/L

#287 Update the KubeOne DigitalOcean quickstart
  content/kubeone/master/getting_started/digitalocean.en.md
Labels: approved, lgtm, size/L

#290 Update the KubeOne Hetzner quickstart
  content/kubeone/master/getting_started/hetzner.en.md
Labels: approved, lgtm, size/L

#288 Update the KubeOne GCE quickstart
  content/kubeone/master/getting_started/gce.en.md
Labels: approved, lgtm, size/L

#291 Update the KubeOne OpenStack quickstart
  content/kubeone/master/getting_started/openstack.en.md
Labels: approved, lgtm, size/L

#292 Update the KubeOne Packet quickstart
  content/kubeone/master/getting_started/packet.en.md
Labels: approved, lgtm, size/L

#293 Update the KubeOne vSphere quickstart
  content/kubeone/master/getting_started/vsphere.en.md
Labels: approved, lgtm, size/L

#294 Improve the KubeOne docs
  content/kubeone/master/using_kubeone/addons.en.md
  content/kubeone/master/using_kubeone/api_migration.en.md
  content/kubeone/master/using_kubeone/environment_variables.en.md
  content/kubeone/master/using_kubeone/example_loadbalancer.en.md
  content/kubeone/master/using_kubeone/manual_cluster_repair.en.md
  content/kubeone/master/using_kubeone/proxy.en.md
  content/kubeone/master/using_kubeone/ssh.en.md
  content/kubeone/master/using_kubeone/upgrading_cluster.en.md
Labels: approved, lgtm, size/L

#296 Restructure data files
  content/kubermatic/master/concepts/kubermaticconfiguration/_index.en.md
  content/kubermatic/master/concepts/seeds/_index.en.md
  content/kubermatic/master/data/addondata.go
  content/kubermatic/master/data/kubermaticConfiguration.yaml
  content/kubermatic/master/data/seed.yaml
  content/kubermatic/v2.12/concepts/seeds/_index.en.md
  content/kubermatic/v2.12/data/seed.yaml
  content/kubermatic/v2.13/concepts/seeds/_index.en.md
  content/kubermatic/v2.13/data/seed.yaml
  convert-runbook.sh
  data/kubermatic/master/runbook.json
  data/kubermatic/v2.12/runbook.json
  data/kubermatic/v2.13/runbook.json
  layouts/runbook/list.html
  layouts/shortcodes/redirect.html
Labels: approved, lgtm, size/XXL

#246 update addon doc
  content/kubermatic/master/advanced/addons/_index.en.md
  content/kubermatic/master/upgrading/2.13_to_2.14/_index.en.md
Labels: approved, lgtm, size/L

#250 Fix addons documentation
  content/kubermatic/v2.12/advanced/addons/_index.en.md
  content/kubermatic/v2.13/advanced/addons/_index.en.md
Labels: approved, lgtm, size/M

#297 Kubeone backups addon
  content/kubeone/master/data/backups-restic.yaml
  content/kubeone/master/using_kubeone/backups-addon.en.md
Labels: approved, lgtm, size/L

#298 fix baseurl
  config.toml
Labels: approved, lgtm, size/XS

#295 Update KubeOne docs for the v0.11.1 release
  content/kubeone/master/getting_started/aws.en.md
  content/kubeone/master/getting_started/azure.en.md
  content/kubeone/master/getting_started/digitalocean.en.md
  content/kubeone/master/getting_started/gce.en.md
  content/kubeone/master/getting_started/hetzner.en.md
  content/kubeone/master/getting_started/openstack.en.md
  content/kubeone/master/getting_started/packet.en.md
  content/kubeone/master/getting_started/vsphere.en.md
Labels: approved, lgtm, size/S

#299 remove unused data files
  data/addondata.go
  data/kubermaticConfiguration.yaml
  data/seed.yaml
Labels: approved, lgtm, size/XL

#289 Add documentation on PSP
  content/kubermatic/master/tutorials/13-psp/01-create-cluster.png
  content/kubermatic/master/tutorials/13-psp/01-edit-cluster.png
  content/kubermatic/master/tutorials/13-psp/_index.en.md
Labels: approved, lgtm, size/M

#301 Add documentation for KubeOne static wokers
  content/kubeone/master/using_kubeone/static_workers.md
Labels: approved, lgtm, size/M

#281 Audit logs
  content/kubermatic/master/data/policy.yaml
  content/kubermatic/master/tutorials/12-audit-logs/01-create-cluster.png
  content/kubermatic/master/tutorials/12-audit-logs/01-edit-cluster.png
  content/kubermatic/master/tutorials/12-audit-logs/_index.en.md
Labels: approved, lgtm, size/M

#300 Document how to recover KubeOne cluster from the backup
  content/kubeone/master/data/backups-restic.yaml
  content/kubeone/master/using_kubeone/manual_cluster_recovery.en.md
Labels: approved, lgtm, size/L

#302 Add KubeCarrier Documentation
  config.toml
  content/kubecarrier/_index.md
  content/kubecarrier/docs-sync/img/KubeCarrier.svg
  content/kubecarrier/docs-sync/manifests/accounts.yaml
  content/kubecarrier/docs-sync/manifests/catalog.yaml
  content/kubecarrier/docs-sync/manifests/catalogentryset.yaml
  content/kubecarrier/docs-sync/manifests/couchdb.crd.yaml
  content/kubecarrier/docs-sync/manifests/couchdb.eu-west-1.yaml
  content/kubecarrier/docs-sync/manifests/servicecluster.yaml
  content/kubecarrier/master/_index.md
  content/kubecarrier/master/api_reference/_index.md
  content/kubecarrier/master/architecture/_index.md
  content/kubecarrier/master/getting_started/10_requirements.md
  content/kubecarrier/master/getting_started/20_installation.md
  content/kubecarrier/master/getting_started/30_accounts.md
  content/kubecarrier/master/getting_started/40_clusters.md
  content/kubecarrier/master/getting_started/50_catalogs.md
  content/kubecarrier/master/getting_started/60_crds.md
  content/kubecarrier/master/getting_started/_index.md
  content/kubecarrier/master/glossary/_index.md
  content/kubecarrier/master/img/KubeCarrier.png
  content/kubecarrier/master/repository_organization/_index.md
  data/version.yaml
  layouts/shortcodes/redirectkubecarrier.html
  static/img/header-logo-kubecarrier.png
Labels: approved, lgtm, size/XL

#303 [kubeone] --manifest flag
  content/kubeone/master/_index.en.md
  content/kubeone/master/getting_started/aws.en.md
  content/kubeone/master/getting_started/azure.en.md
  content/kubeone/master/getting_started/digitalocean.en.md
  content/kubeone/master/getting_started/gce.en.md
  content/kubeone/master/getting_started/hetzner.en.md
  content/kubeone/master/getting_started/openstack.en.md
  content/kubeone/master/getting_started/packet.en.md
  content/kubeone/master/getting_started/vsphere.en.md
  content/kubeone/master/using_kubeone/addons.en.md
  content/kubeone/master/using_kubeone/manual_cluster_recovery.en.md
  content/kubeone/master/using_kubeone/manual_cluster_repair.en.md
Labels: approved, lgtm, size/M

#304 Document how to use the KubeOne credentials file
  content/kubeone/master/using_kubeone/provider_credentials.en.md
Labels: approved, lgtm, size/M
