Repository kubermatic/docs, pull requests merged in 2020-08, with the labels that each got.

#392 rename Kubecarrier service catalog to service hub
  content/kubecarrier/master/_index.md
  content/kubecarrier/master/getting_started/50_catalogs.md
  content/kubecarrier/v0.1/_index.md
  content/kubecarrier/v0.1/getting_started/catalogs.md
  content/kubecarrier/v0.2/_index.md
  content/kubecarrier/v0.2/getting_started/50_catalogs.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#396 Add the KubeOne Prerequisites documents
  content/kubeone/master/prerequisites/_index.en.md
  content/kubeone/master/prerequisites/credentials.en.md
  content/kubeone/master/prerequisites/ssh.en.md
  content/kubeone/master/using_kubeone/provider_credentials.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#386 Update the KubeCarrier docs
  content/kubecarrier/master/_index.md
  content/kubecarrier/master/api_reference/_index.md
  content/kubecarrier/master/getting_started/50_catalogs.md
  content/kubecarrier/master/getting_started/60_crds.md
  content/kubecarrier/v0.1/_index.md
  content/kubecarrier/v0.1/getting_started/requirements.md
  content/kubecarrier/v0.2/_index.md
  content/kubecarrier/v0.2/getting_started/10_requirements.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#399 Revise documentation for authentication configuration
  content/kubecarrier/master/getting_started/60_crds.md
  content/kubecarrier/master/getting_started/70_api_access.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#400 Add KubeCarrier v0.3 documentation
  content/kubecarrier/v0.3/_index.md
  content/kubecarrier/v0.3/api_reference/_index.md
  content/kubecarrier/v0.3/architecture/_index.md
  content/kubecarrier/v0.3/getting_started/10_requirements.md
  content/kubecarrier/v0.3/getting_started/20_installation.md
  content/kubecarrier/v0.3/getting_started/30_accounts.md
  content/kubecarrier/v0.3/getting_started/40_clusters.md
  content/kubecarrier/v0.3/getting_started/50_catalogs.md
  content/kubecarrier/v0.3/getting_started/60_crds.md
  content/kubecarrier/v0.3/getting_started/70_api_access.md
  content/kubecarrier/v0.3/getting_started/_index.md
  content/kubecarrier/v0.3/glossary/_index.md
  content/kubecarrier/v0.3/img/KubeCarrier.png
  content/kubecarrier/v0.3/img/Swagger_apikey.png
  content/kubecarrier/v0.3/repository_organization/_index.md
  data/products.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#389 Upgrade notes for CNI when using NetworkPolicies
  content/kubermatic/v2.12/upgrading/2.11_to_2.12/_index.en.md
  content/kubermatic/v2.13/upgrading/2.11_to_2.12/_index.en.md
  content/kubermatic/v2.14/upgrading/2.11_to_2.12/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#403 Create stub documents for the KubeOne v1.0 release
  content/kubeone/master/advanced/_index.en.md
  content/kubeone/master/advanced/addons.en.md
  content/kubeone/master/advanced/api_migration.en.md
  content/kubeone/master/advanced/calico-vxlan-addon.en.md
  content/kubeone/master/advanced/cluster_reconciliation.en.md
  content/kubeone/master/advanced/example_loadbalancer.en.md
  content/kubeone/master/advanced/proxy.en.md
  content/kubeone/master/api_reference/_index.en.md
  content/kubeone/master/infrastructure/_index.en.md
  content/kubeone/master/infrastructure/production.en.md
  content/kubeone/master/infrastructure/terraform.en.md
  content/kubeone/master/infrastructure/terraform_integration.en.md
  content/kubeone/master/maintenance/_index.en.md
  content/kubeone/master/maintenance/backups-addon.en.md
  content/kubeone/master/maintenance/manual_cluster_recovery.en.md
  content/kubeone/master/maintenance/manual_cluster_repair.en.md
  content/kubeone/master/provisioning/_index.en.md
  content/kubeone/master/provisioning/config.en.md
  content/kubeone/master/provisioning/provision.en.md
  content/kubeone/master/upgrading/_index.en.md
  content/kubeone/master/upgrading/upgrading_cluster.en.md
  content/kubeone/master/workers/_index.en.md
  content/kubeone/master/workers/machine_deployments.en.md
  content/kubeone/master/workers/static_workers.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#398 Improvements to Concepts and Prerequisites KubeOne docs
  content/kubeone/master/concepts/_index.en.md
  content/kubeone/master/prerequisites/credentials.en.md
  content/kubeone/master/prerequisites/ssh.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#402 Remove experimental warnings from seed and kubermaticconfiguration docs
  content/kubermatic/master/concepts/kubermaticconfiguration/_index.en.md
  content/kubermatic/master/concepts/seeds/_index.en.md
  content/kubermatic/master/data/kubermaticConfiguration.yaml
  content/kubermatic/master/data/seed.yaml
  content/kubermatic/v2.14/concepts/kubermaticconfiguration/_index.en.md
  content/kubermatic/v2.14/concepts/seeds/_index.en.md
  content/kubermatic/v2.14/data/kubermaticConfiguration.yaml
  content/kubermatic/v2.14/data/seed.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#404 Add shortcode for tabs
  assets/scss/_tabs.scss
  assets/scss/app.scss
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
  themes/hugo-theme-learn/static/js/learn.js
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/L

#406 kubeone: Initial Infrastructure documents
  content/kubeone/master/concepts/_index.en.md
  content/kubeone/master/infrastructure/_index.en.md
  content/kubeone/master/infrastructure/production_recommendations.en.md
  content/kubeone/master/infrastructure/requirements.en.md
  content/kubeone/master/infrastructure/terraform.en.md
  content/kubeone/master/infrastructure/terraform_integration.en.md
  content/kubeone/master/infrastructure/terraform_scripts.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#407 stop referencing cloud.kubermatic.io
  content/kubermatic/master/getting_started/create_cluster/_index.en.md
  content/kubermatic/v2.12/getting_started/create_cluster/_index.en.md
  content/kubermatic/v2.13/getting_started/create_cluster/_index.en.md
  content/kubermatic/v2.14/getting_started/create_cluster/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#408 Added generated v1beta1 kubeone API
  content/kubeone/master/api_reference/v1beta1.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#410 kubeone: add the creating infrastructure document
  content/kubeone/master/infrastructure/terraform_scripts.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#411 Replace Terraform scripts with Terraform configs
  content/kubeone/master/compatibility_info/_index.en.md
  content/kubeone/master/getting_kubeone/_index.en.md
  content/kubeone/master/infrastructure/_index.en.md
  content/kubeone/master/infrastructure/requirements.en.md
  content/kubeone/master/infrastructure/terraform_configs.en.md
  content/kubeone/master/prerequisites/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#412 kubeone: add the terraform integration document
  content/kubeone/master/infrastructure/terraform_integration.en.md
Labels: approved, lgtm

#413 kubeone: add note about terraform configs on Arch Linux
  content/kubeone/master/api_reference/_index.en.md
  content/kubeone/master/infrastructure/terraform_configs.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#414 Fixing Grammar and spelling
  content/kubeone/v1.0/frequently_asked_questions/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#415 kubeone: add the provisioning document
  content/kubeone/master/provisioning/_index.en.md
  content/kubeone/master/provisioning/config.en.md
  content/kubeone/master/provisioning/provision.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#416 kubeone: upgrade upgrading docs
  content/kubeone/master/upgrading/_index.en.md
  content/kubeone/master/upgrading/upgrading_cluster.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#417 kubeone: minor updates to the reapir document
  content/kubeone/master/maintenance/manual_cluster_repair.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#418 kubeone: improve the maintenance docs
  content/kubeone/master/maintenance/manual_cluster_recovery.en.md
  content/kubeone/master/maintenance/manual_cluster_repair.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#419 kubeone: add more details about credentials
  content/kubeone/master/prerequisites/credentials.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#420 [kubeone] Production recommendations
  content/kubeone/master/infrastructure/production_recommendations.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#421 kubeone: document unprovisioning
  content/kubeone/master/advanced/_index.en.md
  content/kubeone/master/api_reference/_index.en.md
  content/kubeone/master/unprovisioning/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#422 kubeone: document managing worker nodes
  content/kubeone/master/concepts/_index.en.md
  content/kubeone/master/maintenance/_index.en.md
  content/kubeone/master/workers/_index.en.md
  content/kubeone/master/workers/machine_controller.en.md
  content/kubeone/master/workers/machine_deployments.en.md
  content/kubeone/master/workers/static_workers.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#423 kubeone: remove FAQ and quickstarts, setup aliases/redirects
  content/kubeone/master/_index.en.md
  content/kubeone/master/frequently_asked_questions/_index.en.md
  content/kubeone/master/provisioning/_index.en.md
  content/kubeone/master/quickstarts/_index.en.md
  content/kubeone/master/quickstarts/aws.en.md
  content/kubeone/master/quickstarts/azure.en.md
  content/kubeone/master/quickstarts/digitalocean.en.md
  content/kubeone/master/quickstarts/gce.en.md
  content/kubeone/master/quickstarts/hetzner.en.md
  content/kubeone/master/quickstarts/openstack.en.md
  content/kubeone/master/quickstarts/packet.en.md
  content/kubeone/master/quickstarts/vsphere.en.md
  content/kubeone/master/workers/machine_controller.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#424 kubeone: update advanced docs
  content/kubeone/master/advanced/addons.en.md
  content/kubeone/master/advanced/api_migration.en.md
  content/kubeone/master/advanced/calico-vxlan-addon.en.md
  content/kubeone/master/advanced/cluster_reconciliation.en.md
  content/kubeone/master/advanced/example_loadbalancer.en.md
  content/kubeone/master/advanced/proxy.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#426 Replace Loodse -> Kubermatic
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  Zenhub.md
  config.toml
  content/kubecarrier/master/api_reference/_index.md
  content/kubecarrier/master/getting_started/70_api_access.md
  content/kubecarrier/v0.1/api_reference/_index.md
  content/kubecarrier/v0.2/api_reference/_index.md
  content/kubecarrier/v0.2/getting_started/70_api_access.md
  content/kubecarrier/v0.3/api_reference/_index.md
  content/kubecarrier/v0.3/getting_started/70_api_access.md
  content/kubermatic/master/_index.en.md
  content/kubermatic/master/advanced/custom_links/_index.en.md
  content/kubermatic/master/advanced/oidc_auth/_index.en.md
  content/kubermatic/master/concepts/datacenters/_index.en.md
  content/kubermatic/master/installation/install_kubermatic_ee/_index.en.md
  content/kubermatic/master/upgrading/2.6_to_2.7/_index.en.md
  content/kubermatic/master/upgrading/2.8_to_2.9/_index.en.md
  content/kubermatic/v2.12/_index.en.md
  content/kubermatic/v2.12/advanced/custom_links/_index.en.md
  content/kubermatic/v2.12/advanced/oidc_auth/_index.en.md
  content/kubermatic/v2.12/concepts/datacenters/_index.en.md
  content/kubermatic/v2.12/installation/install_kubermatic/_index.en.md
  content/kubermatic/v2.12/installation/install_kubermatic/_installer.en.md
  content/kubermatic/v2.12/upgrading/2.6_to_2.7/_index.en.md
  content/kubermatic/v2.12/upgrading/2.8_to_2.9/_index.en.md
  content/kubermatic/v2.13/_index.en.md
  content/kubermatic/v2.13/advanced/custom_links/_index.en.md
  content/kubermatic/v2.13/advanced/oidc_auth/_index.en.md
  content/kubermatic/v2.13/concepts/datacenters/_index.en.md
  content/kubermatic/v2.13/installation/install_kubermatic/_index.en.md
  content/kubermatic/v2.13/installation/install_kubermatic/_installer.en.md
  content/kubermatic/v2.13/upgrading/2.6_to_2.7/_index.en.md
  content/kubermatic/v2.13/upgrading/2.8_to_2.9/_index.en.md
  content/kubermatic/v2.14/advanced/custom_links/_index.en.md
  content/kubermatic/v2.14/advanced/oidc_auth/_index.en.md
  content/kubermatic/v2.14/concepts/datacenters/_index.en.md
  content/kubermatic/v2.14/installation/install_kubermatic_ee/_index.en.md
  content/kubermatic/v2.14/upgrading/2.6_to_2.7/_index.en.md
  content/kubermatic/v2.14/upgrading/2.8_to_2.9/_index.en.md
  data/kubermatic/v2.14/runbook.json
  docker_images/remark-lint/Dockerfile
  layouts/partials/title.html
  tutorials-tests/LICENSE
  tutorials-tests/containers/cypress/utils/yamls/presets.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#429 kubeone: Rename Getting Started to Quick Start
  content/kubeone/master/quick_start/_index.en.md
  content/kubeone/v1.0/quick_start/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#430 kubeone: Add Packet to natively-supported providers
  content/kubeone/master/compatibility_info/_index.en.md
  content/kubeone/v1.0/compatibility_info/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#433 [All] Fix wording
  layouts/partials/header.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#435 add air gapped so it will be easier to find
  content/kubermatic/v2.14/advanced/offline_mode/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#434 Prometheus 2.20.1 upgrade notes
  content/kubermatic/master/upgrading/2.14_to_2.15/_index.en.md
Labels: Kubermatic, approved, dco-signoff: yes, lgtm, size/XS

#436 update owners file
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, size/S

#432 Document the change from Keycloak to OAuth2-Proxy
  content/kubermatic/master/installation/securing_services/_index.en.md
  content/kubermatic/master/upgrading/2.14_to_2.15/_index.en.md
Labels: Kubermatic, approved, dco-signoff: yes, lgtm, size/M

#431 Add upgrade note for cert-manager 0.16
  content/kubermatic/master/upgrading/2.14_to_2.15/_index.en.md
Labels: Kubermatic, approved, dco-signoff: yes, lgtm, size/XS

#439 fix typo in addon documentation
  content/kubermatic/v2.14/advanced/addons/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S
