Repository kubermatic/docs, pull requests merged in 2020-07, with the labels that each got.

#354 Update screenshots for Audit Logging and Pod Security Policy
  content/kubermatic/master/tutorials/12-audit-logs/01-create-cluster.png
  content/kubermatic/master/tutorials/12-audit-logs/01-edit-cluster.png
  content/kubermatic/master/tutorials/13-psp/01-create-cluster.png
  content/kubermatic/master/tutorials/13-psp/01-edit-cluster.png
Labels: approved, dco-signoff: yes, lgtm, size/XS

#353 Update Screenshots
  content/kubermatic/master/getting_started/manage_cluster/_index.en.md
  content/kubermatic/master/tutorials/03-create-cluster/03-create-cluster-creation.png
  content/kubermatic/master/tutorials/04-upgrade-cluster/04-upgrade-cluster-arrow.png
  content/kubermatic/master/tutorials/04-upgrade-cluster/04-upgrade-cluster-select-version.png
  content/kubermatic/master/tutorials/04-upgrade-cluster/_index.en.md
  content/kubermatic/master/tutorials/05-delete-cluster/05-delete-cluster-confirm.png
  content/kubermatic/master/tutorials/05-delete-cluster/05-delete-cluster-delete-button.png
  content/kubermatic/master/tutorials/06-download-kubeconfig/06-download-kubeconfig-button.png
  content/kubermatic/master/tutorials/06-download-kubeconfig/06-download-kubeconfig-more.png
  content/kubermatic/master/tutorials/06-download-kubeconfig/06-download-kubeconfig-revoke.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/08-manage-node-deployments-edit-dialog.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/08-manage-node-deployments-edit.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/08-manage-node-deployments-overview.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/_index.en.md
  static/img/kubermatic/master/advanced/addons/form.png
  static/img/kubermatic/master/advanced/addons/view.png
  static/img/kubermatic/master/getting_started/manage_cluster/cluster-add-nd.png
  static/img/kubermatic/master/getting_started/manage_cluster/cluster-details.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#352 fix white spaces for imagepullsecrect
  content/kubermatic/master/installation/install_kubermatic/_index.en.md
  content/kubermatic/v2.14/installation/install_kubermatic/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#358 updated changelog for v2.14.1, v2.13.6
  content/kubermatic/master/changelog/2.13/_index.en.md
  content/kubermatic/master/changelog/2.14/_index.en.md
  content/kubermatic/v2.13/changelog/2.13/_index.en.md
  content/kubermatic/v2.14/changelog/2.13/_index.en.md
  content/kubermatic/v2.14/changelog/2.14/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#357 Update Twitter handles
  content/kubermatic/v2.14/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#362 Mention official Arch Linux package
  content/kubeone/master/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/S

#363 [kubeone]: Calico addon
  content/kubeone/master/using_kubeone/calico-vxlan-addon.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#364 kubeone: Remove outdated info from README
  content/kubeone/master/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#365 kubeone: apply docs
  content/kubeone/master/using_kubeone/cluster_reconciliation.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#366 kubeone quickstarts: use v1beta1 API and --manifest flag
  content/kubeone/master/getting_started/aws.en.md
  content/kubeone/master/getting_started/azure.en.md
  content/kubeone/master/getting_started/digitalocean.en.md
  content/kubeone/master/getting_started/gce.en.md
  content/kubeone/master/getting_started/hetzner.en.md
  content/kubeone/master/getting_started/openstack.en.md
  content/kubeone/master/getting_started/packet.en.md
  content/kubeone/master/getting_started/vsphere.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#367 kubeone: update docs to v1.0.0-beta.2
  content/kubeone/master/_index.en.md
  content/kubeone/master/frequently_asked_questions/_index.en.md
  content/kubeone/master/using_kubeone/addons.en.md
  content/kubeone/master/using_kubeone/manual_cluster_recovery.en.md
  content/kubeone/master/using_kubeone/manual_cluster_repair.en.md
  content/kubeone/master/using_kubeone/proxy.en.md
  content/kubeone/master/using_kubeone/ssh.en.md
  content/kubeone/master/using_kubeone/static_workers.md
  content/kubeone/master/using_kubeone/upgrading_cluster.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#369 updated changelog for v2.14.2
  content/kubermatic/master/changelog/2.14/_index.en.md
  content/kubermatic/v2.14/changelog/2.14/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#371 Fix the KubeOne docs URL in the Install HA-Kubernetes document
  content/kubermatic/master/installation/add_seed_cluster_ee/_index.en.md
  content/kubermatic/v2.14/installation/install_kubernetes/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#370 Update KubeOne Addons docs
  content/kubeone/master/using_kubeone/addons.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#373 kubeone: improve the apply docs
  content/kubeone/master/using_kubeone/cluster_reconciliation.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#374 Changes in "Install Kubermatic CE/EE" docs
  content/kubermatic/master/installation/install_kubermatic/_index.en.md
  content/kubermatic/master/installation/install_kubermatic_ee/_index.en.md
  content/kubermatic/v2.14/installation/install_kubermatic/_index.en.md
  content/kubermatic/v2.14/installation/install_kubermatic_ee/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#375 installation docs: make the link to installer better
  content/kubermatic/master/installation/install_kubermatic/_index.en.md
  content/kubermatic/master/installation/install_kubermatic_ee/_index.en.md
  content/kubermatic/v2.14/installation/install_kubermatic/_index.en.md
  content/kubermatic/v2.14/installation/install_kubermatic_ee/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#377 Fix website from loodse
  content/kubermatic/v2.14/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#378 changelog for v2.12.9, v2.13.7, v2.14.3
  content/kubermatic/master/changelog/2.12/_index.en.md
  content/kubermatic/master/changelog/2.13/_index.en.md
  content/kubermatic/master/changelog/2.14/_index.en.md
  content/kubermatic/v2.12/changelog/2.12/_index.en.md
  content/kubermatic/v2.13/changelog/2.12/_index.en.md
  content/kubermatic/v2.13/changelog/2.13/_index.en.md
  content/kubermatic/v2.14/changelog/2.12/_index.en.md
  content/kubermatic/v2.14/changelog/2.13/_index.en.md
  content/kubermatic/v2.14/changelog/2.14/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#379 Upgrade notes for CNI
  content/kubermatic/master/upgrading/2.11_to_2.12/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#368 Update the installation manual to cope with the kubermatic-installer repo cleanup
  content/kubermatic/v2.12/installation/install_kubermatic/_installer.en.md
  content/kubermatic/v2.12/installation/install_kubermatic/_manual.en.md
  content/kubermatic/v2.13/installation/install_kubermatic/_installer.en.md
  content/kubermatic/v2.13/installation/install_kubermatic/_manual.en.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#388 kubeone: move getting started to quickstarts and add the Install KubeOne document
  content/kubeone/master/_index.en.md
  content/kubeone/master/getting_started/_index.en.md
  content/kubeone/master/getting_started/install.en.md
  content/kubeone/master/quickstarts/_index.en.md
  content/kubeone/master/quickstarts/aws.en.md
  content/kubeone/master/quickstarts/azure.en.md
  content/kubeone/master/quickstarts/digitalocean.en.md
  content/kubeone/master/quickstarts/gce.en.md
  content/kubeone/master/quickstarts/hetzner.en.md
  content/kubeone/master/quickstarts/openstack.en.md
  content/kubeone/master/quickstarts/packet.en.md
  content/kubeone/master/quickstarts/vsphere.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#390 kubeone: add the compatibility information
  content/kubeone/master/getting_started/compatibility.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#391 kubeone: configuring SSH added to getting started
  content/kubeone/master/getting_started/ssh.en.md
  content/kubeone/master/using_kubeone/ssh.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#393 kubeone: create new sections
  content/kubeone/master/_index.en.md
  content/kubeone/master/compatibility_info/_index.en.md
  content/kubeone/master/getting_kubeone/_index.en.md
  content/kubeone/master/getting_started/_index.en.md
  content/kubeone/master/prerequisites/_index.en.md
  content/kubeone/master/prerequisites/ssh.en.md
  content/kubeone/master/quickstarts/_index.en.md
  content/kubeone/master/using_kubeone/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#394 kubeone: use the vanity domain
  content/kubeone/master/getting_kubeone/_index.en.md
  content/kubeone/v1.0/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#395 kubeone: add the Concepts document
  content/kubeone/master/concepts/_index.en.md
  content/kubeone/master/prerequisites/_index.en.md
  content/kubeone/master/quickstarts/_index.en.md
  content/kubeone/master/using_kubeone/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L
