Repository kubermatic/docs, pull requests merged in 2020-02, with the labels that each got.

#232 fix OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#221 extend doc for dynamic presets
  content/kubermatic/master/advanced/presets/_index.en.md
Labels: approved, lgtm, size/L

#235 changelog for v2.13.0
  content/kubermatic/master/changelog/2.13/_index.en.md
  content/kubermatic/v2.13/changelog/2.13/_index.en.md
Labels: approved, lgtm, size/L

#236 change changelog pages weights to properly order them from oldest to newest
  content/kubermatic/master/changelog/2.10/_index.en.md
  content/kubermatic/master/changelog/2.11/_index.en.md
  content/kubermatic/master/changelog/2.12/_index.en.md
  content/kubermatic/master/changelog/2.13/_index.en.md
  content/kubermatic/v2.12/changelog/2.10/_index.en.md
  content/kubermatic/v2.12/changelog/2.11/_index.en.md
  content/kubermatic/v2.12/changelog/2.12/_index.en.md
  content/kubermatic/v2.13/changelog/2.10/_index.en.md
  content/kubermatic/v2.13/changelog/2.11/_index.en.md
  content/kubermatic/v2.13/changelog/2.12/_index.en.md
  content/kubermatic/v2.13/changelog/2.13/_index.en.md
Labels: approved, lgtm, size/S

#237 Deprecate Elastic Stack
  content/kubermatic/master/changelog/2.13/_index.en.md
  content/kubermatic/master/upgrading/2.12_to_2.13/_index.en.md
  content/kubermatic/master/upgrading/2.13_to_2.14/_index.en.md
  content/kubermatic/v2.13/changelog/2.13/_index.en.md
  content/kubermatic/v2.13/upgrading/2.12_to_2.13/_index.en.md
Labels: approved, lgtm, size/L

#241 Added a tutorial on deploying an application
  content/kubermatic/master/tutorials/11-deploy-application/_index.en.md
  content/kubermatic/v2.13/tutorials/11-deploy-application/_index.en.md
Labels: approved, lgtm, size/L

#240 Add Google Compute API enabling
  content/kubermatic/master/requirements/cloud_provider/_gcp.en.md
  content/kubermatic/v2.12/requirements/cloud_provider/_gcp.en.md
  content/kubermatic/v2.13/requirements/cloud_provider/_gcp.en.md
Labels: approved, lgtm, size/S

#242 Fix bad page title
  content/kubermatic/master/_index.en.md
  layouts/partials/header.html
  layouts/partials/title.html
Labels: approved, lgtm, size/S

#239 Rework install docs
  content/kubermatic/master/advanced/offline_mode/_index.en.md
  content/kubermatic/master/advanced/oidc_config/_index.en.md
  content/kubermatic/master/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/master/advanced/update_updates/_index.en.md
  content/kubermatic/master/advanced/update_versions/_index.en.md
  content/kubermatic/master/advanced/versions_updates/_index.en.md
  content/kubermatic/master/concepts/kubermaticconfiguration/_index.en.md
  content/kubermatic/master/installation/add_seed_cluser/_index.en.md
  content/kubermatic/master/installation/add_seed_cluster/_index.en.md
  content/kubermatic/master/installation/install_kubermatic/_index.en.md
  content/kubermatic/master/installation/install_kubermatic/_installer.en.md
  content/kubermatic/master/installation/install_kubermatic/_manual.en.md
  content/kubermatic/master/installation/logging_stack/_index.en.md
  content/kubermatic/master/installation/monitoring_stack/_index.en.md
  content/kubermatic/master/installation/securing_services/_index.en.md
  content/kubermatic/v2.12/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/v2.12/installation/add_seed_cluser/_index.en.md
Labels: approved, lgtm, size/XXL
