Repository kubermatic/docs, pull requests merged in 2020-01, with the labels that each got.

#218 Adding tutorial on SSH access to worker nodes
  content/kubermatic/master/tutorials/09-ssh-access-to-worker-node/_index.en.md
  content/kubermatic/v2.12/tutorials/09-ssh-access-to-worker-node/_index.en.md
Labels: approved, lgtm, size/M

#214 tutorials/kubeconfig: add to the master version as well
  content/kubermatic/master/tutorials/06-download-kubeconfig/06-download-kubeconfig-button.png
  content/kubermatic/master/tutorials/06-download-kubeconfig/06-download-kubeconfig-more.png
  content/kubermatic/master/tutorials/06-download-kubeconfig/06-download-kubeconfig-revoke.png
  content/kubermatic/master/tutorials/06-download-kubeconfig/_index.en.md
Labels: approved, lgtm, size/S

#222 Add tutorial 10
  content/kubermatic/master/tutorials/08-manage-node-deployments/08-manage-node-deployments-edit-dialog.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/08-manage-node-deployments-edit.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/08-manage-node-deployments-overview.png
  content/kubermatic/master/tutorials/08-manage-node-deployments/_index.en.md
  content/kubermatic/master/tutorials/09-ssh-access-to-worker-node/_index.en.md
  content/kubermatic/master/tutorials/10-manage-worker-nodes-via-cli/_index.en.md
  content/kubermatic/v2.12/tutorials/08-manage-node-deployments/08-manage-node-deployments-edit-dialog.png
  content/kubermatic/v2.12/tutorials/08-manage-node-deployments/08-manage-node-deployments-edit.png
  content/kubermatic/v2.12/tutorials/08-manage-node-deployments/08-manage-node-deployments-overview.png
  content/kubermatic/v2.12/tutorials/08-manage-node-deployments/_index.en.md
  content/kubermatic/v2.12/tutorials/09-ssh-access-to-worker-node/_index.en.md
  content/kubermatic/v2.12/tutorials/10-manage-worker-nodes-via-cli/_index.en.md
Labels: approved, lgtm, size/M

#223 changelog for v2.12.5
  content/kubermatic/master/changelog/2.12/_index.en.md
  content/kubermatic/v2.12/changelog/2.12/_index.en.md
Labels: approved, lgtm, size/S

#215 Add accessible addons docs
  content/kubermatic/master/advanced/addons/_index.en.md
  static/img/advanced/addons/form.png
  static/img/advanced/addons/view.png
Labels: approved, lgtm, size/M

#225 Fixed typo
  content/kubermatic/master/operation/etcd/restoring-from-backup/_index.en.md
  content/kubermatic/v2.12/operation/etcd/restoring-from-backup/_index.en.md
Labels: approved, lgtm, size/XS

#227 Replace initech with example name
  content/kubermatic/master/monitoring/customization/_index.en.md
  content/kubermatic/v2.12/monitoring/customization/_index.en.md
Labels: approved, lgtm, size/M

#226 Fix broken links
  content/kubermatic/master/advanced/oidc_auth/_index.en.md
  content/kubermatic/master/advanced/oidc_config/_index.en.md
  content/kubermatic/master/advanced/update_versions/_index.en.md
  content/kubermatic/master/installation/add_seed_cluser/_index.en.md
  content/kubermatic/master/installation/install_kubermatic/_manual.en.md
  content/kubermatic/master/installation/install_kubernetes/_index.en.md
  content/kubermatic/master/monitoring/customization/_index.en.md
  content/kubermatic/master/requirements/cluster_requirements/_index.en.md
  content/kubermatic/v2.12/advanced/custom_links/_index.en.md
  content/kubermatic/v2.12/advanced/oidc_auth/_index.en.md
  content/kubermatic/v2.12/advanced/oidc_config/_index.en.md
  content/kubermatic/v2.12/advanced/update_versions/_index.en.md
  content/kubermatic/v2.12/installation/add_seed_cluser/_index.en.md
  content/kubermatic/v2.12/installation/install_kubermatic/_manual.en.md
  content/kubermatic/v2.12/installation/install_kubernetes/_index.en.md
  content/kubermatic/v2.12/monitoring/customization/_index.en.md
  content/kubermatic/v2.12/requirements/cluster_requirements/_index.en.md
Labels: approved, lgtm, size/M

#228 Update Owner structure
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/M
