Repository kubermatic/docs, pull requests merged in 2021-03, with the labels that each got.

#586 Document azure machines cleanups
  content/kubermatic/master/architecture/requirements/cloud_provider/azure.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#587 Fix typo
  content/kubermatic/v2.15/upgrading/2.14_to_2.15/chart_migration/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#588 document hetzner improvements in KKP 2.16.3
  content/kubermatic/v2.16/upgrading/2.15_to_2.16/_index.en.md
Labels: approved, dco-signoff: yes, do-not-merge/hold, lgtm, size/M

#589 fix typo
  content/kubermatic/v2.12/concepts/expose-strategy/expose_strategy.en.md
  content/kubermatic/v2.13/concepts/expose-strategy/expose_strategy.en.md
  content/kubermatic/v2.14/concepts/expose-strategy/expose_strategy.en.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#544 remove unused files
  data/kubermatic/master/kubermaticConfiguration.yaml
  data/kubermatic/master/seed.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#593 Update the KubeOne v1.2 docs
  content/kubeone/v1.2/architecture/_index.en.md
  content/kubeone/v1.2/architecture/architecture.png
  content/kubeone/v1.2/compatibility_info/_index.en.md
  content/kubeone/v1.2/infrastructure/terraform_integration.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#524 Document 2.17 CA handling in KKP
  content/kubermatic/master/guides/custom_ca/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#598 Fix the documentation about the increase of the service CIDR for userclusters
  content/kubermatic/v2.12/operation/control-plane/increase-service-pod-cidr/_index.en.md
  content/kubermatic/v2.13/operation/control-plane/increase-service-pod-cidr/_index.en.md
  content/kubermatic/v2.14/operation/control-plane/increase-service-pod-cidr/_index.en.md
  content/kubermatic/v2.15/operation/control-plane/increase-service-pod-cidr/_index.en.md
  content/kubermatic/v2.16/operation/control-plane/increase-service-pod-cidr/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, sig/networking, size/L
