Repository kubermatic/docs, pull requests merged in 2021-11, with the labels that each got.

#840 Fix links to requirements and upgrade notes in CE installation
  content/kubermatic/master/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.18/guides/installation/install_kkp_CE/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#843 Remove traces of kubermatic-operator-util from docs of versions after removal
  content/kubermatic/master/guides/addons/_index.en.md
  content/kubermatic/v2.16/advanced/addons/_index.en.md
  content/kubermatic/v2.16/advanced/versions_updates/_index.en.md
  content/kubermatic/v2.17/guides/addons/_index.en.md
  content/kubermatic/v2.18/guides/addons/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#841 Add documentation about cluster defaulting
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/cluster_defaulting/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#846 Improvisation changes for Azure Service Account documentation
  content/kubeone/master/architecture/requirements/machine_controller/azure/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/azure/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
  content/kubermatic/master/architecture/requirements/support_policy/provider_support_matrix/azure/azure.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/azure/azure.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#847 mlavacca added to team-lifecycle
  OWNERS_ALIASES
Labels: lgtm, size/XS, approved, dco-signoff: yes

#845 Re-add and update audit logging documentation
  content/kubermatic/master/data/policy.yaml
  content/kubermatic/master/guides/audit_logging/01-create-cluster.png
  content/kubermatic/master/guides/audit_logging/01-edit-cluster.png
  content/kubermatic/master/guides/audit_logging/_index.en.md
  content/kubermatic/v2.18/data/policy.yaml
  content/kubermatic/v2.18/guides/audit_logging/01-create-cluster.png
  content/kubermatic/v2.18/guides/audit_logging/01-edit-cluster.png
  content/kubermatic/v2.18/guides/audit_logging/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#848 Update _index.en.md: fix example URL
  content/kubeone/v1.3/tutorials/creating_clusters_oidc/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#849 Update _index.en.md: fix example URL
  content/kubeone/master/tutorials/creating_clusters_oidc/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#815 Document Azure Availability Sets and Load Balancers in KubeOne
  content/kubeone/master/cheat_sheets/production_recommendations/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.3/cheat_sheets/production_recommendations/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#852 Output separated from command code block under KKP documentation
  content/kubermatic/master/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/master/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/master/guides/installation/offline_mode/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.18/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.18/guides/installation/offline_mode/_index.en.md
  content/kubermatic/v2.18/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#851 Update documentation for MLA upgrade process
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#855 Update screenshot for Kubermatic UI to include audit policy preset
  content/kubermatic/master/guides/audit_logging/01-create-cluster.png
  content/kubermatic/master/guides/audit_logging/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#858 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, size/XS, approved, dco-signoff: yes

#853 Add documentation for setting up Grafana for HA
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#859 Add admissionPlugins documentation for custom admission plugins
  .gitignore
  content/kubermatic/master/guides/admission_plugins/_index.en.md
Labels: sig/cluster-management, lgtm, kind/documentation, approved, size/S, dco-signoff: yes

#854 Remove helm2 references
  content/kubermatic/master/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/master/guides/kkp_security/securing_system_services/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/master_seed/installation/_index.en.md
  content/kubermatic/master/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/master/tutorials_howtos/upgrading/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.18/guides/kkp_security/securing_system_services/_index.en.md
  content/kubermatic/v2.18/guides/monitoring_logging_alerting/master_seed/installation/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/upgrading/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#862 Document setting up MLA with existing minio or s3 services
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#824 Update docs for initial admin and admin settings
  content/kubermatic/master/tutorials_howtos/administration/kkp_user/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#860 Add info about disabling apiserver network policies
  content/kubermatic/master/guides/kkp_networking/apiserver_policies/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#865 Remove jiachengxu from OWNERS
  OWNERS_ALIASES
Labels: lgtm, size/XS, approved, dco-signoff: yes
