Repository kubermatic/docs, pull requests merged in 2021-07, with the labels that each got.

#728 document user ssh key agent migration
  content/kubermatic/v2.17/tutorials_howtos/administration/user_settings/user_ssh_key_agent/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#731 Fix odd typo
  content/kubeone/master/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/v1.0/infrastructure/requirements.en.md
  content/kubeone/v1.2/infrastructure/requirements.en.md
  content/kubeone/v1.3/architecture/requirements/infrastructure_management/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#730 set proper version of data files and update location of default versions
  content/kubermatic/master/data/policy.yaml
  content/kubermatic/master/guides/addons/_index.en.md
  content/kubermatic/master/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
  content/kubermatic/v2.16/concepts/kubermaticconfiguration/_index.en.md
  content/kubermatic/v2.16/data/kubermaticConfiguration.yaml
  content/kubermatic/v2.16/data/seed.yaml
  content/kubermatic/v2.16/tutorials/12-audit-logs/_index.en.md
  content/kubermatic/v2.17/data/addondata.go
  content/kubermatic/v2.17/data/seed.yaml
  content/kubermatic/v2.17/guides/addons/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/KKP_configuration/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/project_and_cluster_management/seed_cluster/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#735 Rollout md fix typo
  content/kubeone/master/cheat_sheets/rollout_machinedeployment/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#736 CCM migration section for KKP
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/_index.en.md
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/ccm_migration_cluster_view.png
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/ccm_migration_confirm.png
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/ccm_migration_confirm_rollout.png
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/ccm_migration_in_progress.png
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/ccm_migration_machine_deployment.png
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/ccm_migration_not_needed.png
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/ccm_migration_supported.png
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/ccm_migration_unsupported.png
  content/kubermatic/master/tutorials_howtos/CCM_migration/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L
