Repository kubermatic/docs, pull requests merged in 2021-02, with the labels that each got.

#467 Adding further description for installation and deployment to Azure
  content/kubeone/master/infrastructure/production_recommendations.en.md
  content/kubeone/master/provisioning/_index.en.md
  content/kubeone/v1.0/infrastructure/production_recommendations.en.md
  content/kubeone/v1.0/provisioning/_index.en.md
  content/kubermatic/master/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/master/requirements/cloud_provider/azure.en.md
  content/kubermatic/v2.15/advanced/proxy_whitelisting/_index.en.md
  content/kubermatic/v2.15/requirements/cloud_provider/azure.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#509 begin 2.16 migration notes
  content/kubermatic/master/upgrading/2.15_to_2.16/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#508 add kubevirt installation doc
  content/kubermatic/master/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/v2.12/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/v2.13/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/v2.14/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/v2.15/requirements/cloud_provider/kubevirt.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#511 add documentation about admission plugins
  content/kubermatic/master/advanced/admission_plugins_configuration/_index.en.md
  static/img/kubermatic/master/advanced/admission_plugins_configuration/configuration.png
  static/img/kubermatic/master/advanced/admission_plugins_configuration/select.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#515 fix referance to v2.16
  content/kubermatic/v2.16/advanced/addons/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#518 Re-structure KubeCarrier documentation
  content/kubecarrier/master/_index.md
  content/kubecarrier/master/architecture/_index.md
  content/kubecarrier/master/architecture/related_projects.md
  content/kubecarrier/master/architecture/system_architecture.md
  content/kubecarrier/master/architecture/use_cases.md
  content/kubecarrier/master/cheat_sheets/_index.md
  content/kubecarrier/master/cheat_sheets/debugging.md
  content/kubecarrier/master/examples/_index.md
  content/kubecarrier/master/getting_started/_index.md
  content/kubecarrier/master/guides/_index.md
  content/kubecarrier/master/guides/api_access.md
  content/kubecarrier/master/references/_index.md
  content/kubecarrier/master/references/api-reference.md
  content/kubecarrier/master/references/glossary.md
  content/kubecarrier/master/references/repository-organization.md
  content/kubecarrier/master/tutorials_howtos/_index.md
  content/kubecarrier/master/tutorials_howtos/api_usage/_index.md
  content/kubecarrier/master/tutorials_howtos/api_usage/accounts.md
  content/kubecarrier/master/tutorials_howtos/api_usage/catalogs.md
  content/kubecarrier/master/tutorials_howtos/api_usage/clusters.md
  content/kubecarrier/master/tutorials_howtos/api_usage/crds.md
  content/kubecarrier/master/tutorials_howtos/installation.md
  content/kubecarrier/master/tutorials_howtos/requirements.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#520 add concept
  content/kubermatic/master/architecture  /concepts/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#521 kubeone: Guides
  content/kubeone/master/guides/addons/_index.en.md
  content/kubeone/master/guides/api_migration/_index.en.md
  content/kubeone/master/guides/credentials/_index.md
  content/kubeone/master/guides/getting_kubeone/_index.en.md
  content/kubeone/master/guides/machine_controller/_index.en.md
  content/kubeone/master/guides/manual_cluster_recovery/_index.en.md
  content/kubeone/master/guides/manual_cluster_repair/_index.en.md
  content/kubeone/master/guides/proxy/_index.en.md
  content/kubeone/master/guides/ssh/_index.en.md
  content/kubeone/master/guides/static_workers/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#519 Initial KubeOne Architecture docs
  content/kubeone/master/architecture/_index.en.md
  content/kubeone/master/architecture/cluster_reconciliation/_index.en.md
  content/kubeone/master/architecture/compatibility/_index.en.md
  content/kubeone/master/architecture/concepts/_index.en.md
  content/kubeone/master/architecture/infrastructure_management/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#522 Fix typo in the Compatibility document
  content/kubeone/master/architecture/compatibility/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#523 KubeOne: Create Tutorials & How-tos section
  content/kubeone/master/tutorials/changing_cluster_properties/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_eks_d/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_oidc/_index.en.md
  content/kubeone/master/tutorials/unprovisioning_clusters/_index.en.md
  content/kubeone/master/tutorials/upgrading_clusters/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#525 KubeOne: Add stubs for all sections
  content/kubeone/master/cheat_sheets/production_recommendations/_index.en.md
  content/kubeone/master/cheat_sheets/troubleshooting/_index.en.md
  content/kubeone/master/examples/addons_backup/_index.en.md
  content/kubeone/master/examples/addons_calico_vxlan/_index.en.md
  content/kubeone/master/examples/ha_load_balancing/_index.en.md
  content/kubeone/master/references/kubeone_cluster_v1beta1/_index.en.md
  content/kubeone/master/references/terraform_integration/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#526 add installation guide
  content/kubermatic/master/architecture  /_index.en.md
  content/kubermatic/master/guides/installation/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_ee/_index.en.md
  content/kubermatic/master/guides/installation/install_kubermatic/_index.en.md
  content/kubermatic/master/guides/installation/install_kubernetes/_index.en.md
  content/kubermatic/master/guides/installation/logging_stack/_index.en.md
  content/kubermatic/master/guides/installation/monitoring_stack/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#528 fix architecture
  content/kubermatic/master/architecture  /_index.en.md
  content/kubermatic/master/architecture  /concepts/_index.en.md
  content/kubermatic/master/architecture  /concepts/datacenters/_index.en.md
  content/kubermatic/master/architecture  /concepts/presets/_index.en.md
  content/kubermatic/master/architecture  /requirements/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#530 fix aritecture layout
  content/kubermatic/master/architecture  /_index.en.md
  content/kubermatic/master/architecture  /concepts/_index.en.md
  content/kubermatic/master/architecture  /requirements/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#527 Offline mode guide
  content/kubermatic/master/architecture/_index.en.md
  content/kubermatic/master/architecture/concepts/_index.en.md
  content/kubermatic/master/architecture/concepts/configuration/_index.en.md
  content/kubermatic/master/architecture/concepts/datacenters/_index.en.md
  content/kubermatic/master/architecture/concepts/presets/_index.en.md
  content/kubermatic/master/architecture/concepts/seeds/_index.en.md
  content/kubermatic/master/architecture/requirements/_index.en.md
  content/kubermatic/master/architecture/requirements/cloud_provider/_index.en.md
  content/kubermatic/master/architecture/requirements/cloud_provider/aws.en.md
  content/kubermatic/master/architecture/requirements/cloud_provider/azure.en.md
  content/kubermatic/master/architecture/requirements/cloud_provider/gcp.en.md
  content/kubermatic/master/architecture/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/master/architecture/requirements/cloud_provider/vsphere.en.md
  content/kubermatic/master/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/master/cheat_sheets/_index.en.md
  content/kubermatic/master/guides/offline_mode/_index.en.md
  content/kubermatic/master/references/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#531 document user ssh key agent
  content/kubermatic/master/references/user_ssh_key_agent/_index.en.md
  static/img/kubermatic/master/advanced/user-ssh-key-agent/enable-agent.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#534 refreshed and restructured create project and cluster management
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01-create-project-creating.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01-create-project-name.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01-create-project-overview.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01-delete-project.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01a-add-ssh-key-dialog.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01a-add-ssh-key-overview.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01b-create-cluster-api-tokens.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01b-create-cluster-choose-name.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01b-create-cluster-choose-provider.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01b-create-cluster-creation.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01b-create-cluster-credentials.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01b-create-cluster-initial-nodes.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01b-create-cluster-start.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01b-create-cluster-status.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01b-create-cluster-summary.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01c-upgrade-cluster-arrow.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01c-upgrade-cluster-select-version.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01d-delete-cluster-confirm.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01d-delete-cluster-delete-button.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/01e-edit-cluster.png
  content/kubermatic/master/tutorials/01-manage-project-and-cluster/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#533 KubeOne: Add the Infrastructure Management document
  content/kubeone/master/architecture/infrastructure_management/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#537 add CRD api usage diagram
  content/kubecarrier/master/img/CRDs.png
  content/kubecarrier/master/tutorials_howtos/api_usage/crds.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#517 Add documentation skeleton for expose strategy concept
  content/kubermatic/master/architecture/_index.en.md
  content/kubermatic/master/architecture/concepts/expose_strategy/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#536 Minor KubeCarrier reorganizations, Concepts page
  content/kubecarrier/master/_index.md
  content/kubecarrier/master/architecture/concepts.md
  content/kubecarrier/master/architecture/related_projects.md
  content/kubecarrier/master/references/repository-organization.md
  content/kubecarrier/master/tutorials_howtos/api_usage/service_clusters.md
  content/kubecarrier/master/tutorials_howtos/installation/_index.md
  content/kubecarrier/master/tutorials_howtos/installation/kkp_addon.md
  content/kubecarrier/master/tutorials_howtos/installation/kubectl.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#538 kubeone: fix broken refs
  content/kubeone/master/architecture/cluster_reconciliation/_index.en.md
  content/kubeone/master/architecture/concepts/_index.en.md
  content/kubeone/master/architecture/infrastructure_management/_index.en.md
  content/kubeone/master/guides/credentials/_index.md
  content/kubeone/master/guides/machine_controller/_index.en.md
  content/kubeone/master/guides/manual_cluster_recovery/_index.en.md
  content/kubeone/master/guides/static_workers/_index.en.md
  content/kubeone/master/references/kubeone_cluster_v1beta1/_index.en.md
  content/kubeone/master/references/terraform_integration/_index.en.md
  content/kubeone/master/tutorials/upgrading_clusters/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#498 add a notice for advanced settings
  content/kubermatic/master/architecture/concepts/presets/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#543 KubeOne: Add Amazon Linux 2 as a supported OS
  content/kubeone/master/architecture/compatibility/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#546 kubeone: update terraform reference
  content/kubeone/master/references/terraform_integration/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#550 move K1 architecture.png to page resource
  content/kubeone/master/architecture/_index.en.md
  content/kubeone/master/architecture/architecture.png
Labels: approved, dco-signoff: yes, lgtm, size/XS

#551 Port oidc-authentication-audit-logging blog post into tutorial
  content/kubeone/master/tutorials/oidc-authentication-audit-logging/_index.en.md
  content/kubeone/master/tutorials/oidc-authentication-audit-logging/dex-oidc-login.jpg
Labels: approved, dco-signoff: yes, lgtm, size/XL

#549 KubeOne: Rework the Cluster Reconciliation document
  content/kubeone/master/architecture/cluster_reconciliation/_index.en.md
  content/kubeone/master/architecture/cluster_reconciliation/cluster_reconciliation.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#553 KubeOne: fix broken ref
  content/kubeone/master/guides/credentials/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#552 KubeOne: Move OIDC tutorial to the placeholder doc
  content/kubeone/master/tutorials/creating_clusters_oidc/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_oidc/dex-oidc-login.jpg
  content/kubeone/master/tutorials/oidc-authentication-audit-logging/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#554 Add KubeCarrier Concepts and Use Cases docs
  content/kubecarrier/master/_index.md
  content/kubecarrier/master/architecture/components.md
  content/kubecarrier/master/architecture/concepts.md
  content/kubecarrier/master/architecture/use_cases.md
  content/kubecarrier/master/img/kubecarrier_concepts.png
  content/kubecarrier/master/img/kubecarrier_example_redis.png
  content/kubecarrier/master/img/kubecarrier_service_hub.png
  content/kubecarrier/master/references/glossary.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#542 add logging monitoring alerting
  content/kubermatic/master/architecture/logging_monitoring_alerting/_index.en.md
  content/kubermatic/master/architecture/requirements/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#540 Add cookie banner
  layouts/index.html
  layouts/partials/header.html
  themes/hugo-theme-learn/layouts/404.html
  themes/hugo-theme-learn/layouts/partials/cookie-banner.html
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#547 Add expose strategy configuration guide
  content/kubermatic/master/guides/installation/add_seed_cluster/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_ee/_index.en.md
  content/kubermatic/master/guides/installation/expose_strategy/_index.en.md
  content/kubermatic/master/guides/installation/install_kubermatic/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#559 add 2.16 to compat matrix
  content/kubermatic/v2.16/installation/compatibility/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#545 refresh support matrix
  content/kubermatic/master/architecture/requirements/supported_versions/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#548 move global settings to the new structure
  content/kubermatic/master/architecture/concepts/global_settings/_index.en.md
  static/img/kubermatic/master/advanced/settings/view.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#561 kubeone: mark as draft TBD pages
  content/kubeone/master/cheat_sheets/troubleshooting/_index.en.md
  content/kubeone/master/tutorials/changing_cluster_properties/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_eks_d/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#562 KubeOne: Add the Using Terraform Configs doc
  content/kubeone/master/guides/using_terraform_configs/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#582 kubermatic: swagger api
  Makefile
  content/kubermatic/master/references/rest-api/index.html
  content/kubermatic/master/references/rest-api/swagger-ui-bundle.js
  content/kubermatic/master/references/rest-api/swagger-ui-standalone-preset.js
  content/kubermatic/master/references/rest-api/swagger-ui.css
  content/kubermatic/master/references/rest-api/swagger.json
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#560 add redis operator example
  content/kubecarrier/master/examples/_index.md
  content/kubecarrier/master/examples/redis_operator.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#581 Add KubeCarrier Operator Concepts, minor re-structuring
  content/kubecarrier/master/architecture/components.md
  content/kubecarrier/master/cheat_sheets/debugging.md
  content/kubecarrier/master/guides/api_access.md
  content/kubecarrier/master/guides/operator-compatibility.md
  content/kubecarrier/master/img/operator_concepts.png
  content/kubecarrier/master/references/glossary.md
  content/kubecarrier/master/references/kubernetes-operators.md
  content/kubecarrier/master/references/repository-organization.md
  content/kubecarrier/master/tutorials_howtos/api_usage/accounts.md
  content/kubecarrier/master/tutorials_howtos/api_usage/catalogs.md
  content/kubecarrier/master/tutorials_howtos/api_usage/crds.md
  content/kubecarrier/master/tutorials_howtos/api_usage/service_clusters.md
  content/kubecarrier/master/tutorials_howtos/installation/kkp_addon.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#564 KubeOne: Add the Creating Kubernetes Clusters document
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/architecture.png
Labels: approved, dco-signoff: yes, lgtm, size/XL

#563 move user settings to architecture concept
  content/kubermatic/master/architecture/concepts/user_settings/_index.en.md
  static/img/kubermatic/master/architecture/concepts/user-settings/menu.png
  static/img/kubermatic/master/architecture/concepts/user-settings/view.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#584 [KubeCarrier] Add prerequisites to example and rephrase the redis example
  content/kubecarrier/master/examples/redis_operator.md
  content/kubecarrier/master/tutorials_howtos/api_usage/catalogs.md
Labels: approved, dco-signoff: yes, lgtm, size/L
