Repository kubermatic/docs, pull requests merged in 2021-06, with the labels that each got.

#708 Document that Kubermatic CRDs should be installed on seed clusters
  content/kubermatic/master/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.16/installation/add_seed_cluster/_index.en.md
  content/kubermatic/v2.16/installation/add_seed_cluster_ee/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_EE/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#709 Adding KKP Master and v2.17 Architecture Content
  content/kubermatic/master/architecture/_index.en.md
  content/kubermatic/v2.17/architecture/_index.en.md
  static/img/kubermatic/master/architecture/combined-master-seed.png
  static/img/kubermatic/master/architecture/dedicated-seeds.png
  static/img/kubermatic/v2.17/architecture/combined-master-seed.png
  static/img/kubermatic/v2.17/architecture/dedicated-seeds.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#710 How to cause a machinedeployment rolling restart
  content/kubeone/master/cheat_sheets/rollout_machinedeployment/_index.en.md
  content/kubeone/v1.3/cheat_sheets/rollout_machinedeployment/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#712 Kubeone containerd migration
  content/kubeone/master/guides/containerd_migration/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#713 cert-manager helm chart now requires an email to be set
  content/kubermatic/master/tutorials_howtos/upgrading/upgrade_from_2.17_to_2.18/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#717 Fix link to seed yaml files
  content/kubermatic/master/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_EE/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#714 Updating 404 error links and images in KKP Master and V2.17
  content/kubermatic/master/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/master/examples/manage_worker's_node/ssh-access-to-worker-node/_index.en.md
  content/kubermatic/master/examples/manage_worker's_node/via_command_line/_index.en.md
  content/kubermatic/master/guides/addons/kubeflow/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/master/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/master/tutorials_howtos/administration/user_settings/_index.en.md
  content/kubermatic/master/tutorials_howtos/administration/user_settings/user_ssh_key_agent/_index.en.md
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/using-kubectl/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/v2.17/examples/manage_worker's_node/ssh-access-to-worker-node/_index.en.md
  content/kubermatic/v2.17/examples/manage_worker's_node/via_command_line/_index.en.md
  content/kubermatic/v2.17/guides/addons/kubeflow/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/user_settings/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/user_settings/user_ssh_key_agent/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/project_and_cluster_management/using-kubectl/_index.en.md
  static/img/kubermatic/master/tutorials/cluster_details2_btn.png
  static/img/kubermatic/master/tutorials/cluster_details_btn.png
  static/img/kubermatic/master/tutorials/cluster_edit_menu.PNG
  static/img/kubermatic/v2.17/tutorials/cluster_details2_btn.png
  static/img/kubermatic/v2.17/tutorials/cluster_details_btn.png
  static/img/kubermatic/v2.17/tutorials/cluster_edit_menu.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#718 KubeOne: Updated the required Terraform version to v1.0.0
  content/kubeone/master/architecture/compatibility/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_eks_d/_index.en.md
  content/kubeone/v1.3/architecture/compatibility/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_eks_d/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#711 New landing pages on tutorials and guides
  content/kubermatic/master/guides/_index.en.md
  content/kubermatic/master/tutorials_howtos/_index.en.md
  content/kubermatic/v2.17/guides/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#719 Update KKP master and v2.17 doc paths with ref
  content/kubermatic/master/architecture/_index.en.md
  content/kubermatic/master/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/master/examples/Deploy_your_application/_index.en.md
  content/kubermatic/master/examples/manage_worker's_node/ssh-access-to-worker-node/_index.en.md
  content/kubermatic/master/examples/manage_worker's_node/via_command_line/_index.en.md
  content/kubermatic/master/guides/addons/kubeflow/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/master/guides/installation/install_HA_kubernetes/_index.en.md
  content/kubermatic/master/guides/service_account/using_service_account/_index.en.md
  content/kubermatic/master/tutorials_howtos/administration/user_settings/_index.en.md
  content/kubermatic/master/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/_index.en.md
  content/kubermatic/v2.17/architecture/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/v2.17/examples/Deploy_your_application/_index.en.md
  content/kubermatic/v2.17/examples/manage_worker's_node/ssh-access-to-worker-node/_index.en.md
  content/kubermatic/v2.17/examples/manage_worker's_node/via_command_line/_index.en.md
  content/kubermatic/v2.17/guides/addons/kubeflow/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.17/guides/installation/install_HA_kubernetes/_index.en.md
  content/kubermatic/v2.17/guides/service_account/using_service_account/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/user_settings/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#720 Fixing Kubecarrier doc broken link
  content/kubecarrier/master/guides/api_access.md
  content/kubecarrier/v0.3/guides/api_access.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#721 document aws spot instance creation
  content/kubermatic/master/guides/addons/aws_node_termination_handler/_index.en.md
  static/img/kubermatic/master/guides/addons/spot_instance_selection.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#724 Remove optional comment for cluster field in seed
  content/kubermatic/master/data/seed.yaml
  content/kubermatic/v2.17/data/seed.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#725 document user ssh key agent migration
  content/kubermatic/master/tutorials_howtos/administration/user_settings/user_ssh_key_agent/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
