Repository kubermatic/docs, pull requests merged in 2021-09, with the labels that each got.

#771 Formatting kkp versioning code block
  content/kubermatic/master/architecture/requirements/support_policy/KKP_components_versioning/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/support_policy/KKP_components_versioning/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#776 Updated Kubeone APIDoc
  content/kubeone/master/references/kubeone_cluster_v1beta1/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#766 Add info about kubeadm-configmap addon
  content/kubermatic/master/guides/addons/_index.en.md
  content/kubermatic/master/tutorials_howtos/upgrading/upgrade_from_2.17_to_2.18/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#778 Add a placeholder for the CCM/CSI migration doc to KubeOne docs
  content/kubeone/master/guides/ccm_csi_migration/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#781 Document new MLA features
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/user_guide/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#779 Kubeone addons API
  content/kubeone/master/guides/addons/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#783 Update MLA documentation with latest UI change
  content/kubermatic/master/tutorials_howtos/monitoring_logging_alerting/user_cluster/setting_up_alertmanager_with_slack_notifications/_index.en.md
  static/img/kubermatic/master/monitoring/user_cluster/create_logs_alert_rule.png
  static/img/kubermatic/master/monitoring/user_cluster/create_metrics_alert_rule.png
  static/img/kubermatic/master/monitoring/user_cluster/slack_alertmanager_config.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_addons.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_alert_rules_data.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#784 Update and publish the KubeOne v1.3 docs
  content/kubeone/v1.3/architecture/cluster_reconciliation/_index.en.md
  content/kubeone/v1.3/architecture/compatibility/_index.en.md
  content/kubeone/v1.3/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/v1.3/cheat_sheets/rollout_machinedeployment/_index.en.md
  content/kubeone/v1.3/guides/addons/_index.en.md
  content/kubeone/v1.3/guides/ccm_csi_migration/_index.en.md
  content/kubeone/v1.3/guides/containerd_migration/_index.en.md
  content/kubeone/v1.3/references/kubeone_cluster_v1beta1/_index.en.md
  content/kubeone/v1.3/tutorials/how_to_contribute_to_kubeone/_index.en.md
  data/products.yaml
Labels: lgtm, size/L, approved, dco-signoff: yes

#739 Add cluster template guide
  content/kubermatic/master/guides/cluster_templates/_index.en.md
  content/kubermatic/master/tutorials_howtos/cluster_templates/_index.en.md
  static/img/kubermatic/master/tutorials/cluster_template/actions.png
  static/img/kubermatic/master/tutorials/cluster_template/cluster_template_menu.png
  static/img/kubermatic/master/tutorials/cluster_template/create_cluster.png
  static/img/kubermatic/master/tutorials/cluster_template/create_from_cluster_wizard.png
  static/img/kubermatic/master/tutorials/cluster_template/create_from_clusters.png
  static/img/kubermatic/master/tutorials/cluster_template/delete_template.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#791 Update MLA architecture diagrams
  static/img/kubermatic/master/monitoring/architecture/architecture.png
  static/img/kubermatic/master/monitoring/user_cluster/architecture.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#789 Drop OS we can't support
  content/kubeone/master/architecture/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#786 Add missing KKP networking docs
  content/kubermatic/master/guides/kkp_networking/_index.en.md
  content/kubermatic/master/guides/kkp_networking/apiserver_policies/_index.en.md
  content/kubermatic/master/guides/kkp_networking/cluster_network/_index.en.md
  content/kubermatic/master/guides/kkp_networking/expose_strategies/_index.en.md
  static/img/kubermatic/master/guides/networking/networking_ui.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#732 Add instructions to create the first KKP admin after installation
  content/kubermatic/master/guides/installation/install_kkp_CE/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#792 Document the CCM/CSI migration process in KubeOne
  content/kubeone/master/guides/ccm_csi_migration/_index.en.md
  content/kubeone/master/guides/ccm_csi_migration/troubleshooting/_index.en.md
  content/kubeone/v1.3/guides/ccm_csi_migration/_index.en.md
  content/kubeone/v1.3/guides/ccm_csi_migration/troubleshooting/_index.en.md
Labels: size/XL, lgtm, approved, dco-signoff: yes

#795 Document upgrading from KubeOne 1.2 to 1.3
  content/kubeone/master/tutorials/upgrading/_index.en.md
  content/kubeone/master/tutorials/upgrading/upgrading_from_1.2_to_1.3/_index.en.md
  content/kubeone/v1.3/tutorials/upgrading/_index.en.md
  content/kubeone/v1.3/tutorials/upgrading/upgrading_from_1.2_to_1.3/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#796 Make sure all GitHub URLs point to the release/v1.3 branch
  content/kubeone/master/references/terraform_integration/_index.en.md
  content/kubeone/v1.3/architecture/compatibility/_index.en.md
  content/kubeone/v1.3/architecture/concepts/_index.en.md
  content/kubeone/v1.3/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/v1.3/examples/addons_backup/_index.en.md
  content/kubeone/v1.3/examples/addons_calico_vxlan/_index.en.md
  content/kubeone/v1.3/guides/addons/_index.en.md
  content/kubeone/v1.3/guides/using_terraform_configs/_index.en.md
  content/kubeone/v1.3/references/terraform_integration/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#794 Vsphere external CCM 1.22 incompatibility
  content/kubermatic/master/tutorials_howtos/CCM_migration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#793 Add guide for telemetry
  content/kubermatic/master/guides/telemetry/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#772 Add metering docs
  content/kubermatic/master/tutorials_howtos/metering/_index.en.md
  static/img/kubermatic/master/tutorials/metering_admin_panel_location.png
  static/img/kubermatic/master/tutorials/metering_configuration.png
  static/img/kubermatic/master/tutorials/metering_credentials.png
  static/img/kubermatic/master/tutorials/metering_overview.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#799 AllowedRegistry docs
  content/kubermatic/master/tutorials_howtos/OPA_integration/OPA_integration_Via_UI/_index.en.md
  content/kubermatic/master/tutorials_howtos/OPA_integration/_index.en.md
  static/img/kubermatic/master/ui/add_allowed_registry.png
  static/img/kubermatic/master/ui/allowed_registries.png
  static/img/kubermatic/master/ui/allowed_registry_default_constraint.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#798 Add image file for v2.17
  static/img/kubermatic/master/ui/admin_panel_access.png
  static/img/kubermatic/master/ui/opa_admin_ct.png
  static/img/kubermatic/master/ui/opa_constraints.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#800 Add cat to command in mla admin guide
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#802 Update support matrix
  content/kubermatic/master/architecture/requirements/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/master/architecture/requirements/support_policy/supported_versions/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#803 Add information about blackbox-exporter to docs
  content/kubermatic/master/guides/monitoring_logging_alerting/master_seed/installation/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#801 Fix minor typo in MLA configuration guide
  content/kubermatic/master/guides/monitoring_logging_alerting/master_seed/customization/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/operation/monitoring-logging-alerting-customization/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#805 Normalize featuregates flags
  content/kubermatic/master/cheat_sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/master/guides/kkp_networking/expose_strategies/_index.en.md
  content/kubermatic/master/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/v2.16/advanced/oidc_auth/_index.en.md
  content/kubermatic/v2.16/installation/expose_strategy/_index.en.md
  content/kubermatic/v2.16/operation/etcd/etcd-launcher/_index.en.md
  content/kubermatic/v2.17/cheat_sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/v2.17/guides/kkp_networking/expose_strategies/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#808 Backup tutorial
  content/kubermatic/master/tutorials_howtos/administration/admin_panel/_index.en.md
  content/kubermatic/master/tutorials_howtos/administration/admin_panel/backup_buckets/_index.en.md
  content/kubermatic/master/tutorials_howtos/etcd_backups/_index.en.md
  static/img/kubermatic/master/tutorials/backups/backup_buckets.png
  static/img/kubermatic/master/tutorials/backups/edit_buckets.png
  static/img/kubermatic/master/tutorials/backups/set_backup_credentials.png
  static/img/kubermatic/master/ui/add_etcd_backup.png
  static/img/kubermatic/master/ui/backup_snapshots.png
  static/img/kubermatic/master/ui/backups_list.png
  static/img/kubermatic/master/ui/cluster_restoring.png
  static/img/kubermatic/master/ui/etcd_backups.png
  static/img/kubermatic/master/ui/restore_backup.png
  static/img/kubermatic/master/ui/restore_cluster.png
  static/img/kubermatic/master/ui/restore_completed.png
  static/img/kubermatic/master/ui/restore_list.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#809 Fix kubeone 1.3 supported OSes doc
  content/kubeone/v1.3/architecture/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#807 add 2.17 support matrix to KKP 2.17 docs
  content/kubermatic/v2.17/architecture/requirements/support_policy/supported_versions/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#804 Update versioning and support matrices for 2.18
  content/kubermatic/master/architecture/requirements/support_policy/KKP_components_versioning/_index.en.md
  content/kubermatic/master/architecture/requirements/support_policy/provider_support_matrix/_index.en.md
  content/kubermatic/master/architecture/requirements/support_policy/supported_versions/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#797 Update KKP Architecture Image
  static/img/kubermatic/master/architecture/combined-master-seed.png
  static/img/kubermatic/master/architecture/dedicated-seeds.png
  static/img/kubermatic/master/architecture/kkp_components_versioning.png
  static/img/kubermatic/v2.16/concepts/architecture/dedicated-seeds.png
  static/img/kubermatic/v2.17/architecture/combined-master-seed.png
  static/img/kubermatic/v2.17/architecture/dedicated-seeds.png
  static/img/kubermatic/v2.17/architecture/kkp_components_versioning.png
  static/img/kubermatic/v2.18/architecture/combined-master-seed.png
  static/img/kubermatic/v2.18/architecture/dedicated-seeds.png
  static/img/kubermatic/v2.18/architecture/kkp_components_versioning.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#811 Update documentation with startio updates
  content/kubermatic/master/startio/_index.en.md
  content/kubermatic/master/startio/concepts/_index.en.md
  content/kubermatic/master/startio/concepts/pipeline_definition/_index.en.md
  content/kubermatic/master/startio/concepts/pipeline_definition/pipeline.png
  content/kubermatic/master/startio/flow.png
  content/kubermatic/master/startio/guides/explore_content/_index.en.md
  content/kubermatic/master/startio/guides/wizard/1.png
  content/kubermatic/master/startio/guides/wizard/2.png
  content/kubermatic/master/startio/guides/wizard/3.png
  content/kubermatic/master/startio/guides/wizard/4.png
  content/kubermatic/master/startio/guides/wizard/5.png
  content/kubermatic/master/startio/guides/wizard/6.png
  content/kubermatic/master/startio/guides/wizard/_index.en.md
  content/kubermatic/master/startio/guides/wizard/congrats.png
  content/kubermatic/master/startio/guides/wizard/welcome.png
  content/kubermatic/v2.18/startio/_index.en.md
  content/kubermatic/v2.18/startio/concepts/_index.en.md
  content/kubermatic/v2.18/startio/concepts/pipeline_definition/_index.en.md
  content/kubermatic/v2.18/startio/concepts/pipeline_definition/pipeline.png
  content/kubermatic/v2.18/startio/flow.png
  content/kubermatic/v2.18/startio/guides/explore_content/_index.en.md
  content/kubermatic/v2.18/startio/guides/wizard/1.png
  content/kubermatic/v2.18/startio/guides/wizard/2.png
  content/kubermatic/v2.18/startio/guides/wizard/3.png
  content/kubermatic/v2.18/startio/guides/wizard/4.png
  content/kubermatic/v2.18/startio/guides/wizard/5.png
  content/kubermatic/v2.18/startio/guides/wizard/6.png
  content/kubermatic/v2.18/startio/guides/wizard/_index.en.md
  content/kubermatic/v2.18/startio/guides/wizard/congrats.png
  content/kubermatic/v2.18/startio/guides/wizard/welcome.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#812 Point to proper tag in User Cluster MLA repo
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/v2.18/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes
