Repository kubermatic/docs, pull requests merged in 2021-05, with the labels that each got.

#678 Add_How_to_contribute _to_KubeCarrier
  content/kubecarrier/master/tutorials_howtos/how_to_contribute_to_kubecarrier/_index.en.md
  content/kubecarrier/v0.3/tutorials_howtos/how_to_contribute_to_kubecarrier/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#682 Add_How_to_Contribute_to_KubeOne
  content/kubeone/master/tutorials/how_to_contribute_to_kubeone/_index.en.md
  content/kubeone/v1.3/tutorials/how_to_contribute_to_kubeone/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#683 Update_How_to_Contribute_to_Kubeone
  content/kubeone/master/tutorials/how_to_contribute_to_kubeone/_index.en.md
  content/kubeone/v1.3/tutorials/how_to_contribute_to_kubeone/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#684 How_to_contribute_to_KKP
  content/kubermatic/master/tutorials_howtos/how_to_contribute_to_kkp/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/how_to_contribute_to_kkp/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#685 How_to_Contribute_to_kkp_v2.17
  content/kubermatic/v2.17/tutorials_howtos/how_to_contribute_to_kkp/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#687 Fixing contribution typos and header
  content/kubeone/master/tutorials/how_to_contribute_to_kubeone/_index.en.md
  content/kubeone/v1.3/tutorials/how_to_contribute_to_kubeone/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#688 Fixing kubecarrier contribution typos
  content/kubecarrier/master/tutorials_howtos/how_to_contribute_to_kubecarrier/_index.en.md
  content/kubecarrier/v0.3/tutorials_howtos/how_to_contribute_to_kubecarrier/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#690 kubeone: Update variable names for vsphere installation
  content/kubeone/master/guides/credentials/_index.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.2/prerequisites/credentials.en.md
  content/kubeone/v1.3/guides/credentials/_index.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#692 Remove empty file in KKP master and V2.17 documentation
  content/kubermatic/master/_index.en.md
  content/kubermatic/master/architecture/kkp_clusters/_index.en.md
  content/kubermatic/master/architecture/requirements/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/master/guides/kkp_networking/proxy_whitelisting/_index.en.md
  content/kubermatic/master/guides/kkp_security/pod_security_policy/_index.en.md
  content/kubermatic/master/tutorials_howtos/how_to_contribute_to_kkp/_index.en.md
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/seed_cluster/_index.en.md
  content/kubermatic/master/tutorials_howtos/upgrading/upgrade_from_2.14_to_2.15/chart_migration/_index.en.md
  content/kubermatic/v2.17/architecture/kkp_clusters/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/v2.17/guides/kkp_networking/proxy_whitelisting/_index.en.md
  content/kubermatic/v2.17/guides/kkp_security/pod_security_policy/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/how_to_contribute_to_kkp/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/project_and_cluster_management/seed_cluster/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.14_to_2.15/chart_migration/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/chart_migration/_index.en.md
  static/img/kubermatic/master/ui/dashboard.png
  static/img/kubermatic/v2.17/ui/dashboard.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#689 Added content on landing pages
  content/kubermatic/master/architecture/_index.en.md
  content/kubermatic/master/architecture/concept/_index.en.md
  content/kubermatic/master/architecture/requirements/support_policy/_index.en.md
  content/kubermatic/master/cheat_sheets/_index.en.md
  content/kubermatic/master/examples/_index.en.md
  content/kubermatic/master/guides/_index.en.md
  content/kubermatic/master/guides/kkp_networking/_index.en.md
  content/kubermatic/master/references/_index.en.md
  content/kubermatic/master/tutorials_howtos/_index.en.md
  content/kubermatic/v2.17/_index.en.md
  content/kubermatic/v2.17/architecture/_index.en.md
  content/kubermatic/v2.17/architecture/concept/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/support_policy/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/support_policy/provider_support_matrix/google_cloud/gcp.en.md
  content/kubermatic/v2.17/cheat_sheets/_index.en.md
  content/kubermatic/v2.17/cheat_sheets/changelog/_index.en.md
  content/kubermatic/v2.17/cheat_sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/v2.17/data/seed.yaml
  content/kubermatic/v2.17/examples/_index.en.md
  content/kubermatic/v2.17/examples/manage_worker's_node/via_UI/_index.en.md
  content/kubermatic/v2.17/guides/_index.en.md
  content/kubermatic/v2.17/guides/addons/_index.en.md
  content/kubermatic/v2.17/guides/addons/kubeflow/_index.en.md
  content/kubermatic/v2.17/guides/addons/multus/_index.en.md
  content/kubermatic/v2.17/guides/admission_plugins/_index.en.md
  content/kubermatic/v2.17/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.17/guides/kkp_networking/_index.en.md
  content/kubermatic/v2.17/guides/kkp_os_support/_index.en.md
  content/kubermatic/v2.17/guides/kkp_os_support/coreos_eos/_index.en.md
  content/kubermatic/v2.17/guides/kkp_security/pod_security_policy/_index.en.md
  content/kubermatic/v2.17/guides/service_account/using_service_account/_index.en.md
  content/kubermatic/v2.17/img/KubermaticKubernetesPlatform-logo.jpg
  content/kubermatic/v2.17/references/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/KKP_configuration/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/OPA_integration/OPA_integration_Via_UI/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/admin_panel/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/admin_panel/administrators/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/admin_panel/cluster_settings/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/admin_panel/custom_links/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/admin_panel/dynamic_datacenters_management/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/admin_panel/opa_constraint_templates/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/global_settings/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/presets/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/user_settings/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/user_settings/user_ssh_key_agent/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/dashboard_customization/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/operation/control_plane/upgrading_the_control_plane/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/project_and_cluster_management/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/project_and_cluster_management/using-kubectl/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/chart_migration/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/kubermatic_operator/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/user_interface/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/user_interface/theming/with_src/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/user_interface/theming/without_src/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#694 Add KubeOne bare-metal tutorial
  content/kubeone/master/architecture/compatibility/_index.en.md
  content/kubeone/master/architecture/infrastructure_management/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/v1.2/compatibility_info/_index.en.md
  content/kubeone/v1.3/architecture/compatibility/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_baremetal/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#697 Re-arrange menu items on KKP master and v2.17 doc
  content/kubermatic/master/tutorials_howtos/upgrading/upgrade_from_2.15_to_2.16/_index.en.md
  content/kubermatic/master/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.15_to_2.16/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#696 Removes upgrade doc for older versions
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.10_to_2.11/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.11_to_2.12/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.12_to_2.13/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.6_to_2.7/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.7_to_2.8/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.8_to_2.9/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.9_to_2.10/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#698 Restoring upgrade info for 2.16 to 2.17 (removed by mistake)
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/chart_migration/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/kubermatic_operator/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#699 extend SA documentation for project managers group
  content/kubermatic/master/guides/service_account/_index.en.md
  content/kubermatic/master/guides/service_account/using_service_account/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#695 Kubeone provider requirements
  content/kubeone/master/architecture/concepts/_index.en.md
  content/kubeone/master/architecture/requirements/_index.en.md
  content/kubeone/master/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/master/architecture/requirements/machine_controller/_index.en.md
  content/kubeone/master/architecture/requirements/machine_controller/aws/aws.en.md
  content/kubeone/master/architecture/requirements/machine_controller/azure/azure.en.md
  content/kubeone/master/architecture/requirements/machine_controller/google_cloud/gcp.en.md
  content/kubeone/master/architecture/requirements/machine_controller/vSphere/vSphere.en.md
  content/kubeone/master/guides/machine_controller/_index.en.md
  content/kubeone/master/guides/using_terraform_configs/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_eks_d/_index.en.md
  content/kubeone/master/tutorials/upgrading_clusters/_index.en.md
  content/kubeone/v1.3/architecture/concepts/_index.en.md
  content/kubeone/v1.3/architecture/requirements/_index.en.md
  content/kubeone/v1.3/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/_index.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/aws/aws.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/azure/azure.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/google_cloud/gcp.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/vSphere/vSphere.en.md
  content/kubeone/v1.3/guides/machine_controller/_index.en.md
  content/kubeone/v1.3/guides/using_terraform_configs/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_eks_d/_index.en.md
  content/kubeone/v1.3/tutorials/upgrading_clusters/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#701 update service account documentation
  content/kubermatic/master/guides/service_account/using_service_account/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#702 Fixing dead links in master and v2.17 example sections
  content/kubermatic/master/examples/Deploy_your_application/_index.en.md
  content/kubermatic/master/examples/manage_worker's_node/via_UI/_index.en.md
  content/kubermatic/master/examples/manage_worker's_node/via_command_line/_index.en.md
  content/kubermatic/v2.17/examples/Deploy_your_application/_index.en.md
  content/kubermatic/v2.17/examples/manage_worker's_node/via_UI/_index.en.md
  content/kubermatic/v2.17/examples/manage_worker's_node/via_command_line/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#704 fix auth-url in kubeone openstack
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.0/provisioning/_index.en.md
  content/kubeone/v1.2/provisioning/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#703 Remove dns & nodelocal-dns-cache from addons docs
  content/kubermatic/master/guides/addons/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S
