Repository kubermatic/docs, pull requests merged in 2021-01, with the labels that each got.

#488 Fixing typos in faq for dashboard
  content/kubermatic/master/faq/dashboard/_index.en.md
  content/kubermatic/v2.15/faq/dashboard/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#502 KubeOne: Add the Architecture page
  content/kubeone/master/_index.en.md
  content/kubeone/master/advanced/_index.en.md
  content/kubeone/master/api_reference/_index.en.md
  content/kubeone/master/architecture/_index.en.md
  content/kubeone/master/infrastructure/_index.en.md
  content/kubeone/master/maintenance/_index.en.md
  content/kubeone/master/prerequisites/_index.en.md
  content/kubeone/master/provisioning/_index.en.md
  content/kubeone/master/unprovisioning/_index.en.md
  content/kubeone/master/upgrading/_index.en.md
  content/kubeone/master/workers/_index.en.md
  content/kubeone/v1.0/_index.en.md
  content/kubeone/v1.0/advanced/_index.en.md
  content/kubeone/v1.0/api_reference/_index.en.md
  content/kubeone/v1.0/architecture/_index.en.md
  content/kubeone/v1.0/infrastructure/_index.en.md
  content/kubeone/v1.0/maintenance/_index.en.md
  content/kubeone/v1.0/prerequisites/_index.en.md
  content/kubeone/v1.0/provisioning/_index.en.md
  content/kubeone/v1.0/unprovisioning/_index.en.md
  content/kubeone/v1.0/upgrading/_index.en.md
  content/kubeone/v1.0/workers/_index.en.md
  static/img/kubeone/master/architecture/architecture.png
  static/img/kubeone/v1.0/architecture/architecture.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#504 Add Service Account Token Volume Projection Documentation
  content/kubermatic/master/advanced/sa_token_projection/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#505 Add Kubeflow Addon documentation
  content/kubermatic/master/advanced/addons/kubeflow/_index.en.md
  layouts/shortcodes/table_of_contents.html
  static/img/kubermatic/master/advanced/addons/kubeflow/addon-details.png
  static/img/kubermatic/master/advanced/addons/kubeflow/addon.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#503 Added OPA Integration docs
  content/kubermatic/master/advanced/opa_integration/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#491 Define master and user cluster to ease end-user understanding
  content/kubermatic/master/requirements/cluster_requirements/_index.en.md
  content/kubermatic/v2.15/requirements/cluster_requirements/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
