Repository kubermatic/docs, pull requests merged in 2021-12, with the labels that each got.

#866 update documentation "disk.enableUUID=1"
  content/kubeone/master/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/master/architecture/requirements/machine_controller/vSphere/vSphere.en.md
  content/kubeone/v1.3/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/vSphere/vSphere.en.md
  content/kubermatic/master/architecture/requirements/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/vSphere/vSphere.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#864 Fix typo in KKP user documentation headline
  content/kubermatic/master/tutorials_howtos/administration/kkp_user/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#868 KubeOne: Document overriding Docker registries (RegistryConfiguration)
  content/kubeone/master/guides/registry_configuration/_index.en.md
  content/kubeone/v1.3/guides/registry_configuration/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#874 KubeOne: document overwriting CoreDNS registry issue
  content/kubeone/master/guides/registry_configuration/_index.en.md
  content/kubeone/v1.3/guides/registry_configuration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#875 Minor KubeOne docs fixes
  content/kubeone/master/guides/autoscaler_addon/_index.en.md
  content/kubeone/master/guides/registry_configuration/_index.en.md
  content/kubeone/v1.3/guides/autoscaler_addon/_index.en.md
  content/kubeone/v1.3/guides/registry_configuration/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#821 Add Hetzner to list of supported Tier 2 providers
  content/kubermatic/master/architecture/requirements/support_policy/provider_support_matrix/_index.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#869 Add preview of CRDs reference
  .codespell.exclude
  content/kubermatic/master/references/crds/_index.en.md
  hack/crd-templates/gv_details.tpl
  hack/crd-templates/gv_list.tpl
  hack/crd-templates/type.tpl
  hack/crd-templates/type_members.tpl
  hack/render-crds.sh
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#876 Use https for kubeone.io
  content/kubeone/master/guides/getting_kubeone/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_eks_d/_index.en.md
  content/kubeone/v1.0/getting_kubeone/_index.en.md
  content/kubeone/v1.2/getting_kubeone/_index.en.md
  content/kubeone/v1.3/guides/getting_kubeone/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_eks_d/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#878 Update the KubeOne Compatibility Matrix to add 1.23
  content/kubeone/master/architecture/compatibility/_index.en.md
  content/kubeone/v1.3/architecture/compatibility/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#877 updated etcd backup docs
  content/kubermatic/master/cheat_sheets/etcd/backup-and-restore/_index.en.md
  content/kubermatic/master/tutorials_howtos/administration/admin_panel/backup_buckets/_index.en.md
  content/kubermatic/master/tutorials_howtos/etcd_backups/_index.en.md
  static/img/kubermatic/master/tutorials/backups/add_backup_destination.png
  static/img/kubermatic/master/tutorials/backups/backup_buckets.png
  static/img/kubermatic/master/tutorials/backups/backup_destinations.png
  static/img/kubermatic/master/tutorials/backups/backup_seed_warning.png
  static/img/kubermatic/master/tutorials/backups/edit_backup_dest_credentials.png
  static/img/kubermatic/master/tutorials/backups/edit_backup_destination.png
  static/img/kubermatic/master/tutorials/backups/edit_buckets.png
  static/img/kubermatic/master/tutorials/backups/set_backup_credentials.png
  static/img/kubermatic/master/ui/add_backup.png
  static/img/kubermatic/master/ui/add_backup_snapshot.png
  static/img/kubermatic/master/ui/backup_snapshots.png
  static/img/kubermatic/master/ui/backups_list.png
  static/img/kubermatic/master/ui/etcd_backups.png
  static/img/kubermatic/master/ui/etcd_restores_list.png
  static/img/kubermatic/master/ui/restore_list.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#879 Update supported RHEL versions for KubeOne
  content/kubeone/master/architecture/compatibility/_index.en.md
  content/kubeone/v1.3/architecture/compatibility/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#880 Fix broken image for kkp logo in startio docs
  content/kubermatic/master/_index.en.md
  content/kubermatic/master/installation/startio/_index.en.md
  content/kubermatic/v2.17/_index.en.md
  content/kubermatic/v2.17/img/KubermaticKubernetesPlatform-logo.jpg
  content/kubermatic/v2.18/_index.en.md
  content/kubermatic/v2.18/img/KubermaticKubernetesPlatform-logo.jpg
  content/kubermatic/v2.18/startio/_index.en.md
  static/img/KubermaticKubernetesPlatform-logo.jpg
Labels: lgtm, approved, size/S, dco-signoff: yes
