Repository kubermatic/docs, pull requests merged in 2021-04, with the labels that each got.

#594 Documentation for Multus-CNI
  content/kubermatic/v2.16/advanced/addons/multus/_index.en.md
  content/kubermatic/v2.16/advanced/addons/multus/multus-ui.png
Labels: approved, dco-signoff: yes, lgtm, sig/networking, size/L

#610 Add Addons docs to master
  content/kubermatic/master/guides/addons/_index.en.md
  content/kubermatic/master/guides/addons/kubeflow/_index.en.md
  content/kubermatic/master/guides/addons/multus/_index.en.md
  content/kubermatic/master/guides/addons/multus/multus-ui.png
Labels: approved, dco-signoff: yes, lgtm, size/XL

#612 Add rastislavs to KubeCarrier owners
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, size/XS

#613 Added documentation for datacenters
  content/kubermatic/master/tutorials/02-datacenters/01-admin-panel-dc.png
  content/kubermatic/master/tutorials/02-datacenters/02-add-dc-1.png
  content/kubermatic/master/tutorials/02-datacenters/02-add-dc-2.png
  content/kubermatic/master/tutorials/02-datacenters/03-filter-to-find-dc.png
  content/kubermatic/master/tutorials/02-datacenters/04-edit-dc.png
  content/kubermatic/master/tutorials/02-datacenters/05-enforced-psp.png
  content/kubermatic/master/tutorials/02-datacenters/05-use-dc-in-cluster-creation.png
  content/kubermatic/master/tutorials/02-datacenters/06-delete-dc.png
  content/kubermatic/master/tutorials/02-datacenters/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#615 add MLA runbook to CheatSheets
  content/kubermatic/master/cheat_sheets/logging_monitoring_alerting/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#609 add MLA customization to the master
  content/kubermatic/master/architecture/monitoring_logging_alerting/_index.en.md
  content/kubermatic/master/cheat_sheets/monitoring_logging_alerting/_index.en.md
  content/kubermatic/master/guides/operation/_index.en.md
  content/kubermatic/master/tutorials/03-monitoring-logging-alerting-customization/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#614 Document OPA UI
  content/kubermatic/master/tutorials/opa/_index.en.md
  content/kubermatic/master/tutorials/opa/add-config.png
  content/kubermatic/master/tutorials/opa/add-constraint.png
  content/kubermatic/master/tutorials/opa/admin-add-ct.png
  content/kubermatic/master/tutorials/opa/admin-ct-overview.png
  content/kubermatic/master/tutorials/opa/admin-ct.png
  content/kubermatic/master/tutorials/opa/admin-options.png
  content/kubermatic/master/tutorials/opa/admin.png
  content/kubermatic/master/tutorials/opa/cluster-overview.png
  content/kubermatic/master/tutorials/opa/config-overview.png
  content/kubermatic/master/tutorials/opa/config.png
  content/kubermatic/master/tutorials/opa/constraints-overview.png
  content/kubermatic/master/tutorials/opa/constraints-violations.png
  content/kubermatic/master/tutorials/opa/constraints.png
  content/kubermatic/master/tutorials/opa/edit-cluster-dialog.png
  content/kubermatic/master/tutorials/opa/edit-cluster.png
  content/kubermatic/master/tutorials/opa/wizard.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#618 add guide and concept for service account
  content/kubermatic/master/architecture/concepts/service_account/_index.en.md
  content/kubermatic/master/guides/service_account/_index.en.md
  static/img/kubermatic/master/guides/service_account/createServiceAccount.png
  static/img/kubermatic/master/guides/service_account/createServiceAccountToken.png
  static/img/kubermatic/master/guides/service_account/manageToken.png
  static/img/kubermatic/master/guides/service_account/serviceAccount.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#628 Re-organize MLA documentation
  content/kubermatic/master/architecture/concepts/monitoring_logging_alerting/_index.en.md
  content/kubermatic/master/cheat_sheets/alerting_runbook/_index.en.md
  content/kubermatic/master/guides/installation/expose_strategy/_index.en.md
  content/kubermatic/master/guides/installation/logging_stack/_index.en.md
  content/kubermatic/master/guides/installation/monitoring_stack/_index.en.md
  content/kubermatic/master/tutorials/operation/_index.en.md
  content/kubermatic/master/tutorials/operation/monitoring-logging-alerting-customization/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#601 add documentation for automation account
  content/kubermatic/master/architecture/concepts/automation_accounts/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#631 Clarification for separate master and seed cluster configuration
  content/kubermatic/v2.16/installation/add_seed_cluster/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#627 Allign nginx namespace name in the KubeOne OIDC doc
  content/kubeone/master/tutorials/creating_clusters_oidc/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#602 Added a page about syntax and content to MachineDeployment object.
  content/kubeone/master/guides/machine_controller/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#633 Update design on homepage
  assets/scss/_home.scss
  assets/scss/_projects.scss
  assets/scss/_theme-kubermatic.scss
  assets/scss/_theme.scss
  assets/scss/app.scss
  content/_index.md
  data/products.yaml
  layouts/index.html
  layouts/partials/logo.html
  static/img/KubeCarrier-logo.svg
  static/img/KubeOne-logo.svg
  static/img/KubermaticKubernetesPlatform-logo.svg
  static/img/header-logo-kubecarrier.png
  static/img/header-logo-kubeone.png
  static/img/header-logo-kubermatic.png
  static/img/icons/auto-scale-icon.svg
  static/img/icons/cash-icon.svg
  static/img/icons/kubernetes-icon.svg
  static/img/icons/person-icon.svg
  static/img/icons/stats-up-icon.svg
  static/img/icons/time-icon.svg
  static/img/kubermatic-kubernetes-platform.png
  themes/hugo-theme-learn/static/fonts/ubuntu-700.woff
  themes/hugo-theme-learn/static/fonts/ubuntu-700.woff2
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XL

#635 Added OPA concept
  content/kubermatic/master/architecture/concepts/opa_integration/_index.en.md
  content/kubermatic/master/architecture/concepts/opa_integration/admin-options.png
  content/kubermatic/master/architecture/concepts/opa_integration/admin.png
  content/kubermatic/master/architecture/concepts/opa_integration/arch.png
  content/kubermatic/master/architecture/concepts/opa_integration/edit-cluster-dialog.png
  content/kubermatic/master/architecture/concepts/opa_integration/edit-cluster.png
  content/kubermatic/master/architecture/concepts/opa_integration/wizard.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#629 Copy Operation and Upgrading docs to master
  content/kubermatic/master/cheat_sheets/debugging/_index.en.md
  content/kubermatic/master/cheat_sheets/etcd/_index.en.md
  content/kubermatic/master/cheat_sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/master/cheat_sheets/etcd/replacing-member/_index.en.md
  content/kubermatic/master/cheat_sheets/etcd/restoring-from-backup/_index.en.md
  content/kubermatic/master/guides/operation/_index.en.md
  content/kubermatic/master/tutorials/operation/control-plane/_index.en.md
  content/kubermatic/master/tutorials/operation/control-plane/resource-usage/_index.en.md
  content/kubermatic/master/tutorials/operation/control-plane/scaling/_index.en.md
  content/kubermatic/master/tutorials/operation/control-plane/upgrading/_index.en.md
  content/kubermatic/master/tutorials/operation/monitoring-logging-alerting-customization/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.10_to_2.11/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.11_to_2.12/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.12_to_2.13/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.13_to_2.14/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.14_to_2.15/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.14_to_2.15/chart_migration/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.14_to_2.15/helm_2to3/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.14_to_2.15/kubermatic_chart/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.14_to_2.15/kubermatic_operator/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.15_to_2.16/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.6_to_2.7/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.7_to_2.8/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.8_to_2.9/_index.en.md
  content/kubermatic/master/tutorials/upgrading/2.9_to_2.10/_index.en.md
  content/kubermatic/master/tutorials/upgrading/_index.en.md
  content/kubermatic/master/tutorials/upgrading/guidelines/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#637 Add link to home in header, sync main menu links
  assets/scss/_main-header.scss
  data/mainMenu.yml
  layouts/partials/main-header.html
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/M

#638 KubeOne Encryption Providers Guide
  content/kubeone/master/guides/encryption_providers/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#646 Prevent documentation pages from indexing except latest version of every product
  config.toml
  layouts/partials/header.html
  layouts/robots.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#652 Improve the KubeOne Encryption Providers document
  content/kubeone/master/guides/encryption_providers/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#642 Update preset dc restriction information
  content/kubermatic/master/tutorials_howtos/administration/presets/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/presets/_index.en.md
  static/img/kubermatic/master/ui/datacenter_names.png
  static/img/kubermatic/v2.17/ui/datacenter_names.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#656 hide release v2.17
  data/products.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#657 Fix make preview errors
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#649 Documentation for new etcd backup/restore
  content/kubermatic/master/cheat_sheets/etcd/backup-and-restore/_index.en.md
  content/kubermatic/master/cheat_sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/master/cheat_sheets/etcd/legacy_restore/_index.en.md
  content/kubermatic/master/cheat_sheets/etcd/replace_a_member/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#659 add guide how to deal with CoreOS EOS
  content/kubermatic/master/guides/kkp_os_support/_index.en.md
  content/kubermatic/master/guides/kkp_os_support/coreos_eos/_index.en.md
  content/kubermatic/v2.17/guides/kkp_os_support/_index.en.md
  content/kubermatic/v2.17/guides/kkp_os_support/coreos_eos/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#654 Adds upgrade doc for 2.16 to 2.17
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/chart_migration/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#661 Update k1 docs with KMS support
  content/kubeone/master/guides/encryption_providers/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#660 Add operator upgrade documentation for v2.17
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/kubermatic_operator/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#666 Documentation for new etcd backup/restore for v2.17
  content/kubermatic/v2.17/cheat_sheets/etcd/backup-and-restore/_index.en.md
  content/kubermatic/v2.17/cheat_sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/v2.17/cheat_sheets/etcd/legacy_restore/_index.en.md
  content/kubermatic/v2.17/cheat_sheets/etcd/replace_a_member/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#667 Change fields order in menu
  assets/scss/_theme-kubermatic.scss
  data/products.yaml
  layouts/partials/menu.html
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/S

#668 Add lines for sublevels of the navigation
  assets/scss/_theme-kubermatic.scss
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/S

#669 Update changelog documentation
  content/kubermatic/master/cheat_sheets/changelog/_index.en.md
  content/kubermatic/v2.17/cheat_sheets/changelog/_index.en.md
  static/img/kubermatic/master/ui/changelog.png
  static/img/kubermatic/v2.17/ui/changelog.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#634 fixed datacenter description
  content/kubermatic/master/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#671 Add the KubeOne Amazon EKS-D tutorial
  content/kubeone/master/tutorials/creating_clusters_eks_d/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_eks_d/architecture.png
  content/kubeone/master/tutorials/creating_clusters_eks_d/demo_thumbnail.jpg
Labels: approved, dco-signoff: yes, lgtm, size/XL

#672 Revert "hide release v2.17 (#656)"
  data/products.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#673 Remove manual installation guide
  content/kubermatic/master/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/master/guides/installation/install_kkp_CE/using_installer/_index.en.md
  content/kubermatic/master/guides/installation/install_kkp_CE/using_manual/_index.en.md
  content/kubermatic/v2.17/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.17/guides/installation/install_kkp_CE/using_installer/_index.en.md
  content/kubermatic/v2.17/guides/installation/install_kkp_CE/using_manual/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#674 Use latest doc version for KubeCarrier v0.3
  content/kubecarrier/v0.3/_index.md
  content/kubecarrier/v0.3/architecture/components.md
  content/kubecarrier/v0.3/architecture/concepts.md
  content/kubecarrier/v0.3/architecture/related_projects.md
  content/kubecarrier/v0.3/architecture/use_cases.md
  content/kubecarrier/v0.3/cheat_sheets/_index.md
  content/kubecarrier/v0.3/cheat_sheets/debugging.md
  content/kubecarrier/v0.3/examples/_index.md
  content/kubecarrier/v0.3/examples/redis_operator.md
  content/kubecarrier/v0.3/getting_started/20_installation.md
  content/kubecarrier/v0.3/getting_started/_index.md
  content/kubecarrier/v0.3/glossary/_index.md
  content/kubecarrier/v0.3/guides/_index.md
  content/kubecarrier/v0.3/guides/api_access.md
  content/kubecarrier/v0.3/guides/operator-compatibility.md
  content/kubecarrier/v0.3/img/CRDs.png
  content/kubecarrier/v0.3/img/kubecarrier_concepts.png
  content/kubecarrier/v0.3/img/kubecarrier_example_redis.png
  content/kubecarrier/v0.3/img/kubecarrier_service_hub.png
  content/kubecarrier/v0.3/img/operator_concepts.png
  content/kubecarrier/v0.3/references/_index.md
  content/kubecarrier/v0.3/references/api-reference.md
  content/kubecarrier/v0.3/references/glossary.md
  content/kubecarrier/v0.3/references/kubernetes-operators.md
  content/kubecarrier/v0.3/references/repository-organization.md
  content/kubecarrier/v0.3/tutorials_howtos/_index.md
  content/kubecarrier/v0.3/tutorials_howtos/api_usage/_index.md
  content/kubecarrier/v0.3/tutorials_howtos/api_usage/accounts.md
  content/kubecarrier/v0.3/tutorials_howtos/api_usage/catalogs.md
  content/kubecarrier/v0.3/tutorials_howtos/api_usage/crds.md
  content/kubecarrier/v0.3/tutorials_howtos/api_usage/service_clusters.md
  content/kubecarrier/v0.3/tutorials_howtos/installation/_index.md
  content/kubecarrier/v0.3/tutorials_howtos/installation/kkp_addon.md
  content/kubecarrier/v0.3/tutorials_howtos/installation/kubectl.md
  content/kubecarrier/v0.3/tutorials_howtos/requirements.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#675 Change KubeCarrier logo in v0.3
  content/kubecarrier/v0.3/_index.md
  content/kubecarrier/v0.3/img/KubeCarrier-logo.jpg
Labels: approved, dco-signoff: yes, lgtm, size/XS

#665 Updating kubecarrier-logo and kubeone-architecture image
  content/kubecarrier/master/_index.md
  content/kubecarrier/master/img/KubeCarrier-logo.jpg
  content/kubecarrier/master/img/KubeCarrier.png
  content/kubeone/master/_index.en.md
  content/kubeone/master/architecture/architecture.png
  content/kubeone/master/img/KubeOne-logo.jpg
  content/kubermatic/master/_index.en.md
  content/kubermatic/master/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/master/img/KubermaticKubernetesPlatform-logo.jpg
Labels: approved, dco-signoff: yes, lgtm, size/S

#676 Copy kubeone master docs to the future (and stable) v1.3
  content/kubeone/v1.3/_index.en.md
  content/kubeone/v1.3/architecture/_index.en.md
  content/kubeone/v1.3/architecture/architecture.png
  content/kubeone/v1.3/architecture/cluster_reconciliation/_index.en.md
  content/kubeone/v1.3/architecture/cluster_reconciliation/cluster_reconciliation.png
  content/kubeone/v1.3/architecture/compatibility/_index.en.md
  content/kubeone/v1.3/architecture/concepts/_index.en.md
  content/kubeone/v1.3/architecture/infrastructure_management/_index.en.md
  content/kubeone/v1.3/cheat_sheets/_index.en.md
  content/kubeone/v1.3/cheat_sheets/production_recommendations/_index.en.md
  content/kubeone/v1.3/cheat_sheets/troubleshooting/_index.en.md
  content/kubeone/v1.3/examples/_index.en.md
  content/kubeone/v1.3/examples/addons_backup/_index.en.md
  content/kubeone/v1.3/examples/addons_calico_vxlan/_index.en.md
  content/kubeone/v1.3/examples/ha_load_balancing/_index.en.md
  content/kubeone/v1.3/guides/_index.en.md
  content/kubeone/v1.3/guides/addons/_index.en.md
  content/kubeone/v1.3/guides/api_migration/_index.en.md
  content/kubeone/v1.3/guides/credentials/_index.md
  content/kubeone/v1.3/guides/encryption_providers/_index.en.md
  content/kubeone/v1.3/guides/getting_kubeone/_index.en.md
  content/kubeone/v1.3/guides/machine_controller/_index.en.md
  content/kubeone/v1.3/guides/manual_cluster_recovery/_index.en.md
  content/kubeone/v1.3/guides/manual_cluster_repair/_index.en.md
  content/kubeone/v1.3/guides/proxy/_index.en.md
  content/kubeone/v1.3/guides/ssh/_index.en.md
  content/kubeone/v1.3/guides/static_workers/_index.en.md
  content/kubeone/v1.3/guides/using_terraform_configs/_index.en.md
  content/kubeone/v1.3/img/KubeOne-logo.jpg
  content/kubeone/v1.3/references/_index.en.md
  content/kubeone/v1.3/references/kubeone_cluster_v1beta1/_index.en.md
  content/kubeone/v1.3/references/terraform_integration/_index.en.md
  content/kubeone/v1.3/tutorials/_index.en.md
  content/kubeone/v1.3/tutorials/changing_cluster_properties/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/architecture.png
  content/kubeone/v1.3/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_eks_d/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_eks_d/architecture.png
  content/kubeone/v1.3/tutorials/creating_clusters_eks_d/demo_thumbnail.jpg
  content/kubeone/v1.3/tutorials/creating_clusters_oidc/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_oidc/dex-oidc-login.jpg
  content/kubeone/v1.3/tutorials/unprovisioning_clusters/_index.en.md
  content/kubeone/v1.3/tutorials/upgrading_clusters/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL
