Repository kubermatic/docs, pull requests merged in 2021-08, with the labels that each got.

#740 Add KKP Autoscaler Images
  static/img/kubermatic/master/tutorials/add_autoscaler_addon.png
  static/img/kubermatic/master/tutorials/autoscaler_confirmation.png
  static/img/kubermatic/master/tutorials/delete_autoscaler.png
  static/img/kubermatic/master/tutorials/edit_autoscaler.png
  static/img/kubermatic/master/tutorials/install_autoscaler.png
  static/img/kubermatic/master/tutorials/kkp_autoscaler_dashboard.png
  static/img/kubermatic/master/tutorials/select_autoscaler.png
  static/img/kubermatic/v2.17/tutorials/add_autoscaler_addon.png
  static/img/kubermatic/v2.17/tutorials/autoscaler_confirmation.png
  static/img/kubermatic/v2.17/tutorials/delete_autoscaler.png
  static/img/kubermatic/v2.17/tutorials/edit_autoscaler.png
  static/img/kubermatic/v2.17/tutorials/install_autoscaler.png
  static/img/kubermatic/v2.17/tutorials/kkp_autoscaler_dashboard.png
  static/img/kubermatic/v2.17/tutorials/select_autoscaler.png
Labels: approved, dco-signoff: yes, lgtm, size/XS

#686 Use convert-kubeconfig command instead of referencing external script
  content/kubermatic/master/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_EE/_index.en.md
Labels: lgtm, lifecycle/stale, approved, size/M, dco-signoff: yes

#742 Add User Cluster MLA Docs
  content/kubermatic/master/architecture/monitoring_logging_alerting/_index.en.md
  content/kubermatic/master/architecture/monitoring_logging_alerting/master_seed/_index.en.md
  content/kubermatic/master/architecture/monitoring_logging_alerting/user_cluster/_index.en.md
  content/kubermatic/master/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/master/guides/installation/install_kkp_EE/_index.en.md
  content/kubermatic/master/guides/kkp_security/securing_system_services/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/master_seed/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/master_seed/customization/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/master_seed/installation/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/user_guide/_index.en.md
  static/img/kubermatic/master/monitoring/user_cluster/admin_panel.png
  static/img/kubermatic/master/monitoring/user_cluster/architecture.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_alert_rules.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_alert_rules_data.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_alertmanager.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_cluster_create.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_cluster_view.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_grafana_dashboards.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_grafana_datasources.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_grafana_orgs.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_grafana_orgs2.png
Labels: size/XL, lgtm, approved, dco-signoff: yes

#741 Add KKP Autoscaler
  content/kubermatic/master/tutorials_howtos/KKP_autoscaler/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/KKP_autoscaler/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#743 [User Cluster MLA] Add a walkthrough tutorial of setting up Alertmanager with Slack notifications
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/user_guide/_index.en.md
  content/kubermatic/master/tutorials_howtos/monitoring_logging_alerting/_index.en.md
  content/kubermatic/master/tutorials_howtos/monitoring_logging_alerting/user_cluster/_index.en.md
  content/kubermatic/master/tutorials_howtos/monitoring_logging_alerting/user_cluster/setting_up_alertmanager_with_slack_notifications/_index.en.md
  static/img/kubermatic/master/monitoring/user_cluster/alertmanager_status.png
  static/img/kubermatic/master/monitoring/user_cluster/create_logs_alert_rule.png
  static/img/kubermatic/master/monitoring/user_cluster/create_metrics_alert_rule.png
  static/img/kubermatic/master/monitoring/user_cluster/slack_alertmanager_config.png
  static/img/kubermatic/master/monitoring/user_cluster/slack_alerts.png
  static/img/kubermatic/master/monitoring/user_cluster/slack_config_channel.png
  static/img/kubermatic/master/monitoring/user_cluster/slack_dashboard.png
  static/img/kubermatic/master/monitoring/user_cluster/slack_incoming_webhook.png
  static/img/kubermatic/master/monitoring/user_cluster/slack_webhook_url.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#744 MLA: Update docs and images with User Cluster Recording & Alerting Rules tab
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/user_guide/_index.en.md
  content/kubermatic/master/tutorials_howtos/monitoring_logging_alerting/user_cluster/setting_up_alertmanager_with_slack_notifications/_index.en.md
  static/img/kubermatic/master/monitoring/user_cluster/create_logs_alert_rule.png
  static/img/kubermatic/master/monitoring/user_cluster/create_metrics_alert_rule.png
  static/img/kubermatic/master/monitoring/user_cluster/slack_alertmanager_config.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_alert_rules.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_alert_rules_data.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_alertmanager.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#750 MLA: Update data retention & scrape annotations docs
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/user_guide/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#751 Add meta description
  content/kubeone/master/architecture/cluster_reconciliation/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#756 Remove Gatekeeper from the default accessible addon list for master, KKP v2.17 and v2.16
  content/kubermatic/master/data/kubermaticConfiguration.yaml
  content/kubermatic/master/guides/addons/_index.en.md
  content/kubermatic/v2.16/advanced/addons/_index.en.md
  content/kubermatic/v2.16/data/kubermaticConfiguration.yaml
  content/kubermatic/v2.17/data/kubermaticConfiguration.yaml
  content/kubermatic/v2.17/guides/addons/_index.en.md
  data/kubermatic/v2.16/kubermaticConfiguration.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#758 Document extending scraping config for user cluster MLA prometheus
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/user_guide/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#762 Update KKP Documentation Images
  static/img/kubermatic/master/tutorials/add_machine_deployment.png
  static/img/kubermatic/master/tutorials/delete_cluster_button.png
  static/img/kubermatic/master/tutorials/machine_deployment_edit.png
  static/img/kubermatic/master/tutorials/revoke_token_cluster.png
  static/img/kubermatic/master/ui/dashboard.png
  static/img/kubermatic/v2.17/tutorials/add_machine_deployment.png
  static/img/kubermatic/v2.17/tutorials/delete_cluster_button.png
  static/img/kubermatic/v2.17/tutorials/machine_deployment_edit.png
  static/img/kubermatic/v2.17/tutorials/revoke_token_cluster.png
  static/img/kubermatic/v2.17/ui/dashboard.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#764 Add MLA addons docs
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/master/guides/monitoring_logging_alerting/user_cluster/user_guide/_index.en.md
  static/img/kubermatic/master/monitoring/user_cluster/ui_addons.png
  static/img/kubermatic/master/monitoring/user_cluster/ui_addons_select.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#763 Rework the Seed cluster backups section
  content/kubermatic/master/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/guides/installation/add_seed_cluster_EE/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#753 Documentation for start.kubermatic.io
  content/kubermatic/master/_index.en.md
  content/kubermatic/master/startio/_index.en.md
  content/kubermatic/master/startio/cheat_sheets/_index.en.md
  content/kubermatic/master/startio/cheat_sheets/access_to_cluster/_index.en.md
  content/kubermatic/master/startio/cheat_sheets/declarative_configurations/_index.en.md
  content/kubermatic/master/startio/cheat_sheets/troubleshoot_pipeline/_index.en.md
  content/kubermatic/master/startio/cheat_sheets/troubleshoot_pipeline/failed_pipeline.png
  content/kubermatic/master/startio/cheat_sheets/validate_cluster_health/_index.en.md
  content/kubermatic/master/startio/cheat_sheets/work_with_secrets/_index.en.md
  content/kubermatic/master/startio/concepts/_index.en.md
  content/kubermatic/master/startio/concepts/pipeline_definition/_index.en.md
  content/kubermatic/master/startio/concepts/pipeline_definition/pipeline.png
  content/kubermatic/master/startio/flow.png
  content/kubermatic/master/startio/guides/_index.en.md
  content/kubermatic/master/startio/guides/explore_content/_index.en.md
  content/kubermatic/master/startio/guides/explore_content/example-secrets.png
  content/kubermatic/master/startio/guides/setup_repository/_index.en.md
  content/kubermatic/master/startio/guides/setup_repository/kkp-login.png
  content/kubermatic/master/startio/guides/setup_repository/kkp-ui.png
  content/kubermatic/master/startio/guides/setup_repository/pipeline.png
  content/kubermatic/master/startio/guides/wizard/1.png
  content/kubermatic/master/startio/guides/wizard/2.png
  content/kubermatic/master/startio/guides/wizard/3.png
  content/kubermatic/master/startio/guides/wizard/4.png
  content/kubermatic/master/startio/guides/wizard/5.png
  content/kubermatic/master/startio/guides/wizard/_index.en.md
  content/kubermatic/master/startio/guides/wizard/congrats.png
  content/kubermatic/master/startio/guides/wizard/welcome.png
Labels: size/XL, lgtm, approved, dco-signoff: yes

#768 Update Kubeone Architecture Image in V1.2
  content/kubeone/v1.2/architecture/architecture.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#770 Add KKP Components Versioning Image for Master and v2.17
  content/kubermatic/master/architecture/requirements/support_policy/KKP_components_versioning/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/support_policy/KKP_components_versioning/_index.en.md
  static/img/kubermatic/master/architecture/kkp_components_versioning.png
  static/img/kubermatic/v2.17/architecture/kkp_components_versioning.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#761 Change Customer Cluster to User Cluster for wording consistency
  content/kubermatic/master/architecture/_index.en.md
  content/kubermatic/master/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/master/data/kubermaticConfiguration.yaml
  content/kubermatic/master/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/master/guides/installation/install_kkp_EE/_index.en.md
  content/kubermatic/master/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/_index.en.md
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/using-kubectl/_index.en.md
  content/kubermatic/v2.17/architecture/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/support_policy/KKP_components_versioning/_index.en.md
  content/kubermatic/v2.17/data/kubermaticConfiguration.yaml
  content/kubermatic/v2.17/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.17/guides/installation/install_kkp_EE/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/project_and_cluster_management/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/project_and_cluster_management/using-kubectl/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#765 Increase the minimum Kubernetes version that KubeOne can manage
  content/kubeone/master/architecture/compatibility/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes
