Repository kubermatic/docs, pull requests merged in 2022-06, with the labels that each got.

#936 Vsphere permission update
  content/kubeone/master/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/master/architecture/requirements/machine_controller/vSphere/vSphere.en.md
  content/kubeone/v1.3/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/vSphere/vSphere.en.md
  content/kubeone/v1.4/architecture/requirements/infrastructure_management/_index.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/v2.19/architecture/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/v2.20/architecture/support_policy/provider_support_matrix/vSphere/vSphere.en.md
Labels: size/XL, lgtm, approved, dco-signoff: yes

#1079 Refactor documentation for etcd backup and restore
  content/kubermatic/master/cheat_sheets/etcd/backup-and-restore/_index.en.md
  content/kubermatic/v2.20/cheat_sheets/etcd/backup-and-restore/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1081 Remove note on vSphere 1.22 limitation in KKP 2.19 docs
  content/kubermatic/v2.19/tutorials_howtos/CCM_migration/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1076 Use title case consistently across all pages
  content/kubermatic/master/architecture/concept/kkp-concepts/cluster_templates/_index.en.md
  content/kubermatic/master/cheat_sheets/_index.en.md
  content/kubermatic/master/cheat_sheets/etcd/legacy_restore/_index.en.md
  content/kubermatic/master/cheat_sheets/etcd/replace_a_member/_index.en.md
  content/kubermatic/master/installation/start_kkp/concepts/pipeline_definition/_index.en.md
  content/kubermatic/master/references/crds/_index.en.md
  content/kubermatic/master/tutorials_howtos/CCM_migration/CCM_migration_via_UI/_index.en.md
  content/kubermatic/master/tutorials_howtos/CCM_migration/_index.en.md
  content/kubermatic/master/tutorials_howtos/Deploy_your_application/_index.en.md
  content/kubermatic/master/tutorials_howtos/cluster_templates/_index.en.md
  content/kubermatic/master/tutorials_howtos/manage_worker's_node/_index.en.md
  content/kubermatic/master/tutorials_howtos/manage_worker's_node/ssh-access-to-worker-node/_index.en.md
  content/kubermatic/master/tutorials_howtos/manage_worker's_node/via_command_line/_index.en.md
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/_index.en.md
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/cluster_defaulting/_index.en.md
  content/kubermatic/v2.20/architecture/concept/kkp-concepts/cluster_templates/_index.en.md
  content/kubermatic/v2.20/cheat_sheets/_index.en.md
  content/kubermatic/v2.20/cheat_sheets/etcd/legacy_restore/_index.en.md
  content/kubermatic/v2.20/installation/start_kkp/concepts/pipeline_definition/_index.en.md
  content/kubermatic/v2.20/references/crds/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/CCM_migration/CCM_migration_via_UI/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/CCM_migration/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/Deploy_your_application/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/cluster_templates/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/manage_worker's_node/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/manage_worker's_node/ssh-access-to-worker-node/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/manage_worker's_node/via_command_line/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/project_and_cluster_management/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/project_and_cluster_management/cluster_defaulting/_index.en.md
  hack/crd-templates/gv_list.tpl
Labels: lgtm, approved, size/M, dco-signoff: yes

#1083 Add more info about capacity planning for cortex
  content/kubermatic/master/tutorials_howtos/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1086 Fixed REF_NOT_FOUND error for ref link encountered during build
  content/kubermatic/master/tutorials_howtos/Deploy_your_application/_index.en.md
  content/kubermatic/v2.17/examples/Deploy_your_application/_index.en.md
  content/kubermatic/v2.18/examples/Deploy_your_application/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/Deploy_your_application/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/Deploy_your_application/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1090 Replace `image-loader` with `kubermatic-installer mirror-images`
  content/kubermatic/master/installation/offline_mode/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1071 KKP Docs introduction changes (2.20 and master)
  content/kubermatic/master/_index.en.md
  content/kubermatic/v2.20/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1087 osm: add documentation for machine rotation
  content/kubermatic/master/tutorials_howtos/operating_system_manager/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1092 Improve generation for title and meta description
  layouts/index.html
  layouts/partials/header.html
  layouts/partials/title.html
  themes/hugo-theme-learn/layouts/partials/meta.html
Labels: lgtm, approved, size/M, dco-signoff: yes
