Repository kubermatic/docs, pull requests merged in 2022-11, with the labels that each got.

#1234 Update metering
  content/kubermatic/main/tutorials-howtos/metering/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1238 Fix some typos
  content/kubeone/main/guides/all-in-one-node/_index.en.md
  content/kubeone/v1.5/guides/all-in-one-node/_index.en.md
  content/kubermatic/v2.13/advanced/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.14/advanced/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.15/advanced/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.16/advanced/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.16/concepts/expose-strategy/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/KKP_configuration/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/KKP_configuration/dynamic_kubelet_config/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1237 KubeOne: add guides for creating vSphere template VMs
  content/kubeone/main/guides/vsphere-template-vm/_index.en.md
  content/kubeone/main/guides/vsphere-template-vm/centos/_index.en.md
  content/kubeone/main/guides/vsphere-template-vm/ubuntu/_index.en.md
  content/kubeone/v1.4/guides/vsphere-template-vm/_index.en.md
  content/kubeone/v1.4/guides/vsphere-template-vm/centos/_index.en.md
  content/kubeone/v1.4/guides/vsphere-template-vm/ubuntu/_index.en.md
  content/kubeone/v1.5/guides/vsphere-template-vm/_index.en.md
  content/kubeone/v1.5/guides/vsphere-template-vm/centos/_index.en.md
  content/kubeone/v1.5/guides/vsphere-template-vm/ubuntu/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1236 Document expose strategy port number usage
  content/kubermatic/main/tutorials-howtos/networking/expose-strategies/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1241 Update swagger specs from patch releases 2.21.3, 2.20.10 and 2.19.12
  content/kubermatic/v2.19/data/swagger.json
  content/kubermatic/v2.20/data/swagger.json
  content/kubermatic/v2.21/data/swagger.json
Labels: size/XL, lgtm, approved, dco-signoff: yes

#1239 Update metering in KKP 2.21
  content/kubermatic/main/tutorials-howtos/metering/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/metering/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1243 Copy over vSphere needed permissions for KKP
  content/kubermatic/main/architecture/supported-providers/vSphere/vSphere.en.md
  content/kubermatic/v2.21/architecture/supported-providers/vSphere/vSphere.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1250 Add documentation for tagging mechanism for vSphere
  content/kubermatic/v2.21/architecture/supported-providers/vSphere/vSphere.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1252 Add notice about upgrading and mla-secrets chart.
  content/kubermatic/v2.19/tutorials_howtos/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1253 Update link for join to slack
  config.toml
  content/kubermatic/main/how-to-contribute-to-kkp/_index.en.md
  content/kubermatic/main/installation/start-kkp/_index.en.md
  content/kubermatic/v2.19/how_to_contribute_to_kkp/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/_index.en.md
  content/kubermatic/v2.20/how_to_contribute_to_kkp/_index.en.md
  content/kubermatic/v2.20/installation/start_kkp/_index.en.md
  content/kubermatic/v2.21/how-to-contribute-to-kkp/_index.en.md
  content/kubermatic/v2.21/installation/start-kkp/_index.en.md
  layouts/shortcodes/slackjoinlink.html
Labels: lgtm, approved, size/S, dco-signoff: yes

#1255 Drop support for Kubernetes 1.22 in KubeOne 1.6
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/v1.4/architecture/compatibility/_index.en.md
  content/kubeone/v1.5/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1219 update kubevirt doc for topology spread constaint
  content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1254 Update AWS section in dual-stack
  content/kubermatic/main/tutorials-howtos/networking/dual-stack/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1263 Remove temporary directory for OSM
  _content/operatingsystemmanager/_index.en.md
  _content/operatingsystemmanager/master/_index.en.md
  _content/operatingsystemmanager/master/architecture/_index.en.md
  _content/operatingsystemmanager/master/cheat-sheets/_index.en.md
  _content/operatingsystemmanager/master/cheat-sheets/rollout-machinedeployment/_index.en.md
  _content/operatingsystemmanager/master/compatibility/_index.en.md
  _content/operatingsystemmanager/master/data/osp-ubuntu-swap-enabled.yaml
  _content/operatingsystemmanager/master/guides/_index.en.md
  _content/operatingsystemmanager/master/guides/customize-operating-system-profile/_index.en.md
  _content/operatingsystemmanager/master/guides/machine-rotation/_index.en.md
  _content/operatingsystemmanager/master/guides/osm-configuration/_index.en.md
  _content/operatingsystemmanager/master/img/operating-system-manager-logo.png
  _content/operatingsystemmanager/master/references/_index.en.md
  _content/operatingsystemmanager/master/references/crds/_index.en.md
  _content/operatingsystemmanager/v1.0/_index.en.md
  _content/operatingsystemmanager/v1.0/architecture/_index.en.md
  _content/operatingsystemmanager/v1.0/cheat-sheets/_index.en.md
  _content/operatingsystemmanager/v1.0/cheat-sheets/rollout-machinedeployment/_index.en.md
  _content/operatingsystemmanager/v1.0/compatibility/_index.en.md
  _content/operatingsystemmanager/v1.0/data/osp-ubuntu-swap-enabled.yaml
  _content/operatingsystemmanager/v1.0/guides/_index.en.md
  _content/operatingsystemmanager/v1.0/guides/customize-operating-system-profile/_index.en.md
  _content/operatingsystemmanager/v1.0/guides/machine-rotation/_index.en.md
  _content/operatingsystemmanager/v1.0/guides/osm-configuration/_index.en.md
  _content/operatingsystemmanager/v1.0/img/operating-system-manager-logo.png
  _content/operatingsystemmanager/v1.0/references/_index.en.md
  _content/operatingsystemmanager/v1.0/references/crds/_index.en.md
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1264 Add product description for OSM
  data/products.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1268 Update User Cluster MLA docs with grafana-agent mentions
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/user-guide/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes
