Repository kubermatic/docs, pull requests merged in 2022-02, with the labels that each got.

#933 Minor Fixes to OIDC documentation
  content/kubeone/master/tutorials/creating_clusters_oidc/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters_oidc/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#937 Document operating system manager usage
  content/kubermatic/master/tutorials_howtos/operating_system_manager/usage/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/operating_system_manager/usage/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#935 Corrected custom certificate configuration for nginx
  content/kubermatic/v2.19/tutorials_howtos/KKP_configuration/custom_certificates/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#963 Add documentation for registriesAuth and csiConfig in credentials.yaml
  content/kubeone/master/guides/credentials/_index.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#964 Update the KubeOne docs
  content/kubeone/master/_index.en.md
  content/kubeone/master/architecture/_index.en.md
  content/kubeone/master/architecture/compatibility/_index.en.md
  content/kubeone/master/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/master/cheat_sheets/_index.en.md
  content/kubeone/master/examples/_index.en.md
  content/kubeone/master/examples/addons_backup/_index.en.md
  content/kubeone/master/examples/addons_calico_vxlan/_index.en.md
  content/kubeone/master/getting_kubeone/_index.en.md
  content/kubeone/master/guides/_index.en.md
  content/kubeone/master/guides/ccm_csi_migration/_index.en.md
  content/kubeone/master/guides/credentials/_index.md
  content/kubeone/master/guides/using_terraform_configs/_index.en.md
  content/kubeone/master/references/_index.en.md
  content/kubeone/master/tutorials/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubermatic/master/installation/start_kkp/cheat_sheets/access_to_cluster/_index.en.md
  content/kubermatic/v2.18/startio/cheat_sheets/access_to_cluster/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/cheat_sheets/access_to_cluster/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#968 KubeOne: document migrating to v1beta2 API
  content/kubeone/master/guides/api_migration/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#970 fix date format string
  content/kubeone/master/cheat_sheets/rollout_machinedeployment/_index.en.md
  content/kubeone/master/guides/ccm_csi_migration/_index.en.md
  content/kubeone/v1.3/cheat_sheets/rollout_machinedeployment/_index.en.md
  content/kubeone/v1.3/guides/ccm_csi_migration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#971 KubeOne: Upgrading from 1.3 to 1.4
  content/kubeone/master/tutorials/upgrading/upgrading_from_1.3_to_1.4/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#967 Document mirror registries in KubeOne
  content/kubeone/master/guides/api_migration/_index.en.md
  content/kubeone/master/guides/mirror_registries/_index.en.md
  content/kubeone/master/guides/registry_configuration/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#931 Prepare docs for kubeone release v1.4
  content/kubeone/v1.4/_index.en.md
  content/kubeone/v1.4/architecture/_index.en.md
  content/kubeone/v1.4/architecture/architecture.png
  content/kubeone/v1.4/architecture/cluster_reconciliation/_index.en.md
  content/kubeone/v1.4/architecture/cluster_reconciliation/cluster_reconciliation.png
  content/kubeone/v1.4/architecture/compatibility/_index.en.md
  content/kubeone/v1.4/architecture/concepts/_index.en.md
  content/kubeone/v1.4/architecture/requirements/_index.en.md
  content/kubeone/v1.4/architecture/requirements/infrastructure_management/_index.en.md
  content/kubeone/v1.4/architecture/requirements/machine_controller/_index.en.md
  content/kubeone/v1.4/architecture/requirements/machine_controller/aws/aws.en.md
  content/kubeone/v1.4/architecture/requirements/machine_controller/azure/_index.en.md
  content/kubeone/v1.4/architecture/requirements/machine_controller/google_cloud/gcp.en.md
  content/kubeone/v1.4/architecture/requirements/machine_controller/vSphere/vSphere.en.md
  content/kubeone/v1.4/cheat_sheets/_index.en.md
  content/kubeone/v1.4/cheat_sheets/production_recommendations/_index.en.md
  content/kubeone/v1.4/cheat_sheets/rollout_machinedeployment/_index.en.md
  content/kubeone/v1.4/cheat_sheets/troubleshooting/_index.en.md
  content/kubeone/v1.4/examples/_index.en.md
  content/kubeone/v1.4/examples/addons_backup/_index.en.md
  content/kubeone/v1.4/examples/addons_calico_vxlan/_index.en.md
  content/kubeone/v1.4/examples/ha_load_balancing/_index.en.md
  content/kubeone/v1.4/getting_kubeone/_index.en.md
  content/kubeone/v1.4/guides/_index.en.md
  content/kubeone/v1.4/guides/addons/_index.en.md
  content/kubeone/v1.4/guides/api_migration/_index.en.md
  content/kubeone/v1.4/guides/autoscaler_addon/_index.en.md
  content/kubeone/v1.4/guides/ccm_csi_migration/_index.en.md
  content/kubeone/v1.4/guides/ccm_csi_migration/troubleshooting/_index.en.md
  content/kubeone/v1.4/guides/containerd_migration/_index.en.md
  content/kubeone/v1.4/guides/credentials/_index.md
  content/kubeone/v1.4/guides/encryption_providers/_index.en.md
  content/kubeone/v1.4/guides/machine_controller/_index.en.md
  content/kubeone/v1.4/guides/manual_cluster_recovery/_index.en.md
  content/kubeone/v1.4/guides/manual_cluster_repair/_index.en.md
  content/kubeone/v1.4/guides/mirror_registries/_index.en.md
  content/kubeone/v1.4/guides/proxy/_index.en.md
  content/kubeone/v1.4/guides/registry_configuration/_index.en.md
  content/kubeone/v1.4/guides/ssh/_index.en.md
  content/kubeone/v1.4/guides/static_workers/_index.en.md
  content/kubeone/v1.4/guides/using_terraform_configs/_index.en.md
  content/kubeone/v1.4/img/KubeOne-logo.jpg
  content/kubeone/v1.4/references/_index.en.md
  content/kubeone/v1.4/references/kubeone_cluster_v1beta1/_index.en.md
  content/kubeone/v1.4/references/kubeone_cluster_v1beta2/_index.en.md
  content/kubeone/v1.4/references/terraform_integration/_index.en.md
  content/kubeone/v1.4/tutorials/_index.en.md
  content/kubeone/v1.4/tutorials/changing_cluster_properties/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters/architecture.png
  content/kubeone/v1.4/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters_oidc/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters_oidc/dex-oidc-login.jpg
  content/kubeone/v1.4/tutorials/how_to_contribute_to_kubeone/_index.en.md
  content/kubeone/v1.4/tutorials/unprovisioning_clusters/_index.en.md
  content/kubeone/v1.4/tutorials/upgrading/_index.en.md
  content/kubeone/v1.4/tutorials/upgrading/upgrading_from_1.2_to_1.3/_index.en.md
  content/kubeone/v1.4/tutorials/upgrading/upgrading_from_1.3_to_1.4/_index.en.md
  content/kubeone/v1.4/tutorials/upgrading_clusters/_index.en.md
  data/products.yaml
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#934 Simplify docs creation for releases
  hack/README.md
  hack/prepare-release.sh
Labels: lgtm, size/L, approved, dco-signoff: yes

#915 Improve search behaviour
  assets/scss/_theme-kubermatic.scss
  config.toml
  layouts/_default/home.search.json
  layouts/section/list.json
  themes/hugo-theme-learn/layouts/index.json
  themes/hugo-theme-learn/layouts/partials/search.html
  themes/hugo-theme-learn/static/js/search.js
Labels: lgtm, size/L, approved, dco-signoff: yes

#974 kubeone: add a note about terraform refresh
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#978 Update instructions for accessing k8s cluster via start.kkp
  content/kubermatic/master/installation/start_kkp/cheat_sheets/access_to_cluster/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/cheat_sheets/access_to_cluster/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#980 Update swagger.json for KKP 2.19 to 2.19.1 swagger
  content/kubermatic/v2.19/data/swagger.json
Labels: lgtm, size/L, approved, dco-signoff: yes

#941 Get Started with KKP on Single Node using Kubeone
  content/kubermatic/master/installation/install_kkp_on_node/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#984 Updated the download repository name as per recent renaming changes
  content/kubermatic/master/installation/install_kkp_on_node/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#930 Describe KKP 2.20 upgrade procedure
  content/kubermatic/master/tutorials_howtos/upgrading/upgrade_from_2.19_to_2.20/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes
