Repository kubermatic/docs, pull requests merged in 2022-07, with the labels that each got.

#1088 Added documentation for installation KKP CE and EE on Azure and GCP
  content/kubermatic/master/installation/install_kkp_CE_on_Azure/_index.en.md
  content/kubermatic/master/installation/install_kkp_CE_on_Azure/add_seed_cluster_CE_on_Azure/_index.en.md
  content/kubermatic/master/installation/install_kkp_CE_on_GCP/_index.en.md
  content/kubermatic/master/installation/install_kkp_CE_on_GCP/add_seed_cluster_CE_on_GCP/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE_on_Azure/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE_on_Azure/add_seed_cluster_ee_on_azure/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE_on_GCP/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE_on_GCP/add_seed_cluster_ee_on_gcp/_index.en.md
  content/kubermatic/master/installation/offline_mode/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_Azure/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_Azure/add_seed_cluster_CE_on_Azure/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_GCP/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_GCP/add_seed_cluster_CE_on_GCP/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE_on_Azure/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE_on_Azure/add_seed_cluster_ee_on_azure/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE_on_GCP/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE_on_GCP/add_seed_cluster_ee_on_gcp/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1084 Update kubevirt docs for storageClass
  content/kubermatic/master/architecture/supported_providers/kubevirt/kubevirt.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1089 Added documentation for KKP CE and EE installation for AWS and vSphere
  content/kubermatic/master/installation/install_kkp_CE_on_AWS/_index.en.md
  content/kubermatic/master/installation/install_kkp_CE_on_AWS/add_seed_cluster_ce_on_aws/_index.en.md
  content/kubermatic/master/installation/install_kkp_CE_on_vSphere/_index.en.md
  content/kubermatic/master/installation/install_kkp_CE_on_vSphere/add_seed_cluster_ce_on_vsphere/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE_on_AWS/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE_on_AWS/add_seed_cluster_ee_on_aws/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE_on_vSphere/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE_on_vSphere/add_seed_cluster_ee_on_vsphere/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_AWS/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_AWS/add_seed_cluster_ce_on_aws/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_vSphere/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_vSphere/add_seed_cluster_ce_on_vsphere/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE_on_AWS/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE_on_AWS/add_seed_cluster_ee_on_aws/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE_on_vSphere/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE_on_vSphere/add_seed_cluster_ee_on_vsphere/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1096 Update main menu by follow menu on company website
  assets/js/menu-hover.min.js
  assets/scss/_main-header.scss
  data/mainMenu.yml
  layouts/partials/main-header.html
  static/img/icons/list-icon.svg
  static/img/icons/network-icon.svg
  static/img/icons/star-icon.svg
  static/img/menu/kkp-features.svg
  static/img/menu/kubecarrier.jpeg
  static/img/menu/kubeone.jpeg
  static/img/menu/kubermatic-kubernetes-subscription.jpeg
  static/img/menu/managed-custom-kubernetes.jpeg
  static/img/menu/managed-kubermatic-kubeone.jpeg
  static/img/menu/managed-kubermatic-kubernetes-platform.jpeg
  static/img/menu/professional-services.jpeg
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1098 Clarify KubeVirt status that it's tech-preview
  content/kubermatic/master/architecture/supported_providers/_index.en.md
  content/kubermatic/master/architecture/supported_providers/kubevirt/kubevirt.en.md
  content/kubermatic/v2.12/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/v2.13/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/v2.14/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/v2.15/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/v2.16/requirements/cloud_provider/kubevirt.en.md
  content/kubermatic/v2.17/architecture/requirements/support_policy/provider_support_matrix/kubevirt/kubevirt.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/_index.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/kubevirt/kubevirt.en.md
  content/kubermatic/v2.19/architecture/support_policy/provider_support_matrix/_index.en.md
  content/kubermatic/v2.19/architecture/support_policy/provider_support_matrix/kubevirt/kubevirt.en.md
  content/kubermatic/v2.20/architecture/support_policy/provider_support_matrix/_index.en.md
  content/kubermatic/v2.20/architecture/support_policy/provider_support_matrix/kubevirt/kubevirt.en.md
  data/kubermatic/master/runbook.json
Labels: lgtm, size/L, approved, dco-signoff: yes

#1101 Replace jquery and plugins with pure js
  assets/js/app.js
  assets/js/clipboard.min.js
  assets/js/featherlight.min.js
  assets/js/hugo-learn.js
  assets/js/img-lightbox.min.js
  assets/js/jquery-3.6.0.min.js
  assets/js/jquery.sticky.js
  assets/js/jump.min.js
  assets/js/learn.js
  assets/js/perfect-scrollbar.jquery.min.js
  assets/js/perfect-scrollbar.min.js
  assets/scss/_featherlight.min.scss
  assets/scss/_hugo-theme.scss
  assets/scss/_img-lightbox.scss
  assets/scss/_perfect-scrollbar.min.scss
  assets/scss/_perfect-scrollbar.scss
  assets/scss/_tabs.scss
  assets/scss/_theme-kubermatic.scss
  assets/scss/_theme.scss
  assets/scss/app.scss
  layouts/partials/footer.html
  layouts/partials/header.html
  themes/hugo-theme-learn/layouts/shortcodes/expand.html
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1104 KubeOne: change default number of worker nodes to two
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1091 Fix Loki docu
  content/kubermatic/v2.20/tutorials_howtos/monitoring_logging_alerting/master_seed/installation/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1105 Add meta descriptions for some pages
  content/kubecarrier/master/architecture/_index.md
  content/kubecarrier/master/cheat_sheets/_index.md
  content/kubecarrier/master/examples/_index.md
  content/kubecarrier/master/guides/_index.md
  content/kubecarrier/master/tutorials_howtos/_index.md
  content/kubecarrier/master/tutorials_howtos/api_usage/_index.md
  content/kubecarrier/v0.3/architecture/_index.md
  content/kubecarrier/v0.3/cheat_sheets/_index.md
  content/kubecarrier/v0.3/examples/_index.md
  content/kubecarrier/v0.3/guides/_index.md
  content/kubecarrier/v0.3/tutorials_howtos/_index.md
  content/kubecarrier/v0.3/tutorials_howtos/api_usage/_index.md
  content/kubermatic/master/installation/install_kkp_EE_on_AWS/add_seed_cluster_ee_on_aws/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE_on_AWS/add_seed_cluster_ee_on_aws/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1106 Created known issues page
  content/kubermatic/v2.18/architecture/known_issues/_index.en.md
  content/kubermatic/v2.19/architecture/known_issues/_index.en.md
  content/kubermatic/v2.20/architecture/known_issues/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1109 Update supported CNI versions
  content/kubermatic/master/tutorials_howtos/networking/cni_cluster_network/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/networking/cni_cluster_network/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1107 Add documentation on how to customize audit-logs sidecar
  content/kubermatic/master/tutorials_howtos/audit_logging/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1062 Added Meta Description
  content/kubermatic/v2.18/guides/_index.en.md
  content/kubermatic/v2.18/guides/installation/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.18/guides/installation/install_HA_kubernetes/_index.en.md
  content/kubermatic/v2.18/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.18/guides/installation/install_kkp_EE/_index.en.md
  content/kubermatic/v2.18/guides/installation/offline_mode/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/CCM_migration/CCM_migration_via_UI/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/CCM_migration/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/OIDC_Provider_Configuration/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/OPA_integration/OPA_integration_Via_UI/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/OPA_integration/[Experimental]_OPA_Mutation/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/OPA_integration/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/dashboard_customization/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/upgrading/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/upgrading/upgrade_from_2.13_to_2.14/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/upgrading/upgrade_from_2.14_to_2.15/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/chart_migration/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/upgrading/upgrade_from_2.16_to_2.17/kubermatic_operator/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/upgrading/upgrade_from_2.17_to_2.18/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
Labels: lgtm, ok-to-test, approved, size/S, dco-signoff: yes

#1102 Add copy behaviour for header anchors
  assets/js/app.js
  assets/scss/_theme-kubermatic.scss
  assets/scss/_theme.scss
Labels: lgtm, approved, size/M, dco-signoff: yes

#1119 Update mla installation document.
  content/kubermatic/master/tutorials_howtos/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes
