Repository kubermatic/docs, pull requests merged in 2022-08, with the labels that each got.

#1118 Update CE installation reference
  content/kubermatic/master/installation/install_kkp_CE/_index.en.md
Labels: lgtm, ok-to-test, size/XS, approved, dco-signoff: yes

#1123 Fix issue with copy links for tabs section
  assets/js/app.js
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1122 Add note about identifying audit logging source
  content/kubermatic/master/tutorials_howtos/audit_logging/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1117 Add Multi-Cluster IP Address Management (IPAM) feature documentation
  content/kubermatic/master/tutorials_howtos/networking/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/ipam/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1128 Generate the redirects to current stable version of the products
  config.toml
  content/kubecarrier/_index.md
  content/kubeone/_index.md
  content/kubermatic/_index.md
  layouts/_default/home.redirects
Labels: lgtm, approved, size/S, dco-signoff: yes

#1131 Update community slack information on contribution pages
  content/kubermatic/master/how-to-contribute-to-kkp/_index.en.md
  content/kubermatic/v2.19/how_to_contribute_to_kkp/_index.en.md
  content/kubermatic/v2.20/how_to_contribute_to_kkp/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1130 Mark metering page as enterprise feature via meta keyword
  content/kubermatic/master/tutorials-howtos/metering/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1132 Exclude the pages with redirect from sitemap
  content/kubecarrier/_index.md
  content/kubeone/_index.md
  content/kubermatic/_index.md
  layouts/_default/home.redirects
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1129 Add documentation for OIDC group bindings
  content/kubermatic/master/architecture/role-based-access-control/_index.en.md
  content/kubermatic/master/architecture/role-based-access-control/groups-support/_index.en.md
  static/img/kubermatic/master/architecture/group-rbac-add.png
  static/img/kubermatic/master/architecture/group-rbac-view.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1135 kubermatic: update provider preset doc screenshots
  static/img/kubermatic/master/ui/add_provider_first_step.png
  static/img/kubermatic/master/ui/create_preset.png
  static/img/kubermatic/master/ui/create_preset_second_step.png
  static/img/kubermatic/master/ui/create_preset_third_step_dc.png
  static/img/kubermatic/master/ui/preset_management.png
Labels: lgtm, size/XS, kind/documentation, approved, dco-signoff: yes

#1127 Update encryption at rest docs with clarifications
  content/kubermatic/master/tutorials-howtos/encryption-at-rest/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1124 Add dual-stack networking docs
  content/kubermatic/master/tutorials-howtos/networking/_index.en.md
  content/kubermatic/master/tutorials-howtos/networking/dual-stack/_index.en.md
  static/img/kubermatic/master/tutorials/networking/ui_cluster_advanced_nw_config.png
  static/img/kubermatic/master/tutorials/networking/ui_cluster_ip_family.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1137 kubeone local docs
  content/kubeone/master/guides/local/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1139 Better page title for kubeone All-in-one Cluster
  content/kubeone/master/guides/local/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1140 Fix broken links for internal pages
  content/kubermatic/master/installation/install-kkp-on-node/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/CCM_migration/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_on_node/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/CCM_migration/_index.en.md
  layouts/_default/home.redirects
Labels: lgtm, approved, size/S, dco-signoff: yes

#1141 Sync main menu with company website
  data/mainMenu.yml
  static/img/menu/professional-services.jpeg
Labels: lgtm, approved, size/M, dco-signoff: yes

#1143 Refactor & update general CNI/networking docs
  content/kubermatic/master/tutorials-howtos/networking/cni-cluster-network/_index.en.md
  content/kubermatic/master/tutorials-howtos/networking/dual-stack/_index.en.md
  static/img/kubermatic/master/tutorials/networking/ui_cluster_cni.png
  static/img/kubermatic/master/tutorials/networking/ui_cluster_konnectivity.png
  static/img/kubermatic/master/tutorials/networking/ui_cluster_networking.png
  static/img/kubermatic/master/tutorials/networking/ui_cluster_networking_advanced.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1145 Fix broken link
  layouts/_default/home.redirects
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1133 KubeOne: documentation for Operating System Manager
  README.md
  content/kubeone/master/architecture/compatibility/_index.en.md
  content/kubeone/master/architecture/concepts/_index.en.md
  content/kubeone/master/architecture/operating-system-manager/_index.en.md
  content/kubeone/master/architecture/operating-system-manager/compatibility/_index.en.md
  content/kubeone/master/architecture/operating-system-manager/usage/_index.en.md
  static/img/kubeone/master/operating-system-manager/architecture.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1148 Split documentation for cluster settings and dashboard interface
  content/kubermatic/master/tutorials-howtos/administration/admin-panel/cluster-settings/_index.en.md
  content/kubermatic/master/tutorials-howtos/administration/admin-panel/interface/_index.en.md
  content/kubermatic/master/tutorials-howtos/administration/user-settings/_index.en.md
  static/img/kubermatic/master/ui/cluster_settings.png
  static/img/kubermatic/master/ui/get_kubeconfig.png
  static/img/kubermatic/master/ui/interface.png
  static/img/kubermatic/master/ui/resource_filter.png
  static/img/kubermatic/master/ui/resource_quota.png
  static/img/kubermatic/master/ui/user_projects_limit.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1146 Document changing of kube-proxy mode
  content/kubermatic/master/tutorials-howtos/networking/cni-cluster-network/_index.en.md
  content/kubermatic/master/tutorials-howtos/networking/cni-migration/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1149 Update documentation for KKP operating system support matrix
  content/kubermatic/master/architecture/compatibility/OS-support-matrix/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1134 Add Guides for Applications
  .gitignore
  content/kubermatic/master/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/master/tutorials-howtos/applications/_index.en.md
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/_index.en.md
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/application_customization.png
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/application_section.png
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/application_status.png
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/applications_flow_in_cluster_wizard.png
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/save_to_cluster_template.png
  content/kubermatic/master/tutorials-howtos/applications/application-catalogue.png
  content/kubermatic/master/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  layouts/shortcodes/toc.html
Labels: lgtm, size/L, approved, dco-signoff: yes

#1152 update screenshots for application guide
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/_index.en.md
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/application_customization.png
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/application_settings.png
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/application_values.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1154 KKP: docs for VMware Cloud Director
  content/kubermatic/master/architecture/supported-providers/_index.en.md
  content/kubermatic/master/architecture/supported-providers/vmware-cloud-director/vmware-cloud-director.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1155 Equinix uptier
  content/kubermatic/master/architecture/supported-providers/_index.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/_index.en.md
  content/kubermatic/v2.19/architecture/support_policy/provider_support_matrix/_index.en.md
  content/kubermatic/v2.20/architecture/support_policy/provider_support_matrix/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1147 Add note about kubeconfig requirements for external clusters
  content/kubermatic/master/tutorials-howtos/external-clusters/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/external_clusters/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1158 update dualstack docs: CentOS 7 + AWS unsupported
  content/kubermatic/master/tutorials-howtos/networking/dual-stack/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1153 DataVolume cloning documentation
  content/kubermatic/master/architecture/supported-providers/kubevirt/DV-cloning.png
  content/kubermatic/master/architecture/supported-providers/kubevirt/Source-DV-creation.png
  content/kubermatic/master/architecture/supported-providers/kubevirt/kubevirt.en.md
  content/kubermatic/master/architecture/supported-providers/kubevirt/primary-disk.png
Labels: lgtm, approved, size/M, dco-signoff: yes, sig/virtualization

#1151 Documentation for KubeVirt scheduling settings
  content/kubermatic/master/architecture/supported-providers/kubevirt/Dashboard-scheduling.png
  content/kubermatic/master/architecture/supported-providers/kubevirt/Scheduling.png
  content/kubermatic/master/architecture/supported-providers/kubevirt/kubevirt.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes, sig/virtualization

#1161 KubeVirt fix documentation images for DataVolume and Affinity
  content/kubermatic/master/architecture/supported-providers/kubevirt/kubevirt.en.md
  static/img/kubermatic/master/architecture/supported-providers/kubevirt/DV-cloning.png
  static/img/kubermatic/master/architecture/supported-providers/kubevirt/Dashboard-scheduling.png
  static/img/kubermatic/master/architecture/supported-providers/kubevirt/Scheduling.png
  static/img/kubermatic/master/architecture/supported-providers/kubevirt/Source-DV-creation.png
  static/img/kubermatic/master/architecture/supported-providers/kubevirt/primary-disk.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1157 Add note regarding NetworkPolicy requirement for audit logs output
  content/kubermatic/master/tutorials-howtos/audit-logging/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1164 Update dual-stack limitations
  content/kubermatic/master/tutorials-howtos/networking/dual-stack/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1166 destroy base64 encoding of secret to prevent users from reusing it
  content/kubermatic/master/tutorials-howtos/encryption-at-rest/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1167 Fixed AWS EE seed page title
  content/kubermatic/v2.20/installation/install_kkp_EE_on_AWS/add_seed_cluster_ee_on_aws/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1163 kubeone: migration for AWS machines using flatcar with cloud-init
  content/kubeone/master/architecture/operating-system-manager/usage/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1156 Update multi-cluster IPAM docs
  content/kubermatic/master/tutorials-howtos/networking/ipam/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1169 Add documentation for Operating System Manager
  _content/operatingsystemmanager/_index.en.md
  _content/operatingsystemmanager/master/_index.en.md
  _content/operatingsystemmanager/master/architecture/_index.en.md
  _content/operatingsystemmanager/master/cheat-sheets/_index.en.md
  _content/operatingsystemmanager/master/cheat-sheets/rollout-machinedeployment/_index.en.md
  _content/operatingsystemmanager/master/compatibility/_index.en.md
  _content/operatingsystemmanager/master/data/osp-ubuntu-swap-enabled.yaml
  _content/operatingsystemmanager/master/guides/_index.en.md
  _content/operatingsystemmanager/master/guides/customize-operating-system-profile/_index.en.md
  _content/operatingsystemmanager/master/guides/machine-rotation/_index.en.md
  _content/operatingsystemmanager/master/guides/osm-configuration/_index.en.md
  _content/operatingsystemmanager/master/img/operating-system-manager-logo.png
  _content/operatingsystemmanager/master/references/_index.en.md
  _content/operatingsystemmanager/master/references/crds/_index.en.md
  _content/operatingsystemmanager/v1.0/_index.en.md
  _content/operatingsystemmanager/v1.0/architecture/_index.en.md
  _content/operatingsystemmanager/v1.0/cheat-sheets/_index.en.md
  _content/operatingsystemmanager/v1.0/cheat-sheets/rollout-machinedeployment/_index.en.md
  _content/operatingsystemmanager/v1.0/compatibility/_index.en.md
  _content/operatingsystemmanager/v1.0/data/osp-ubuntu-swap-enabled.yaml
  _content/operatingsystemmanager/v1.0/guides/_index.en.md
  _content/operatingsystemmanager/v1.0/guides/customize-operating-system-profile/_index.en.md
  _content/operatingsystemmanager/v1.0/guides/machine-rotation/_index.en.md
  _content/operatingsystemmanager/v1.0/guides/osm-configuration/_index.en.md
  _content/operatingsystemmanager/v1.0/img/operating-system-manager-logo.png
  _content/operatingsystemmanager/v1.0/references/_index.en.md
  _content/operatingsystemmanager/v1.0/references/crds/_index.en.md
  content/kubeone/master/architecture/_index.en.md
  content/kubeone/master/architecture/architecture.jpg
  content/kubeone/master/architecture/architecture.png
  content/kubeone/master/architecture/operating-system-manager/_index.en.md
  content/kubermatic/master/architecture/supported-providers/vmware-cloud-director/vmware-cloud-director.md
  content/kubermatic/master/cheat-sheets/rollout-machinedeployment/_index.en.md
  content/kubermatic/master/tutorials-howtos/operating-system-manager/_index.en.md
  content/kubermatic/master/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/kubermatic/master/tutorials-howtos/operating-system-manager/machine-rotation/_index.en.md
  content/kubermatic/master/tutorials-howtos/operating-system-manager/usage/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/operating_system_manager/usage/_index.en.md
  hack/render-crds.sh
  static/img/kubermatic/master/architecture/combined-master-seed.png
  static/img/kubermatic/master/architecture/dedicated-seeds.png
  static/img/kubermatic/master/tutorials/operating_system_manager/osm_dashboard.png
  static/img/kubermatic/master/tutorials/operating_system_manager/osm_select.png
  static/img/operating-system-manager-logo.svg
  static/img/operatingsystemmanager/master/osm-kubernetes.png
  static/img/operatingsystemmanager/master/osp-ubuntu-swap-enabled.png
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1171 Use ubuntu in custom OSP example
  _content/operatingsystemmanager/master/guides/customize-operating-system-profile/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1165 Enhance documentation for KubeVirt VirtualMachineInstancePreset
  content/kubermatic/master/architecture/supported-providers/kubevirt/kubevirt.en.md
  static/img/kubermatic/master/architecture/supported-providers/kubevirt/Dedicated-namespace.jpg
  static/img/kubermatic/master/architecture/supported-providers/kubevirt/Preset.jpg
  static/img/kubermatic/master/architecture/supported-providers/kubevirt/clusterid.png
Labels: lgtm, kind/documentation, approved, size/M, dco-signoff: yes, sig/virtualization

#1173 Cleanup and improve theme
  config.toml
  static/img/icons/auto-scale-icon.svg
  static/img/icons/cash-icon.svg
  static/img/icons/kubernetes-icon.svg
  static/img/icons/person-icon.svg
  static/img/icons/stats-up-icon.svg
  static/img/icons/time-icon.svg
  themes/kubermatic-docs/assets/scss/_theme.scss
  themes/kubermatic-docs/i18n/ar.toml
  themes/kubermatic-docs/i18n/de.toml
  themes/kubermatic-docs/i18n/en.toml
  themes/kubermatic-docs/i18n/es.toml
  themes/kubermatic-docs/i18n/fr.toml
  themes/kubermatic-docs/i18n/hi.toml
  themes/kubermatic-docs/i18n/id.toml
  themes/kubermatic-docs/i18n/nl.toml
  themes/kubermatic-docs/i18n/pt.toml
  themes/kubermatic-docs/i18n/tr.toml
  themes/kubermatic-docs/layouts/partials/menu.html
  themes/kubermatic-docs/static/fonts/Inconsolata.eot
  themes/kubermatic-docs/static/fonts/Inconsolata.svg
  themes/kubermatic-docs/static/fonts/Inconsolata.ttf
  themes/kubermatic-docs/static/fonts/Inconsolata.woff
  themes/kubermatic-docs/static/fonts/Novecentosanswide-Normal-webfont.eot
  themes/kubermatic-docs/static/fonts/Novecentosanswide-Normal-webfont.svg
  themes/kubermatic-docs/static/fonts/Novecentosanswide-Normal-webfont.ttf
  themes/kubermatic-docs/static/fonts/Novecentosanswide-Normal-webfont.woff
  themes/kubermatic-docs/static/fonts/Novecentosanswide-Normal-webfont.woff2
  themes/kubermatic-docs/static/fonts/Novecentosanswide-UltraLight-webfont.eot
  themes/kubermatic-docs/static/fonts/Novecentosanswide-UltraLight-webfont.svg
  themes/kubermatic-docs/static/fonts/Novecentosanswide-UltraLight-webfont.ttf
  themes/kubermatic-docs/static/fonts/Novecentosanswide-UltraLight-webfont.woff
  themes/kubermatic-docs/static/fonts/Novecentosanswide-UltraLight-webfont.woff2
  themes/kubermatic-docs/static/fonts/Work_Sans_200.eot
  themes/kubermatic-docs/static/fonts/Work_Sans_200.svg
  themes/kubermatic-docs/static/fonts/Work_Sans_200.ttf
  themes/kubermatic-docs/static/fonts/Work_Sans_200.woff
  themes/kubermatic-docs/static/fonts/Work_Sans_200.woff2
  themes/kubermatic-docs/static/fonts/Work_Sans_300.eot
  themes/kubermatic-docs/static/fonts/Work_Sans_300.svg
  themes/kubermatic-docs/static/fonts/Work_Sans_300.ttf
  themes/kubermatic-docs/static/fonts/Work_Sans_300.woff
  themes/kubermatic-docs/static/fonts/Work_Sans_300.woff2
  themes/kubermatic-docs/static/fonts/Work_Sans_500.eot
  themes/kubermatic-docs/static/fonts/Work_Sans_500.svg
  themes/kubermatic-docs/static/fonts/Work_Sans_500.ttf
  themes/kubermatic-docs/static/fonts/Work_Sans_500.woff
  themes/kubermatic-docs/static/fonts/Work_Sans_500.woff2
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1172 Document KubeVirt migration from 2.20 to 2.21
  content/kubermatic/master/architecture/supported-providers/kubevirt/kubevirt.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1175 PodSecurityPolicy deprecation warning
  content/kubermatic/master/architecture/concept/kkp-concepts/kkp-security/pod-security-policy/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1176 KKP: docs for custom OSP
  content/kubermatic/master/tutorials-howtos/operating-system-manager/usage/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1177 Update dual-stack docs with compatibility matrix
  content/kubermatic/master/tutorials-howtos/networking/dual-stack/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1183 kubermatic: update user settings docs
  content/kubermatic/master/tutorials-howtos/administration/user-settings/_index.en.md
  static/img/kubermatic/master/ui/user_settings.png
Labels: lgtm, size/XS, kind/documentation, approved, dco-signoff: yes, KKP

#1181 refactor KubeVirt documentation
  content/kubermatic/master/architecture/supported-providers/kubevirt/kubevirt.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1185 Exclude references/crds pages of KKP from search index
  content/kubermatic/master/references/crds/_index.en.md
  content/kubermatic/v2.20/references/crds/_index.en.md
  layouts/_default/home.search.json
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1160 Update metering report documentation
  content/kubermatic/master/tutorials-howtos/metering/_index.en.md
  static/img/kubermatic/master/tutorials/metering_admin_panel_location.png
  static/img/kubermatic/master/tutorials/metering_overview.png
  static/img/kubermatic/master/tutorials/metering_report_configuration.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1189 add note to group oidc docs that grafana is not yet supported
  content/kubermatic/master/architecture/role-based-access-control/groups-support/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1186 applications: add example of crd
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/_index.en.md
  content/kubermatic/master/tutorials-howtos/applications/create-application-catalogue/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1187 add apps.kubermatic to kubermatic/master/references/crds page
  content/kubermatic/master/references/crds/_index.en.md
  hack/crd-templates/gv_list.tpl
  hack/render-crds.sh
Labels: lgtm, size/L, approved, dco-signoff: yes

#1188 Make UUID optional
  content/kubermatic/master/tutorials-howtos/telemetry/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1193 Remove metering comment
  content/kubermatic/master/tutorials-howtos/metering/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1194 Add the Known Issues and Upgrading documents for KubeOne 1.5
  content/kubeone/master/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/master/known-issues/_index.en.md
  content/kubeone/master/tutorials/upgrading/upgrading-from-1.4-to-1.5/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1195 Sync the KubeOne v1.5 docs with the master docs
  content/kubeone/v1.5/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/v1.5/known-issues/_index.en.md
  content/kubeone/v1.5/references/kubeone_cluster_v1beta1/_index.en.md
  content/kubeone/v1.5/references/kubeone_cluster_v1beta2/_index.en.md
  content/kubeone/v1.5/tutorials/upgrading/upgrading-from-1.4-to-1.5/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1197 remove comment
  content/kubermatic/v2.21/tutorials-howtos/metering/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1198 Remove duplicate pages with underscore in url
  content/kubeone/master/references/kubeone_cluster_v1beta1/_index.en.md
  content/kubeone/master/references/kubeone_cluster_v1beta2/_index.en.md
  content/kubeone/v1.5/references/kubeone_cluster_v1beta1/_index.en.md
  content/kubeone/v1.5/references/kubeone_cluster_v1beta2/_index.en.md
  layouts/_default/home.redirects
Labels: lgtm, size/XXL, approved, dco-signoff: yes
