Repository kubermatic/docs, pull requests merged in 2022-12, with the labels that each got.

#1269 Update default cluster template docs
  content/kubermatic/main/tutorials-howtos/project-and-cluster-management/cluster-defaulting/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1271 Cilium docs fixes
  content/kubermatic/main/tutorials-howtos/networking/cni-cluster-network/_index.en.md
  content/kubermatic/v2.19/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/networking/cni_cluster_network/_index.en.md
  content/kubermatic/v2.20/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/networking/cni_cluster_network/_index.en.md
  content/kubermatic/v2.21/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/networking/cni-cluster-network/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1272 Update tunneling expose startegy section
  content/kubermatic/main/tutorials-howtos/networking/apiserver-policies/_index.en.md
  content/kubermatic/main/tutorials-howtos/networking/expose-strategies/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1273 Fix typo
  content/kubeone/v1.5/tutorials/creating-clusters/_index.en.md
Labels: lgtm, ok-to-test, size/XS, approved, dco-signoff: yes

#1274 Fix KubeOne tutorial typo on main as well
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1270 Helm Releases
  content/kubeone/main/guides/helm-integration/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1276 KubeVirt add ExperimentalIgnitionSupport featureGate
  content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1277 Update support matrix for Kubernetes 1.23 support in KKP 2.20
  content/kubermatic/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubermatic/v2.20/architecture/support_policy/supported_versions/_index.en.md
  content/kubermatic/v2.21/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1281 Document an issue with upgrading Canal CNI in KubeOne
  content/kubeone/main/known-issues/_index.en.md
  content/kubeone/v1.5/known-issues/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1278 Add Cilium Cluster Mesh guide
  content/kubermatic/main/tutorials-howtos/networking/_index.en.md
  content/kubermatic/main/tutorials-howtos/networking/cilium-cluster-mesh/_index.en.md
  content/kubermatic/main/tutorials-howtos/networking/ipam/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1266 Add documentation for defaulting tag category in the seed
  content/kubermatic/v2.21/architecture/supported-providers/vSphere/vSphere.en.md
  content/kubermatic/v2.21/data/seed.yaml
Labels: lgtm, approved, size/S, dco-signoff: yes

#1283 Update swagger.json for KKP 2.21.4
  content/kubermatic/v2.21/data/swagger.json
Labels: lgtm, approved, size/S, dco-signoff: yes
