Repository kubermatic/docs, pull requests merged in 2022-05, with the labels that each got.

#1063 fix KKP AWS Policy
  content/kubermatic/master/architecture/support_policy/provider_support_matrix/AWS/aws.en.md
  content/kubermatic/v2.19/architecture/support_policy/provider_support_matrix/AWS/aws.en.md
  content/kubermatic/v2.20/architecture/support_policy/provider_support_matrix/AWS/aws.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1066 Add Kubernetes 1.24 support to KubeOne master docs
  content/kubeone/master/architecture/compatibility/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/v1.3/architecture/compatibility/_index.en.md
  content/kubeone/v1.4/architecture/compatibility/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters_baremetal/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1068 Add Kubernetes 1.24 to support matrix for upcoming KKP 2.21
  content/kubermatic/master/architecture/support_policy/supported_versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes
