Repository kubermatic/docs, pull requests merged in 2022-10, with the labels that each got.

#1218 add some words to the AWS docs
  content/kubermatic/master/architecture/supported-providers/AWS/aws.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1220 add info about EtcdLauncherNotEnabled phase to backup/restore docs
  content/kubermatic/master/tutorials-howtos/etcd-backups/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1222 Enhance expose strategies docs + describe expose strategy migration
  content/kubermatic/master/tutorials-howtos/networking/cni-migration/_index.en.md
  content/kubermatic/master/tutorials-howtos/networking/expose-strategies/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1221 Update UserCluster MLA installation docs
  content/kubermatic/master/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1223 fix missing camel case for zoneSuffixes in KKP installtion doc
  content/kubermatic/v2.21/installation/install-kkp-CE-on-GCP/add-seed-cluster-CE-on-GCP/_index.en.md
  content/kubermatic/v2.21/installation/install-kkp-EE-on-GCP/add-seed-cluster-ee-on-gcp/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1226 Remove redirects and duplicates
  content/kubeone/main/references/kubeone_cluster_v1beta1/_index.en.md
  content/kubeone/main/references/kubeone_cluster_v1beta2/_index.en.md
  layouts/_default/home.redirects
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1228 Fix displaying for under construction banner in main branch of KubeOne
  themes/kubermatic-docs/layouts/partials/header.html
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1224 fix links in KubeOne docs
  content/kubeone/main/architecture/_index.en.md
  content/kubeone/main/architecture/concepts/_index.en.md
  content/kubeone/main/architecture/requirements/infrastructure-management/_index.en.md
  content/kubeone/main/guides/credentials/_index.md
  content/kubeone/main/guides/machine-controller/_index.en.md
  content/kubeone/main/guides/static-workers/_index.en.md
  content/kubeone/main/tutorials/creating-clusters-baremetal/_index.en.md
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.5/architecture/_index.en.md
  content/kubeone/v1.5/architecture/concepts/_index.en.md
  content/kubeone/v1.5/architecture/requirements/infrastructure-management/_index.en.md
  content/kubeone/v1.5/guides/credentials/_index.md
  content/kubeone/v1.5/guides/machine-controller/_index.en.md
  content/kubeone/v1.5/guides/static-workers/_index.en.md
  content/kubeone/v1.5/tutorials/creating-clusters-baremetal/_index.en.md
  content/kubeone/v1.5/tutorials/creating-clusters/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1230 Add link to Securing System Services page from master/seed MLA installation
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/installation/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/monitoring-logging-alerting/master-seed/installation/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1231 Document the documentation process at Kubermatic
  PROCESS.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1232 Update supported Kubernetes versions for KubeOne
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/v1.4/architecture/compatibility/_index.en.md
  content/kubeone/v1.5/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes
