Repository kubermatic/docs, pull requests merged in 2022-03, with the labels that each got.

#987 Add notice about not using passphrase for SSH keys for pipeline
  content/kubermatic/master/installation/start_kkp/guides/setup_repository/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/guides/setup_repository/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#905 Add updates from Mita
  content/kubermatic/master/_index.en.md
  static/img/kubermatic-kubernetes-platform.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#988 describe kubeconfig for gke and eks
  content/kubermatic/master/tutorials_howtos/external_clusters/eks/_index.en.md
  content/kubermatic/master/tutorials_howtos/external_clusters/gke/_index.en.md
  static/img/kubermatic/master/tutorials/external_clusters/gke_kubeconfig.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#998 Added Meta Description
  content/kubermatic/v2.18/startio/guides/explore_content/_index.en.md
Labels: lgtm, ok-to-test, size/XS, approved, dco-signoff: yes

#999 Added Meta Description
  content/kubermatic/v2.18/startio/guides/setup_repository/_index.en.md
Labels: lgtm, ok-to-test, size/XS, approved, dco-signoff: yes

#992 Added Meta Description
  content/kubermatic/v2.18/_index.en.md
Labels: lgtm, ok-to-test, size/XS, approved, dco-signoff: yes

#993 Added Meta Description
  content/kubermatic/v2.18/startio/_index.en.md
Labels: lgtm, ok-to-test, size/XS, approved, dco-signoff: yes

#1004 ccm/csi migration prerequisites update
  content/kubermatic/master/tutorials_howtos/CCM_migration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#991 Add documentation for Nutanix support
  content/kubermatic/master/architecture/support_policy/provider_support_matrix/_index.en.md
  content/kubermatic/master/architecture/support_policy/provider_support_matrix/nutanix/nutanix.en.md
  content/kubermatic/master/tutorials_howtos/administration/admin_panel/presets_management/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1006 Update Kubevirt configuration required by KKP
  content/kubermatic/master/architecture/support_policy/provider_support_matrix/kubevirt/kubevirt.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1008 Add a note to EtcdLauncher feature flag
  content/kubermatic/master/cheat_sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/v2.19/cheat_sheets/etcd/etcd-launcher/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1010 Update start_kkp documentation with Bitbucket
  content/kubermatic/master/installation/start_kkp/cheat_sheets/access_to_cluster/_index.en.md
  content/kubermatic/master/installation/start_kkp/cheat_sheets/troubleshoot_pipeline/_index.en.md
  content/kubermatic/master/installation/start_kkp/concepts/_index.en.md
  content/kubermatic/master/installation/start_kkp/concepts/pipeline_definition/_index.en.md
  content/kubermatic/master/installation/start_kkp/concepts/pipeline_definition/pipeline.png
  content/kubermatic/master/installation/start_kkp/flow.png
  content/kubermatic/master/installation/start_kkp/guides/explore_content/_index.en.md
  content/kubermatic/master/installation/start_kkp/guides/setup_repository/_index.en.md
  content/kubermatic/master/installation/start_kkp/guides/wizard/1.png
  content/kubermatic/master/installation/start_kkp/guides/wizard/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/cheat_sheets/access_to_cluster/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/cheat_sheets/troubleshoot_pipeline/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/concepts/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/concepts/pipeline_definition/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/concepts/pipeline_definition/pipeline.png
  content/kubermatic/v2.19/installation/start_kkp/flow.png
  content/kubermatic/v2.19/installation/start_kkp/guides/explore_content/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/guides/setup_repository/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/guides/wizard/1.png
  content/kubermatic/v2.19/installation/start_kkp/guides/wizard/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1002 updated etcd backup docs after removing legacy config options
  content/kubermatic/master/cheat_sheets/etcd/backup-and-restore/_index.en.md
  content/kubermatic/master/tutorials_howtos/administration/admin_panel/backup_buckets/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1015 start.kubermatic bitbucket doc updates for v2.20
  content/kubermatic/v2.20/installation/start_kkp/cheat_sheets/access_to_cluster/_index.en.md
  content/kubermatic/v2.20/installation/start_kkp/cheat_sheets/troubleshoot_pipeline/_index.en.md
  content/kubermatic/v2.20/installation/start_kkp/concepts/_index.en.md
  content/kubermatic/v2.20/installation/start_kkp/concepts/pipeline_definition/_index.en.md
  content/kubermatic/v2.20/installation/start_kkp/concepts/pipeline_definition/pipeline.png
  content/kubermatic/v2.20/installation/start_kkp/flow.png
  content/kubermatic/v2.20/installation/start_kkp/guides/explore_content/_index.en.md
  content/kubermatic/v2.20/installation/start_kkp/guides/setup_repository/_index.en.md
  content/kubermatic/v2.20/installation/start_kkp/guides/wizard/1.png
  content/kubermatic/v2.20/installation/start_kkp/guides/wizard/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#973 Add OS_REGION_NAME
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#960 fix link inside tab
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1016 backport OS_REGION_NAME variable to 1.3 and 1.4
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1012 Remove CRD reference from v2.19 docs, CRDs are not available there
  content/kubermatic/v2.19/references/crds/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#942 Update Multus docs
  content/kubermatic/master/tutorials_howtos/networking/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/cni_cluster_network/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/multus/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1014 Kubeone: add documentation for application credentials
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1022 Use search by product and version
  themes/hugo-theme-learn/layouts/partials/search.html
  themes/hugo-theme-learn/static/js/search.js
Labels: lgtm, approved, size/S, dco-signoff: yes

#1020 Kubeone all in one Node guide
  Makefile
  content/kubeone/master/guides/all_in_one_node/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1025 Update examples for KKP v2.20
  content/kubermatic/master/cheat_sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/master/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/master/tutorials_howtos/administration/admin_panel/presets_management/_index.en.md
  content/kubermatic/master/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
  content/kubermatic/master/tutorials_howtos/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/cni_cluster_network/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/expose_strategies/_index.en.md
  content/kubermatic/master/tutorials_howtos/operating_system_manager/usage/_index.en.md
  content/kubermatic/v2.20/cheat_sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/OIDC_Provider_Configuration/share _clusters_via_delegated_OIDC_authentication/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/administration/admin_panel/presets_management/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/networking/cni_cluster_network/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/networking/expose_strategies/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/operating_system_manager/usage/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#883 [KKP] update seed install documentation
  content/kubermatic/master/installation/install_kkp_CE/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_EE/add_seed_cluster_EE/_index.en.md
Labels: size/XL, lgtm, approved, dco-signoff: yes

#1024 KKP: Update the Supported Kubernetes versions
  content/kubermatic/master/architecture/support_policy/supported_versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1027 Update documentation for KKP on single node
  content/kubermatic/master/installation/install_kkp_on_node/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_on_node/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1028 Add documentation for KKP_DNS in KKP for single node
  content/kubermatic/master/installation/install_kkp_on_node/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_on_node/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes
