Repository kubermatic/docs, pull requests merged in 2022-09, with the labels that each got.

#1199 Add upgrade guide KKP 2.20 to 2.21
  content/kubermatic/master/architecture/supported-providers/kubevirt/kubevirt.en.md
  content/kubermatic/master/tutorials-howtos/upgrading/_index.en.md
  content/kubermatic/master/tutorials-howtos/upgrading/upgrade-from-2.20-to-2.21/_index.en.md
  content/kubermatic/v2.21/architecture/supported-providers/kubevirt/kubevirt.en.md
  content/kubermatic/v2.21/tutorials-howtos/upgrading/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/upgrading/upgrade-from-2.20-to-2.21/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1200 Fix some broken internal links on some pages
  content/kubermatic/master/tutorials-howtos/CCM-migration/_index.en.md
  content/kubermatic/master/tutorials-howtos/KKP-autoscaler/_index.en.md
  content/kubermatic/master/tutorials-howtos/applications/_index.en.md
  content/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/CCM-migration/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/KKP-autoscaler/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/applications/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/applications/add-applications-to-cluster/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/applications/add-applications-to-cluster/application_section.png
  content/kubermatic/v2.21/tutorials-howtos/applications/add-applications-to-cluster/application_settings.png
  content/kubermatic/v2.21/tutorials-howtos/applications/add-applications-to-cluster/application_status.png
  content/kubermatic/v2.21/tutorials-howtos/applications/add-applications-to-cluster/application_values.png
  content/kubermatic/v2.21/tutorials-howtos/applications/add-applications-to-cluster/applications_flow_in_cluster_wizard.png
  content/kubermatic/v2.21/tutorials-howtos/applications/add-applications-to-cluster/save_to_cluster_template.png
  content/kubermatic/v2.21/tutorials-howtos/applications/application-catalogue.png
  static/img/kubermatic/common/applications/application-catalogue.png
  static/img/kubermatic/common/applications/application_section.png
  static/img/kubermatic/common/applications/application_settings.png
  static/img/kubermatic/common/applications/application_status.png
  static/img/kubermatic/common/applications/application_values.png
  static/img/kubermatic/common/applications/applications_flow_in_cluster_wizard.png
  static/img/kubermatic/common/applications/save_to_cluster_template.png
  themes/kubermatic-docs/layouts/_default/_markup/render-image.html
Labels: lgtm, approved, size/M, dco-signoff: yes

#1201 Update documentation for using custom OSPs with KubeOne
  _content/operatingsystemmanager/v1.0/guides/customize-operating-system-profile/_index.en.md
  content/kubeone/master/architecture/operating-system-manager/usage/_index.en.md
  content/kubeone/v1.5/architecture/operating-system-manager/usage/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1203 Update CCM migration document with note on Azure
  content/kubermatic/master/tutorials-howtos/CCM-migration/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/CCM-migration/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1204 Minor dual-stack links update
  content/kubermatic/master/tutorials-howtos/networking/dual-stack/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/networking/dual-stack/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1206 Fix broken images
  content/kubeone/master/tutorials/creating-clusters-baremetal/_index.en.md
  content/kubeone/master/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.5/tutorials/creating-clusters-baremetal/_index.en.md
  content/kubeone/v1.5/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.5/tutorials/creating-clusters/architecture.png
  content/kubermatic/master/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  layouts/_default/home.search.json
  static/img/kubeone/common/creating-clusters/architecture.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1207 Improve handling content pages without versions
  layouts/_default/home.redirects
  layouts/index.html
Labels: lgtm, approved, size/S, dco-signoff: yes

#1209 Document known issues for KKP upgrade from 2.20 to 2.21
  content/kubermatic/master/tutorials-howtos/upgrading/upgrade-from-2.20-to-2.21/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/upgrading/upgrade-from-2.20-to-2.21/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1208 Update logo for OSM
  _content/operatingsystemmanager/master/img/operating-system-manager-logo.png
  _content/operatingsystemmanager/v1.0/img/operating-system-manager-logo.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1214 fix runbook script for yq4
  data/kubermatic/master/runbook.json
  hack/convert-runbook.sh
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1215 Update KKP docs based on the recent feedback
  content/kubermatic/master/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/master/tutorials-howtos/upgrading/upgrade-from-2.18-to-2.19/_index.en.md
  content/kubermatic/master/tutorials-howtos/upgrading/upgrade-from-2.19-to-2.20/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1212 Update status of KubeOne 1.5 known issues as of 2022-09-22
  content/kubeone/master/known-issues/_index.en.md
  content/kubeone/v1.5/known-issues/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes
