Repository kubermatic/docs, pull requests merged in 2022-04, with the labels that each got.

#1031 KubeOne: document how to monitor and recover etcd ring
  content/kubeone/master/guides/etcd_corruption/_index.en.md
  content/kubeone/v1.4/guides/etcd_corruption/_index.en.md
Labels: size/XL, lgtm, approved, dco-signoff: yes

#1032 Reference correct secret for backup/restore S3 credentials
  content/kubermatic/v2.18/cheat_sheets/etcd/backup-and-restore/_index.en.md
  content/kubermatic/v2.19/cheat_sheets/etcd/backup-and-restore/_index.en.md
  content/kubermatic/v2.20/cheat_sheets/etcd/backup-and-restore/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1029 Synchronize OWNERS_ALIASES file with Github teams
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, size/M, dco-signoff: yes

#1033 Naveen
  content/kubermatic/v2.18/architecture/concept/KKP vs kubeone/_index.en.md
  content/kubermatic/v2.18/architecture/monitoring_logging_alerting/_index.en.md
  content/kubermatic/v2.18/architecture/monitoring_logging_alerting/master_seed/_index.en.md
  content/kubermatic/v2.18/architecture/monitoring_logging_alerting/user_cluster/_index.en.md
  content/kubermatic/v2.18/architecture/predefined_roles/_index.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/AWS/aws.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/azure/azure.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/google_cloud/gcp.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/kubevirt/kubevirt.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/v2.18/tutorials_howtos/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/admin_panel/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/admin_panel/administrators/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/admin_panel/backup_buckets/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/admin_panel/cluster_settings/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/admin_panel/custom_links/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/admin_panel/dynamic_datacenters_management/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/admin_panel/opa_constraint_templates/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/admin_panel/opa_default_constraints/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/admin_panel/presets_management/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/presets/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/user_settings/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/user_settings/user_ssh_key_agent/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/metering/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/project_and_cluster_management/_index.en.md
Labels: lgtm, ok-to-test, approved, size/S, dco-signoff: yes

#1043 fix default ClusterTemplate example
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/cluster_defaulting/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/project_and_cluster_management/cluster_defaulting/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1036 Added Use case for KKP - Quick Start Guide
  content/kubermatic/master/installation/install_kkp_on_node/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_on_node/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1046 Attempt to fix automatic sync of CRD reference
  hack/crd-ref-docs.yaml
  hack/render-crds.sh
Labels: lgtm, approved, size/M, dco-signoff: yes

#1048 Remove 'rm' no longer necessary in hack/update-crds.sh
  hack/render-crds.sh
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1047 update kubevirt docs
  content/kubermatic/master/architecture/support_policy/provider_support_matrix/kubevirt/kubevirt.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1049 Enhance documentation for expose strategies
  content/kubermatic/master/tutorials_howtos/networking/expose_strategies/_index.en.md
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/seed_cluster/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/networking/expose_strategies/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/project_and_cluster_management/seed_cluster/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1050 Describe Metering configuration via Seed
  content/kubermatic/master/tutorials_howtos/metering/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1056 Make quick start documentation compatible with macOS
  content/kubermatic/master/installation/install_kkp_on_node/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_on_node/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1058 Kubeone: Update policy required for machine-controller on AWS
  content/kubeone/master/architecture/requirements/machine_controller/aws/aws.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/aws/aws.en.md
  content/kubeone/v1.4/architecture/requirements/machine_controller/aws/aws.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1060 Minor corrections to the Cluster Template documentation
  content/kubermatic/master/architecture/concept/kkp-concepts/cluster_templates/_index.en.md
  content/kubermatic/master/tutorials_howtos/cluster_templates/_index.en.md
  content/kubermatic/v2.18/guides/cluster_templates/_index.en.md
  content/kubermatic/v2.19/architecture/concept/kkp-concepts/cluster_templates/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/cluster_templates/_index.en.md
  content/kubermatic/v2.20/architecture/concept/kkp-concepts/cluster_templates/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/cluster_templates/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1059 update kubevirt monitoring doc
  content/kubermatic/master/architecture/support_policy/provider_support_matrix/kubevirt/kubevirt.en.md
  static/img/kubermatic/master/monitoring/kubevirt/grafana.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1057 Add KubeOne support policy
  content/kubeone/master/architecture/support_policy/_index.en.md
  content/kubeone/master/architecture/support_policy/supported_versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes
