Repository kubermatic/docs, pull requests merged in 2022-01, with the labels that each got.

#872 Document periodic cloud reconciliation
  content/kubermatic/master/architecture/support_policy/provider_support_matrix/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#886 Update admission plugin docs and add EventRateLimit
  content/kubermatic/master/architecture/concept/kkp-concepts/admission_plugins/_index.en.md
  content/kubermatic/master/tutorials_howtos/admission_plugins/_index.en.md
  static/img/kubermatic/master/ui/admission_plugin_configuration_eventratelimit.png
  static/img/kubermatic/master/ui/admission_plugins.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#889 Use empty map for datacenters example in Seed installation
  content/kubermatic/master/installation/install_kkp_CE/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.16/installation/add_seed_cluster/_index.en.md
  content/kubermatic/v2.16/installation/add_seed_cluster_ee/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.17/guides/installation/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_EE/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#891 Add upgrade notes for 2.19 - helm charts
  content/kubermatic/master/tutorials_howtos/upgrading/upgrade_from_2.18_to_2.19/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#893 Fixed CRDs path provided for Kubermatic components deployment in the Seed Cluster.
  content/kubermatic/master/installation/install_kkp_CE/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE/add_seed_cluster_EE/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_CE/_index.en.md
  content/kubermatic/v2.18/guides/installation/add_seed_cluster_EE/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#895 Add Nutanix support to the KubeOne compatibility matrix
  content/kubeone/master/architecture/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#888 Add documentation for AWS assume role feature
  content/kubermatic/master/tutorials_howtos/aws_assume_role/_index.en.md
  static/img/kubermatic/master/tutorials/aws_assume_role_sequence_diagram.png
  static/img/kubermatic/master/tutorials/aws_assume_role_wizard.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#898 Update KKP Networking documentation
  content/kubermatic/master/architecture/concept/kkp-concepts/kkp_networking/cluster_network/_index.en.md
  content/kubermatic/master/installation/install_kkp_CE/_index.en.md
  content/kubermatic/master/installation/install_kkp_CE/add_seed_cluster_CE/_index.en.md
  content/kubermatic/master/installation/install_kkp_EE/add_seed_cluster_EE/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/apiserver_policies/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/cni_cluster_network/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/expose_strategies/_index.en.md
  content/kubermatic/master/tutorials_howtos/networking/proxy_whitelisting/_index.en.md
  content/kubermatic/master/tutorials_howtos/project_and_cluster_management/_index.en.md
  static/img/kubermatic/master/guides/networking/networking_ui.png
  static/img/kubermatic/master/tutorials/networking/ui_addon_hubble.png
  static/img/kubermatic/master/tutorials/networking/ui_addons.png
  static/img/kubermatic/master/tutorials/networking/ui_cluster_cni.png
  static/img/kubermatic/master/tutorials/networking/ui_cluster_dialog_konnectivity.png
  static/img/kubermatic/master/tutorials/networking/ui_cluster_konnectivity.png
  static/img/kubermatic/master/tutorials/networking/ui_cluster_networking.png
  static/img/kubermatic/master/tutorials/networking/ui_cni_upgrade_available.png
  static/img/kubermatic/master/tutorials/networking/ui_cni_upgrade_dialog.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#897 external cluster documentation
  content/kubermatic/master/tutorials_howtos/external_clusters/_index.en.md
  content/kubermatic/master/tutorials_howtos/external_clusters/aks/_index.en.md
  content/kubermatic/master/tutorials_howtos/external_clusters/eks/_index.en.md
  content/kubermatic/master/tutorials_howtos/external_clusters/gke/_index.en.md
  static/img/kubermatic/master/tutorials/external_clusters/add_external_cluster.png
  static/img/kubermatic/master/tutorials/external_clusters/gke_credentials.png
  static/img/kubermatic/master/tutorials/external_clusters/gke_details.png
  static/img/kubermatic/master/tutorials/external_clusters/gke_machine_deployments.png
  static/img/kubermatic/master/tutorials/external_clusters/select_gke_cluster.png
  static/img/kubermatic/master/tutorials/external_clusters/update_gke_md.png
  static/img/kubermatic/master/tutorials/external_clusters/upgrade_gke.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#899 Enhance documentation for upgrading from v2.18 to v2.19
  content/kubermatic/master/tutorials_howtos/upgrading/upgrade_from_2.18_to_2.19/_index.en.md
  content/kubermatic/master/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#904 Add information about changed ingress annotations.
  content/kubermatic/master/tutorials_howtos/upgrading/upgrade_from_2.18_to_2.19/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#896 Add Nutanix to the KubeOne Getting Started tutorial
  content/kubeone/master/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_baremetal/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#906 Update the KubeOne docs to use the v1beta2 API instead of v1beta1
  content/kubeone/master/examples/addons_calico_vxlan/_index.en.md
  content/kubeone/master/guides/addons/_index.en.md
  content/kubeone/master/guides/autoscaler_addon/_index.en.md
  content/kubeone/master/guides/ccm_csi_migration/_index.en.md
  content/kubeone/master/guides/containerd_migration/_index.en.md
  content/kubeone/master/guides/encryption_providers/_index.en.md
  content/kubeone/master/guides/manual_cluster_recovery/_index.en.md
  content/kubeone/master/guides/proxy/_index.en.md
  content/kubeone/master/guides/registry_configuration/_index.en.md
  content/kubeone/master/tutorials/creating_clusters/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_oidc/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#881 Mark Amazon EKS-D support as removed
  content/kubeone/master/tutorials/creating_clusters_eks_d/_index.en.md
  content/kubeone/master/tutorials/creating_clusters_eks_d/architecture.png
  content/kubeone/master/tutorials/creating_clusters_eks_d/demo_thumbnail.jpg
  content/kubeone/v1.3/tutorials/creating_clusters_eks_d/_index.en.md
Labels: size/XL, lgtm, approved, dco-signoff: yes

#913 Enhance Konnectivity documentation
  content/kubermatic/master/tutorials_howtos/networking/cni_cluster_network/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#912 updated OPA docs, removing rawJSON references
  content/kubermatic/master/tutorials_howtos/OPA_integration/OPA_integration_Via_UI/_index.en.md
  content/kubermatic/master/tutorials_howtos/OPA_integration/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#882 Update kubevirt storage requirements
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/kubevirt/kubevirt.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#918 Default backup dest
  content/kubermatic/master/tutorials_howtos/administration/admin_panel/backup_buckets/_index.en.md
  static/img/kubermatic/master/tutorials/backups/add_backup_destination.png
  static/img/kubermatic/master/tutorials/backups/set_backup_dest_as_default.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#910 External Cluster AKS and EKS Guide
  content/kubermatic/master/tutorials_howtos/external_clusters/_index.en.md
  content/kubermatic/master/tutorials_howtos/external_clusters/aks/_index.en.md
  content/kubermatic/master/tutorials_howtos/external_clusters/eks/_index.en.md
  content/kubermatic/master/tutorials_howtos/external_clusters/gke/_index.en.md
  static/img/kubermatic/master/tutorials/external_clusters/aks_credentials.png
  static/img/kubermatic/master/tutorials/external_clusters/aks_details.png
  static/img/kubermatic/master/tutorials/external_clusters/aks_machine_deployments.png
  static/img/kubermatic/master/tutorials/external_clusters/aks_reconcile.png
  static/img/kubermatic/master/tutorials/external_clusters/aks_stopped.png
  static/img/kubermatic/master/tutorials/external_clusters/aks_stopping.png
  static/img/kubermatic/master/tutorials/external_clusters/connect.png
  static/img/kubermatic/master/tutorials/external_clusters/custom_cluster_credentials.png
  static/img/kubermatic/master/tutorials/external_clusters/custom_details.png
  static/img/kubermatic/master/tutorials/external_clusters/delete_status.png
  static/img/kubermatic/master/tutorials/external_clusters/disconnect_deleted_cluster.png
  static/img/kubermatic/master/tutorials/external_clusters/edit_md.png
  static/img/kubermatic/master/tutorials/external_clusters/eks.png
  static/img/kubermatic/master/tutorials/external_clusters/eks_credentials.png
  static/img/kubermatic/master/tutorials/external_clusters/eks_details.png
  static/img/kubermatic/master/tutorials/external_clusters/eks_machine_deployments.png
  static/img/kubermatic/master/tutorials/external_clusters/eks_reconciling.png
  static/img/kubermatic/master/tutorials/external_clusters/events.png
  static/img/kubermatic/master/tutorials/external_clusters/provisioning_status.png
  static/img/kubermatic/master/tutorials/external_clusters/select_aks_cluster.png
  static/img/kubermatic/master/tutorials/external_clusters/select_eks_cluster.png
  static/img/kubermatic/master/tutorials/external_clusters/update_aks_md.png
  static/img/kubermatic/master/tutorials/external_clusters/update_eks_md.png
  static/img/kubermatic/master/tutorials/external_clusters/update_inprogress.png
  static/img/kubermatic/master/tutorials/external_clusters/upgrade_aks.png
  static/img/kubermatic/master/tutorials/external_clusters/upgrade_eks.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#919 Add compatibility matrix for cilium
  content/kubermatic/master/tutorials_howtos/networking/cni_cluster_network/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#922 cni cilium: add compatibililty matix for ipvs proxy mode
  content/kubermatic/master/tutorials_howtos/networking/cni_cluster_network/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#861 Update etcd-launcher docs to include changes on KKP master
  content/kubermatic/master/cheat_sheets/etcd/etcd-launcher/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#923 Add information about cert-manager post-install configuration
  content/kubermatic/master/installation/install_kkp_CE/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#924 Add table with support for cilium w/iptables on infra providers
  content/kubermatic/master/tutorials_howtos/networking/cni_cluster_network/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#914 Add documentation for operating system manager
  README.md
  content/kubermatic/master/tutorials_howtos/operating_system_manager/_index.en.md
  content/kubermatic/master/tutorials_howtos/operating_system_manager/usage/_index.en.md
  static/img/kubermatic/master/tutorials/operating_system_manager/architecture.png
  static/img/kubermatic/master/tutorials/operating_system_manager/osm_dashboard.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#925 Backport OSM documentation to 2.19
  content/kubermatic/v2.19/tutorials_howtos/operating_system_manager/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/operating_system_manager/usage/_index.en.md
  static/img/kubermatic/v2.19/tutorials/operating_system_manager/architecture.png
  static/img/kubermatic/v2.19/tutorials/operating_system_manager/osm_dashboard.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#926 Add ahmedwaleedmalik to team-lifecycle
  OWNERS_ALIASES
Labels: lgtm, size/XS, approved, dco-signoff: yes

#927 Add deprecation notice to dynamic kubelet configuration
  content/kubermatic/master/tutorials_howtos/KKP_configuration/dynamic_kubelet_config/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/KKP_configuration/dynamic_kubelet_config/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#928 Update swagger.json for 2.17, 2.18, 2.19 and master
  content/kubermatic/master/data/swagger.json
  content/kubermatic/master/references/rest_api_reference/swagger.json
  content/kubermatic/v2.17/data/swagger.json
  content/kubermatic/v2.17/references/rest_api_reference/swagger.json
  content/kubermatic/v2.18/data/swagger.json
  content/kubermatic/v2.18/references/rest_api_reference/swagger.json
  content/kubermatic/v2.19/data/swagger.json
  content/kubermatic/v2.19/references/rest_api_reference/swagger.json
Labels: lgtm, size/XXL, approved, dco-signoff: yes
