Repository kubermatic/docs, pull requests merged in 2023-09, with the labels that each got.

#1512 osm: replace screenshot with the custom OSP's diff as snippet
  content/operatingsystemmanager/data/osp-ubuntu-swap-enabled.yaml
  content/operatingsystemmanager/guides/customize-operating-system-profile/_index.en.md
  static/img/operatingsystemmanager/master/osp-ubuntu-swap-enabled.png
Labels: lgtm, ok-to-test, approved, size/M, dco-signoff: yes

#1517 Document parameter for parallel CCM service reconciliation
  content/kubeone/main/guides/addons/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1522 Correct support matrix for KubeOne 1.6
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/v1.7/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1523 Ubuntu cloud image issue in VMware Cloud Director provider on KKP
  content/kubermatic/main/architecture/known-issues/_index.en.md
  content/kubermatic/main/architecture/supported-providers/vmware-cloud-director/vmware-cloud-director.md
  content/kubermatic/v2.23/architecture/known-issues/_index.en.md
  content/kubermatic/v2.23/architecture/supported-providers/vmware-cloud-director/vmware-cloud-director.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1524 Add missing OIDC settings in UI config
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1525 Mark user cluster MLA as optional, not alpha
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1516 fix KKP addon configuration snippets
  content/kubermatic/main/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.21/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.22/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.23/architecture/concept/kkp-concepts/addons/_index.en.md
Labels: size/XL, lgtm, approved, dco-signoff: yes

#1526 Fixed OIDC UI Config for missing comma
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes
