Repository kubermatic/docs, pull requests merged in 2023-01, with the labels that each got.

#1290 Drop docker related configurations from sample OSP
  content/operatingsystemmanager/compatibility/_index.en.md
  content/operatingsystemmanager/data/osp-ubuntu-swap-enabled.yaml
  content/operatingsystemmanager/guides/osm-configuration/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1288 Consolidate and update KKP installation instructions
  content/kubermatic/main/architecture/concept/kkp-concepts/resource-quotas/_index.en.md
  content/kubermatic/main/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/main/installation/install-HA-kubernetes/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE-on-AWS/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE-on-AWS/add-seed-cluster-ce-on-aws/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE-on-Azure/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE-on-Azure/add-seed-cluster-CE-on-Azure/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE-on-GCP/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE-on-GCP/add-seed-cluster-CE-on-GCP/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE-on-vSphere/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE-on-vSphere/add-seed-cluster-ce-on-vsphere/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE/add-seed-cluster-CE/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE-on-AWS/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE-on-AWS/add-seed-cluster-ee-on-aws/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE-on-Azure/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE-on-Azure/add-seed-cluster-ee-on-azure/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE-on-GCP/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE-on-GCP/add-seed-cluster-ee-on-gcp/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE-on-vSphere/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE-on-vSphere/add-seed-cluster-ee-on-vsphere/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE/add-seed-cluster-EE/_index.en.md
  content/kubermatic/main/installation/install-kkp-on-node/_index.en.md
  content/kubermatic/main/installation/offline-mode/_index.en.md
  content/kubermatic/main/installation/start-kkp/_index.en.md
  content/kubermatic/main/installation/start-kkp/cheat-sheets/_index.en.md
  content/kubermatic/main/installation/start-kkp/cheat-sheets/access-to-cluster/_index.en.md
  content/kubermatic/main/installation/start-kkp/cheat-sheets/declarative-configurations/_index.en.md
  content/kubermatic/main/installation/start-kkp/cheat-sheets/troubleshoot-pipeline/_index.en.md
  content/kubermatic/main/installation/start-kkp/cheat-sheets/troubleshoot-pipeline/failed_pipeline.png
  content/kubermatic/main/installation/start-kkp/cheat-sheets/validate-cluster-health/_index.en.md
  content/kubermatic/main/installation/start-kkp/cheat-sheets/work-with-secrets/_index.en.md
  content/kubermatic/main/installation/start-kkp/concepts/_index.en.md
  content/kubermatic/main/installation/start-kkp/concepts/pipeline-definition/_index.en.md
  content/kubermatic/main/installation/start-kkp/concepts/pipeline-definition/pipeline.png
  content/kubermatic/main/installation/start-kkp/flow.png
  content/kubermatic/main/installation/start-kkp/guides/_index.en.md
  content/kubermatic/main/installation/start-kkp/guides/explore-content/_index.en.md
  content/kubermatic/main/installation/start-kkp/guides/explore-content/example-secrets.png
  content/kubermatic/main/installation/start-kkp/guides/setup-repository/_index.en.md
  content/kubermatic/main/installation/start-kkp/guides/setup-repository/kkp-login.png
  content/kubermatic/main/installation/start-kkp/guides/setup-repository/kkp-ui.png
  content/kubermatic/main/installation/start-kkp/guides/setup-repository/pipeline.png
  content/kubermatic/main/installation/start-kkp/guides/wizard/1.png
  content/kubermatic/main/installation/start-kkp/guides/wizard/2.png
  content/kubermatic/main/installation/start-kkp/guides/wizard/3.png
  content/kubermatic/main/installation/start-kkp/guides/wizard/4.png
  content/kubermatic/main/installation/start-kkp/guides/wizard/5.png
  content/kubermatic/main/installation/start-kkp/guides/wizard/6.png
  content/kubermatic/main/installation/start-kkp/guides/wizard/_index.en.md
  content/kubermatic/main/installation/start-kkp/guides/wizard/congrats.png
  content/kubermatic/main/installation/start-kkp/guides/wizard/welcome.png
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1285 default project resource quota docs
  content/kubermatic/main/architecture/concept/kkp-concepts/resource-quotas/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1293 Remove references to the KonnectivityService feature gate
  content/kubermatic/main/tutorials-howtos/networking/cni-cluster-network/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1295 Minor documentation improvements for wording and capitalisation
  content/kubermatic/main/_index.en.md
  content/kubermatic/main/architecture/_index.en.md
  content/kubermatic/main/installation/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE/_index.en.md
  content/kubermatic/main/tutorials-howtos/KKP-autoscaler/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1296 Brighten up inline code highlighting
  content/kubermatic/main/_index.en.md
  themes/kubermatic-docs/assets/scss/_theme-kubermatic.scss
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1297 Add `oidc_logout_url` in OIDC provider configuration docs
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1299 Add release cycles to support policy document
  content/kubermatic/main/architecture/support-policy/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1300 Remove Kubernetes 1.23 as supported for KubeOne 1.6
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1307 Update mirror-images documentation to include new capabilities
  content/kubermatic/main/installation/offline-mode/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1311 KubeVirt remove Technology Preview and StorageClass init based on Seed
  content/kubermatic/main/architecture/supported-providers/_index.en.md
  content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1313 Update main page
  config.toml
  content/_index.md
  data/products.yaml
  layouts/index.html
  static/img/main-background.svg
  themes/kubermatic-docs/assets/scss/_home.scss
Labels: lgtm, size/L, approved, dco-signoff: yes

#1309 Update docs for API Server Allowed Source IP Ranges
  content/kubermatic/main/tutorials-howtos/networking/apiserver-policies/_index.en.md
  static/img/kubermatic/main/tutorials/networking/cluster_details_allowed_ip_ranges.png
  static/img/kubermatic/main/tutorials/networking/network_config_allowed_ip_ranges.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1312 Update KKP component versions for all supported versions
  content/kubermatic/v2.19/architecture/support_policy/KKP_components_versioning/_index.en.md
  content/kubermatic/v2.20/architecture/support_policy/KKP_components_versioning/_index.en.md
  content/kubermatic/v2.21/architecture/compatibility/KKP-components-versioning/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1317 Update contribution links and slightly improve landing page language
  content/_index.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1298 Remove references TunnelingExposeStrategy feature gate, make the strategy GA
  content/kubermatic/main/tutorials-howtos/networking/expose-strategies/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1314 Update headers to be more consistent in language
  content/kubermatic/main/architecture/concept/kkp-concepts/kkp-security/pod-security-policy/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/kkp-security/securing-system-services/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/resource-quotas/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/service-account/service-account-token-projection/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/service-account/using-service-account/_index.en.md
  content/kubermatic/main/architecture/known-issues/_index.en.md
  content/kubermatic/main/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/main/architecture/role-based-access-control/_index.en.md
  content/kubermatic/main/architecture/supported-providers/AWS/aws.en.md
  content/kubermatic/main/architecture/supported-providers/google-cloud/gcp.en.md
  content/kubermatic/main/architecture/supported-providers/vSphere/vSphere.en.md
  content/kubermatic/main/cheat-sheets/changelog/_index.en.md
  content/kubermatic/main/cheat-sheets/debugging/_index.en.md
  content/kubermatic/main/cheat-sheets/etcd/backup-and-restore/_index.en.md
  content/kubermatic/main/cheat-sheets/etcd/etcd-launcher/_index.en.md
  content/kubermatic/main/cheat-sheets/etcd/legacy-restore/_index.en.md
  content/kubermatic/main/cheat-sheets/rollout-machinedeployment/_index.en.md
  content/kubermatic/main/cheat-sheets/vsphere-cluster-id/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE/_index.en.md
  content/kubermatic/main/installation/install-kkp-on-node/_index.en.md
  content/kubermatic/main/tutorials-howtos/CCM-migration/CCM-migration-via-UI/_index.en.md
  content/kubermatic/main/tutorials-howtos/KKP-autoscaler/_index.en.md
  content/kubermatic/main/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/share-clusters-via-delegated-OIDC-authentication/_index.en.md
  content/kubermatic/main/tutorials-howtos/OPA-integration/OPA-integration-Via-UI/_index.en.md
  content/kubermatic/main/tutorials-howtos/OPA-integration/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/backup-buckets/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/opa-default-constraints/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/presets-management/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/dynamic-data-centers/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/kkp-user/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/user-settings/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/user-settings/user-ssh-key-agent/_index.en.md
  content/kubermatic/main/tutorials-howtos/admission-plugins/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/main/tutorials-howtos/audit-logging/_index.en.md
  content/kubermatic/main/tutorials-howtos/aws-assume-role/_index.en.md
  content/kubermatic/main/tutorials-howtos/cluster-templates/_index.en.md
  content/kubermatic/main/tutorials-howtos/external-clusters/aks/create-aks/_index.en.md
  content/kubermatic/main/tutorials-howtos/external-clusters/eks/create-eks/_index.en.md
  content/kubermatic/main/tutorials-howtos/external-clusters/gke/create-gke/_index.en.md
  content/kubermatic/main/tutorials-howtos/manage-worker's-node/_index.en.md
  content/kubermatic/main/tutorials-howtos/manage-worker's-node/via-UI/_index.en.md
  content/kubermatic/main/tutorials-howtos/metering/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/customization/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/main/tutorials-howtos/networking/cni-migration/_index.en.md
  content/kubermatic/main/tutorials-howtos/networking/multus/_index.en.md
  content/kubermatic/main/tutorials-howtos/networking/proxy-whitelisting/_index.en.md
  content/kubermatic/main/tutorials-howtos/project-and-cluster-management/_index.en.md
  content/kubermatic/main/tutorials-howtos/project-and-cluster-management/cluster-defaulting/_index.en.md
  content/kubermatic/main/tutorials-howtos/telemetry/_index.en.md
Labels: size/XL, lgtm, approved, dco-signoff: yes

#1316 Update etcd Launcher docs as it is enabled by default now
  content/kubermatic/main/cheat-sheets/etcd/etcd-launcher/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1308 OPA integration: adds doc about enforcementAction
  content/kubermatic/main/tutorials-howtos/OPA-integration/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1310 Cluster rbac
  content/kubermatic/main/architecture/role-based-access-control/_index.en.md
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/share-clusters-via-delegated-OIDC-authentication/_index.en.md
  content/kubermatic/main/tutorials-howtos/cluster-rbac/_index.en.md
  static/img/kubermatic/main/ui/rbac.png
  static/img/kubermatic/main/ui/rbac_add.png
  static/img/kubermatic/main/ui/rbac_group_binding.png
  static/img/kubermatic/main/ui/rbac_group_view.png
  static/img/kubermatic/main/ui/rbac_sa_binding.png
  static/img/kubermatic/main/ui/rbac_sa_creation.png
  static/img/kubermatic/main/ui/rbac_sa_download_kc.png
  static/img/kubermatic/main/ui/rbac_sa_view.png
  static/img/kubermatic/main/ui/rbac_user_binding.png
  static/img/kubermatic/main/ui/rbac_user_view.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1318 Update Kubernetes version support matrix
  content/kubermatic/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubermatic/v2.21/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1322 Replace Packet with Equinix Metal for KubeOne
  content/kubeone/main/architecture/supported-providers/_index.en.md
  content/kubeone/main/guides/credentials/_index.md
  content/kubeone/main/tutorials/creating-clusters-baremetal/_index.en.md
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.3/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.4/architecture/compatibility/_index.en.md
  content/kubeone/v1.4/guides/credentials/_index.md
  content/kubeone/v1.4/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters_baremetal/_index.en.md
  content/kubeone/v1.5/architecture/supported-providers/_index.en.md
  content/kubeone/v1.5/guides/credentials/_index.md
  content/kubeone/v1.5/tutorials/creating-clusters-baremetal/_index.en.md
  content/kubeone/v1.5/tutorials/creating-clusters/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1324 Add Enterprise Edition page to Architecture menu
  content/kubermatic/main/architecture/enterprise-edition/_index.md
Labels: lgtm, approved, size/S, dco-signoff: yes
