Repository kubermatic/docs, pull requests merged in 2023-02, with the labels that each got.

#1326 Add docs for Web Terminal feature
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/interface/_index.en.md
  content/kubermatic/main/tutorials-howtos/project-and-cluster-management/web-terminal/_index.en.md
  static/img/kubermatic/main/ui/enable_web_terminal.png
  static/img/kubermatic/main/ui/interface.png
  static/img/kubermatic/main/ui/web_terminal.png
  static/img/kubermatic/main/ui/web_terminal_button.png
  static/img/kubermatic/main/ui/web_terminal_sequence_diagram.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1325 FIx copy-paste issue in Konnectivity docs for 2.21
  content/kubermatic/v2.21/tutorials-howtos/networking/cni-cluster-network/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1332 add documentation for vsphere tagging mechanism
  content/kubermatic/main/architecture/supported-providers/_index.en.md
  content/kubermatic/main/architecture/supported-providers/vSphere/vSphere.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1331 Fix brew install command in KKP install tutorials
  content/kubermatic/main/installation/install-kkp-CE/_index.en.md
  content/kubermatic/v2.14/installation/install_kubermatic/_index.en.md
  content/kubermatic/v2.14/installation/install_kubermatic_ee/_index.en.md
  content/kubermatic/v2.15/installation/install_kubermatic/_index.en.md
  content/kubermatic/v2.16/installation/install_kubermatic/_index.en.md
  content/kubermatic/v2.17/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.18/guides/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.19/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_AWS/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_Azure/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_GCP/_index.en.md
  content/kubermatic/v2.20/installation/install_kkp_CE_on_vSphere/_index.en.md
  content/kubermatic/v2.21/installation/install-kkp-CE-on-AWS/_index.en.md
  content/kubermatic/v2.21/installation/install-kkp-CE-on-Azure/_index.en.md
  content/kubermatic/v2.21/installation/install-kkp-CE-on-GCP/_index.en.md
  content/kubermatic/v2.21/installation/install-kkp-CE-on-vSphere/_index.en.md
  content/kubermatic/v2.21/installation/install-kkp-CE/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1335 Documentation for editing cluster templates
  content/kubermatic/main/tutorials-howtos/cluster-templates/_index.en.md
  static/img/kubermatic/main/tutorials/cluster_template/actions.png
  static/img/kubermatic/main/tutorials/cluster_template/cluster_template_menu.png
  static/img/kubermatic/main/tutorials/cluster_template/create_cluster.png
  static/img/kubermatic/main/tutorials/cluster_template/create_from_cluster_wizard.png
  static/img/kubermatic/main/tutorials/cluster_template/create_from_clusters.png
  static/img/kubermatic/main/tutorials/cluster_template/delete_template.png
  static/img/kubermatic/main/tutorials/cluster_template/edit_cluster_template.png
  static/img/kubermatic/main/tutorials/cluster_template/edit_cluster_template_summary.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1336 Add troubleshooting section for Web Terminal
  content/kubermatic/main/tutorials-howtos/project-and-cluster-management/web-terminal/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1337 Add doc for new IPAMPool feature: exclusions
  content/kubermatic/main/tutorials-howtos/networking/ipam/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1340 Add share images for the products
  config.toml
  data/products.yaml
  static/img/Docs-KKP-share.jpg
  static/img/Docs-KubeCarrier-share.jpg
  static/img/Docs-KubeOne-share.jpg
  static/img/Docs-OSM-share.jpg
  themes/kubermatic-docs/layouts/partials/meta.html
  themes/kubermatic-docs/static/img/Kubermatic-share.jpg
  themes/kubermatic-docs/static/img/share-socials.jpg
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1339 Add MLA Architecture picture + add links to MLA subsections
  content/kubermatic/main/architecture/monitoring-logging-alerting/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/_index.en.md
  content/kubermatic/v2.20/architecture/monitoring_logging_alerting/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/monitoring_logging_alerting/_index.en.md
  content/kubermatic/v2.21/architecture/monitoring-logging-alerting/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/monitoring-logging-alerting/_index.en.md
  static/img/kubermatic/main/architecture/kkp-mla-architecture.png
  static/img/kubermatic/v2.20/architecture/kkp-mla-architecture.png
  static/img/kubermatic/v2.21/architecture/kkp-mla-architecture.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1342 mention AWS on CCM migration page
  content/kubermatic/main/tutorials-howtos/CCM-migration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1344 Add KubeVirt GA documentation
  content/kubermatic/main/architecture/supported-providers/_index.en.md
  content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
  static/img/kubermatic/main/architecture/supported-providers/kubevirt/architecture.png
  static/img/kubermatic/main/architecture/supported-providers/kubevirt/instance-type.png
  static/img/kubermatic/main/architecture/supported-providers/kubevirt/scheduling-form.png
Labels: size/XL, lgtm, approved, dco-signoff: yes

#1341 remove severely outdated tutorial e2e tests
  .gitignore
  tutorials-tests/LICENSE
  tutorials-tests/containers/cypress/utils/yamls/presets.yaml
  tutorials-tests/cypress.json
  tutorials-tests/cypress/integration/stories/tutorials.spec.ts
  tutorials-tests/cypress/pages/clusters.po.ts
  tutorials-tests/cypress/pages/cypress.json
  tutorials-tests/cypress/pages/dex.po.ts
  tutorials-tests/cypress/pages/login.po.ts
  tutorials-tests/cypress/pages/members.po.ts
  tutorials-tests/cypress/pages/node-deployment-details.po.ts
  tutorials-tests/cypress/pages/projects.po.ts
  tutorials-tests/cypress/pages/ssh-keys.po.ts
  tutorials-tests/cypress/pages/tutorial-projects.po.ts
  tutorials-tests/cypress/pages/wizard.po.ts
  tutorials-tests/cypress/plugins/cy-ts-preprocessor.js
  tutorials-tests/cypress/plugins/index.js
  tutorials-tests/cypress/support/commands.js
  tutorials-tests/cypress/support/index.js
  tutorials-tests/cypress/support/index.ts
  tutorials-tests/cypress/utils/auth.ts
  tutorials-tests/cypress/utils/condition.ts
  tutorials-tests/cypress/utils/member.ts
  tutorials-tests/cypress/utils/provider.ts
  tutorials-tests/cypress/utils/random.ts
  tutorials-tests/cypress/utils/wait.ts
  tutorials-tests/package-lock.json
  tutorials-tests/package.json
  tutorials-tests/proxy-local.conf.json
  tutorials-tests/proxy.conf.json
  tutorials-tests/tsconfig.json
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1346 Add a notice about migrating from the Tunneling expose strategy
  content/kubermatic/main/tutorials-howtos/networking/expose-strategies/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1348 Add some clarifications for expose strategy migration
  content/kubermatic/main/tutorials-howtos/networking/expose-strategies/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1347 Add note for removal of PodSecurityPolicy from Kubernetes v1.25
  content/kubermatic/main/tutorials-howtos/admission-plugins/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1345 Fix KubeVirt links
  content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1351 KubeOne: Update documentation for custom OSP usage
  content/kubeone/main/architecture/operating-system-manager/usage/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1352 KKP: Update docs for using custom OSPs
  content/kubeone/main/_index.en.md
  content/kubeone/main/architecture/compatibility/OS-support-matrix/_index.en.md
  content/kubeone/main/architecture/supported-providers/_index.en.md
  content/kubermatic/main/architecture/compatibility/OS-support-matrix/_index.en.md
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/kubermatic/main/tutorials-howtos/operating-system-manager/usage/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1323 update applications docs
  content/kubermatic/main/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-definition/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-installation/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/add-applications-to-cluster/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/add-remove-application-version/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/update-application/_index.en.md
  static/img/kubermatic/common/applications/applications_edit_icon.png
  static/img/kubermatic/common/applications/applications_edit_values.png
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1355 application: fix example of templateCredentials
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-definition/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1356 Document Ubuntu 22.04 support since KKP 2.21.2
  content/kubermatic/v2.21/architecture/compatibility/OS-support-matrix/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1359 remove ubuntu 18.04 from supported os
  content/kubermatic/main/architecture/compatibility/OS-support-matrix/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1354 Update OSM docs
  content/kubermatic/main/tutorials-howtos/operating-system-manager/_index.en.md
  content/operatingsystemmanager/architecture/_index.en.md
  static/img/kubermatic/main/tutorials/operating_system_manager/architecture.png
  static/img/operatingsystemmanager/master/osm-management-worker.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1360 applications: update doc with new enableDNS field
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-definition/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-installation/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1364 Documentation for updating OSPs
  content/kubermatic/main/tutorials-howtos/operating-system-manager/usage/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/operating-system-manager/usage/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1365 Update restrictions of the API Server Allowed Source IP Ranges feature
  content/kubermatic/main/tutorials-howtos/networking/apiserver-policies/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1363 Add KubeVirt migration steps
  content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
  static/img/kubermatic/main/architecture/supported-providers/kubevirt/mc-edit.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1366 KubeOne: Update kubernetes version in examples to v1.25.6
  content/kubeone/main/architecture/operating-system-manager/usage/_index.en.md
  content/kubeone/main/examples/addons-calico-vxlan/_index.en.md
  content/kubeone/main/guides/addons/_index.en.md
  content/kubeone/main/guides/autoscaler-addon/_index.en.md
  content/kubeone/main/guides/ccm-csi-migration/_index.en.md
  content/kubeone/main/guides/encryption-providers/_index.en.md
  content/kubeone/main/guides/mirror-registries/_index.en.md
  content/kubeone/main/guides/registry-configuration/_index.en.md
  content/kubeone/main/tutorials/creating-clusters-baremetal/_index.en.md
  content/kubeone/main/tutorials/creating-clusters-oidc/_index.en.md
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1368 kubermatic docs: Update Images for cluster templates
  static/img/kubermatic/main/tutorials/cluster_template/cluster_template_menu.png
  static/img/kubermatic/main/tutorials/cluster_template/create_cluster.png
  static/img/kubermatic/main/tutorials/cluster_template/delete_template.png
  static/img/kubermatic/main/tutorials/cluster_template/edit_cluster_template.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1367 kubermatic docs: Update Images for project-and-cluster-management docs
  content/kubermatic/main/tutorials-howtos/project-and-cluster-management/_index.en.md
  static/img/kubermatic/main/tutorials/add_machine_deployment.png
  static/img/kubermatic/main/tutorials/change_version.png
  static/img/kubermatic/main/tutorials/cluster_details_after_creation.png
  static/img/kubermatic/main/tutorials/cluster_details_overview.png
  static/img/kubermatic/main/tutorials/cluster_edit_menu.PNG
  static/img/kubermatic/main/tutorials/cluster_edit_menu.png
  static/img/kubermatic/main/tutorials/cluster_list.png
  static/img/kubermatic/main/tutorials/delete_cluster.png
  static/img/kubermatic/main/tutorials/delete_cluster_button.png
  static/img/kubermatic/main/tutorials/edit_cluster_dialog.png
  static/img/kubermatic/main/tutorials/machine_deployment_edit.png
  static/img/kubermatic/main/tutorials/machine_deployment_edit_dialog.png
  static/img/kubermatic/main/tutorials/project_delete.png
  static/img/kubermatic/main/tutorials/projects_overview.png
  static/img/kubermatic/main/tutorials/sshkeys_overview.png
  static/img/kubermatic/main/tutorials/upgrade_version.png
  static/img/kubermatic/main/tutorials/wizard_step_1.png
  static/img/kubermatic/main/tutorials/wizard_step_2.png
  static/img/kubermatic/main/tutorials/wizard_step_3.png
  static/img/kubermatic/main/tutorials/wizard_step_4.1.png
  static/img/kubermatic/main/tutorials/wizard_step_4.png
  static/img/kubermatic/main/tutorials/wizard_step_5.png
  static/img/kubermatic/main/tutorials/wizard_step_6.png
Labels: lgtm, size/XS, approved, dco-signoff: yes, KKP

#1369 kubermatic docs: Update Images for external clusters
  content/kubermatic/main/tutorials-howtos/external-clusters/_index.en.md
  static/img/kubermatic/main/tutorials/external_clusters/add_external_cluster.png
  static/img/kubermatic/main/tutorials/external_clusters/connect.png
  static/img/kubermatic/main/tutorials/external_clusters/create_external_cluster.png
  static/img/kubermatic/main/tutorials/external_clusters/custom_cluster_credentials.png
  static/img/kubermatic/main/tutorials/external_clusters/delete_disconnect_page.png
  static/img/kubermatic/main/tutorials/external_clusters/delete_external_cluster_dialog.png
  static/img/kubermatic/main/tutorials/external_clusters/disconnect.png
  static/img/kubermatic/main/tutorials/external_clusters/disconnect_externalcluster.png
  static/img/kubermatic/main/tutorials/external_clusters/disconnect_externalcluster_details_page.png
  static/img/kubermatic/main/tutorials/external_clusters/externalcluster_list.png
  static/img/kubermatic/main/tutorials/external_clusters/reconciling_status.png
  static/img/kubermatic/main/tutorials/external_clusters/running_status.png
Labels: lgtm, approved, size/S, dco-signoff: yes, KKP

#1343 Documenting Seed level OIDC provider configuration
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1370 update applications: failures counter is only incremented when spec.deployOptions.helm.atomic=true
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-installation/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1371 improve KKP GCP documentation a bit
  content/kubermatic/main/architecture/supported-providers/aws/aws.en.md
  content/kubermatic/main/architecture/supported-providers/azure/azure.en.md
  content/kubermatic/main/architecture/supported-providers/gcp/gcp.en.md
  content/kubermatic/main/architecture/supported-providers/google-cloud/gcp.en.md
  content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
  content/kubermatic/main/architecture/supported-providers/nutanix/nutanix.en.md
  content/kubermatic/main/architecture/supported-providers/vmware-cloud-director/vmware-cloud-director.md
  content/kubermatic/main/architecture/supported-providers/vsphere/vsphere.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1375 Change Gatekeeper version in docs
  content/kubermatic/main/architecture/compatibility/KKP-components-versioning/_index.en.md
  content/kubermatic/main/tutorials-howtos/OPA-integration/[Experimental]-OPA-Mutation/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1329 Update CNI docs with deploying Cilium CNI as a System Application
  content/kubermatic/main/tutorials-howtos/networking/cilium-cluster-mesh/_index.en.md
  content/kubermatic/main/tutorials-howtos/networking/cni-cluster-network/_index.en.md
  static/img/kubermatic/main/tutorials/networking/edit-cni-app-values.png
  static/img/kubermatic/main/tutorials/networking/edit-cni-app.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1373 kubermatic docs: Documenting for Seed Configuration
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/seed-configurations/_index.en.md
  static/img/kubermatic/main/tutorials/seed-configurations/seed_confgurations.png
  static/img/kubermatic/main/tutorials/seed-configurations/seed_confgurations_details.png
  static/img/kubermatic/main/tutorials/seed-configurations/seed_confgurations_provider_datacenters.png
Labels: lgtm, approved, size/S, dco-signoff: yes, KKP

#1378 Add manual for setting cluster autoscaler annotations with Dashboard
  content/kubermatic/main/tutorials-howtos/KKP-autoscaler/_index.en.md
  static/img/kubermatic/main/tutorials/create_autoscaler_annotations.png
  static/img/kubermatic/main/tutorials/edit_autoscaler_annotations.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1380 kubermatic docs: Update Images for external clusters
  content/kubermatic/main/tutorials-howtos/external-clusters/aks/create-aks/_index.en.md
  content/kubermatic/main/tutorials-howtos/external-clusters/eks/create-eks/_index.en.md
  content/kubermatic/main/tutorials-howtos/external-clusters/gke/_index.en.md
  static/img/kubermatic/main/tutorials/external_clusters/add_md.png
  static/img/kubermatic/main/tutorials/external_clusters/create_akspreset.png
  static/img/kubermatic/main/tutorials/external_clusters/create_ekspreset.png
  static/img/kubermatic/main/tutorials/external_clusters/create_gkepreset.png
  static/img/kubermatic/main/tutorials/external_clusters/external_cluster_page.png
  static/img/kubermatic/main/tutorials/external_clusters/provide_gkepreset_name.png
  static/img/kubermatic/main/tutorials/external_clusters/provider_presets.png
  static/img/kubermatic/main/tutorials/external_clusters/select_adminpanel.png
Labels: lgtm, approved, size/S, dco-signoff: yes, KKP

#1381 kubermatic docs: Update Images for Cluster Autoscaler docs
  content/kubermatic/main/tutorials-howtos/KKP-autoscaler/_index.en.md
  static/img/kubermatic/main/tutorials/add_autoscaler_addon.png
  static/img/kubermatic/main/tutorials/autoscaler_confirmation.png
  static/img/kubermatic/main/tutorials/cluster-autoscaler/add_autoscaler_addon.png
  static/img/kubermatic/main/tutorials/cluster-autoscaler/autoscaler_confirmation.png
  static/img/kubermatic/main/tutorials/cluster-autoscaler/create_autoscaler_annotations.png
  static/img/kubermatic/main/tutorials/cluster-autoscaler/delete_autoscaler.png
  static/img/kubermatic/main/tutorials/cluster-autoscaler/edit_autoscaler.png
  static/img/kubermatic/main/tutorials/cluster-autoscaler/edit_autoscaler_annotations.png
  static/img/kubermatic/main/tutorials/cluster-autoscaler/install_autoscaler.png
  static/img/kubermatic/main/tutorials/cluster-autoscaler/kkp_autoscaler_dashboard.png
  static/img/kubermatic/main/tutorials/cluster-autoscaler/select_autoscaler.png
  static/img/kubermatic/main/tutorials/delete_autoscaler.png
  static/img/kubermatic/main/tutorials/edit_autoscaler.png
  static/img/kubermatic/main/tutorials/install_autoscaler.png
  static/img/kubermatic/main/tutorials/kkp_autoscaler_dashboard.png
Labels: lgtm, approved, size/S, KKP

#1383 Copy skipped changes from main to v2.22
  content/kubermatic/v2.22/tutorials-howtos/KKP-autoscaler/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/administration/admin-panel/seed-configurations/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/external-clusters/aks/create-aks/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/external-clusters/eks/create-eks/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/external-clusters/gke/_index.en.md
  static/img/kubermatic/v2.22/tutorials/cluster-autoscaler/add_autoscaler_addon.png
  static/img/kubermatic/v2.22/tutorials/cluster-autoscaler/autoscaler_confirmation.png
  static/img/kubermatic/v2.22/tutorials/cluster-autoscaler/create_autoscaler_annotations.png
  static/img/kubermatic/v2.22/tutorials/cluster-autoscaler/delete_autoscaler.png
  static/img/kubermatic/v2.22/tutorials/cluster-autoscaler/edit_autoscaler.png
  static/img/kubermatic/v2.22/tutorials/cluster-autoscaler/edit_autoscaler_annotations.png
  static/img/kubermatic/v2.22/tutorials/cluster-autoscaler/install_autoscaler.png
  static/img/kubermatic/v2.22/tutorials/cluster-autoscaler/kkp_autoscaler_dashboard.png
  static/img/kubermatic/v2.22/tutorials/cluster-autoscaler/select_autoscaler.png
  static/img/kubermatic/v2.22/tutorials/external_clusters/add_md.png
  static/img/kubermatic/v2.22/tutorials/external_clusters/create_akspreset.png
  static/img/kubermatic/v2.22/tutorials/external_clusters/create_ekspreset.png
  static/img/kubermatic/v2.22/tutorials/external_clusters/create_gkepreset.png
  static/img/kubermatic/v2.22/tutorials/external_clusters/external_cluster_page.png
  static/img/kubermatic/v2.22/tutorials/external_clusters/provider_presets.png
  static/img/kubermatic/v2.22/tutorials/external_clusters/select_adminpanel.png
  static/img/kubermatic/v2.22/tutorials/seed-configurations/seed_confgurations.png
  static/img/kubermatic/v2.22/tutorials/seed-configurations/seed_confgurations_details.png
  static/img/kubermatic/v2.22/tutorials/seed-configurations/seed_confgurations_provider_datacenters.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1385 KubeOne: Update compatibility matrix for cluster creation
  content/kubeone/main/tutorials/creating-clusters-baremetal/_index.en.md
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1386 Introduce shortcode for current docs version
  layouts/shortcodes/current_version.html
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1358 Updated versions we currently support
  content/kubeone/v1.5/architecture/support-policy/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1387 Use RelPermalink instead of regex for calculating current version
  layouts/shortcodes/current_version.html
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1377 Add docs to import KubeOne cluster
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/aws/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/azure/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/gcp/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/kkp-kubeone-integration/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/kkp-kubeone-integration/aws/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/kkp-kubeone-integration/azure/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/kkp-kubeone-integration/gcp/_index.en.md
  static/img/kubermatic/main/tutorials/kubeone_clusters/aws_credentials_step.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/azure_credentials_step.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/cluster_details.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/cluster_list.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/cluster_list_empty.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/cluster_settings_step.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/disconnect_cluster_details.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/disconnect_cluster_dialog.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/disconnect_cluster_list.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/gcp_credentials_step.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/import_kubeone_cluster.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/md_details.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/update_md_dialog.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/update_md_list.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/upgrade_cluster.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/aws_credentials_step.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/azure_credentials_step.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/cluster_details.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/cluster_list.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/cluster_list_empty.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/cluster_settings_step.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/disconnect_cluster_details.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/disconnect_cluster_dialog.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/disconnect_cluster_list.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/gcp_credentials_step.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/import_kubeone_cluster.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/md_details.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/update_md_dialog.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/update_md_list.png
  static/img/kubermatic/v2.22/tutorials/kubeone_clusters/upgrade_cluster.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1388 Update KubermaticConfiguration for v2.22
  content/kubermatic/v2.22/data/kubermaticConfiguration.ce.yaml
  content/kubermatic/v2.22/data/kubermaticConfiguration.ee.yaml
  content/kubermatic/v2.22/data/kubermaticConfiguration.yaml
Labels: lgtm, approved, size/M, dco-signoff: yes

#1389 Adjust KubeVirt architecture diagram to KKP style
  static/img/kubermatic/main/architecture/supported-providers/kubevirt/architecture.png
  static/img/kubermatic/v2.22/architecture/supported-providers/kubevirt/architecture.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1390 Updating telemetry docs
  content/kubermatic/main/tutorials-howtos/telemetry/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/telemetry/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1379 Add upgrade guide and document known issues for KubeOne 1.6
  content/kubeone/main/known-issues/_index.en.md
  content/kubeone/main/tutorials/upgrading/upgrading-from-1.5-to-1.6/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1391 Update swagger doc for v2.22
  content/kubermatic/v2.22/data/swagger.json
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1382 Uncomment v2.22 to publish release docs
  data/products.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1393 Add note to upgrade guide about in-tree provider upgrade limitations
  content/kubermatic/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubermatic/main/installation/upgrading/upgrade-from-2.21-to-2.22/_index.en.md
  content/kubermatic/v2.22/architecture/compatibility/KKP-components-versioning/_index.en.md
  content/kubermatic/v2.22/architecture/compatibility/supported-versions/_index.en.md
  content/kubermatic/v2.22/installation/upgrading/upgrade-from-2.21-to-2.22/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1396 Check if response exists for render_external_markdown shortcode
  layouts/shortcodes/render_external_markdown.html
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1397 Add documentation on using MLA for health assessment.
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/customization/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/health-assessment/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/health-assessment/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/monitoring-logging-alerting/master-seed/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/monitoring-logging-alerting/master-seed/health-assessment/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/monitoring-logging-alerting/user-cluster/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/monitoring-logging-alerting/user-cluster/health-assessment/_index.en.md
  static/img/kubermatic/main/tutorials/mla/master-seed/health-assessment/all_dashboards.png
  static/img/kubermatic/main/tutorials/mla/master-seed/health-assessment/kkp_controllers.png
  static/img/kubermatic/main/tutorials/mla/master-seed/health-assessment/kubernetes_dashboards.png
  static/img/kubermatic/main/tutorials/mla/master-seed/health-assessment/machine_controller.png
  static/img/kubermatic/main/tutorials/mla/master-seed/health-assessment/user_clusters.png
  static/img/kubermatic/main/tutorials/mla/user-cluster/health-assessment/mla_dashboards.png
  static/img/kubermatic/main/tutorials/mla/user-cluster/health-assessment/mla_kkp_dashboard.png
  static/img/kubermatic/main/tutorials/mla/user-cluster/health-assessment/mla_kubernetes_workloads.png
  static/img/kubermatic/v2.22/tutorials/mla/master-seed/health-assessment/all_dashboards.png
  static/img/kubermatic/v2.22/tutorials/mla/master-seed/health-assessment/kkp_controllers.png
  static/img/kubermatic/v2.22/tutorials/mla/master-seed/health-assessment/kubernetes_dashboards.png
  static/img/kubermatic/v2.22/tutorials/mla/master-seed/health-assessment/machine_controller.png
  static/img/kubermatic/v2.22/tutorials/mla/master-seed/health-assessment/user_clusters.png
  static/img/kubermatic/v2.22/tutorials/mla/user-cluster/health-assessment/mla_dashboards.png
  static/img/kubermatic/v2.22/tutorials/mla/user-cluster/health-assessment/mla_kkp_dashboard.png
  static/img/kubermatic/v2.22/tutorials/mla/user-cluster/health-assessment/mla_kubernetes_workloads.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1394 Add KKP release notes in our docs
  content/kubermatic/v2.20/how_to_contribute_to_kkp/_index.en.md
  content/kubermatic/v2.20/release-notes/_index.en.md
  content/kubermatic/v2.21/how-to-contribute-to-kkp/_index.en.md
  content/kubermatic/v2.21/release-notes/_index.en.md
  content/kubermatic/v2.22/how-to-contribute-to-kkp/_index.en.md
  content/kubermatic/v2.22/release-notes/_index.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1398 Improve KubeVirt scheduling options documentation
  content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
  content/kubermatic/v2.22/architecture/supported-providers/kubevirt/kubevirt.en.md
Labels: approved, size/M, dco-signoff: yes
