Repository kubermatic/docs, pull requests merged in 2023-05, with the labels that each got.

#1438 Add schema markup for Org
  layouts/index.html
Labels: lgtm, approved, size/M, dco-signoff: yes

#1436 Update sample manifests for KubeOne cluster creation
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.6/tutorials/creating-clusters/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1440 Tweak org markup
  content/_index.md
  layouts/index.html
Labels: lgtm, approved, size/M, dco-signoff: yes

#1443 Fix link on docs in main menu
  data/mainMenu.yml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1447 Add DigitalOcean, Hetzner and OpenStack providers to kubeone wizard
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/digitalocean/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/hetzner/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/openstack/_index.en.md
  static/img/kubermatic/main/tutorials/kubeone_clusters/digitalocean_credentials_step.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/hetzner_credentials_step.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/import_kubeone_cluster.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/openstack_credentials_step.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1439 Add networking concept and rework port requirements
  content/kubermatic/main/architecture/concept/kkp-concepts/networking/_index.en.md
  content/kubermatic/main/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/main/data/ports.md
  content/kubermatic/main/tutorials-howtos/networking/expose-strategies/_index.en.md
  layouts/shortcodes/include.html
  static/img/kubermatic/main/concepts/architecture/expose-lb.png
  static/img/kubermatic/main/concepts/architecture/expose-np.png
  static/img/kubermatic/main/concepts/architecture/expose-tunnel.png
  static/img/kubermatic/main/concepts/architecture/network.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1449 Add the table with OS selection for downloading the installer
  content/kubermatic/main/installation/install-kkp-CE/_index.en.md
  content/kubermatic/v2.22/installation/install-kkp-CE/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1453 mention 1.27 support in KKP's support matrix
  content/kubermatic/main/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1451 Further improvements of vSphere documentation with PR comments
  content/kubermatic/main/architecture/supported-providers/vsphere/vsphere.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes
