Repository kubermatic/docs, pull requests merged in 2023-08, with the labels that each got.

#1499 Add MacOS download snippet in installation docs
  content/kubermatic/main/installation/install-kkp-CE/_index.en.md
  content/kubermatic/main/installation/local-kkp-installation/_index.en.md
  content/kubermatic/v2.22/installation/install-kkp-CE/_index.en.md
  content/kubermatic/v2.23/installation/install-kkp-CE/_index.en.md
  content/kubermatic/v2.23/installation/local-kkp-installation/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1500 Upload search index
  .gitignore
  functions/deploy-succeeded.js
  netlify.toml
  package-lock.json
  package.json
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1501 change machine_controller_machines_total to new kube_node_info metric
  content/kubermatic/main/tutorials-howtos/metering/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/metering/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/metering/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1503 Add release notes for v2.23.1, v2.22.5 and v2.21.11
  content/kubermatic/v2.21/release-notes/_index.en.md
  content/kubermatic/v2.22/release-notes/_index.en.md
  content/kubermatic/v2.23/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1502 Reference correct kubermatic-s3-credentials Secret for backup location
  content/kubermatic/main/installation/install-kkp-CE/add-seed-cluster-CE/_index.en.md
  content/kubermatic/v2.22/installation/install-kkp-CE/add-seed-cluster-CE/_index.en.md
  content/kubermatic/v2.23/installation/install-kkp-CE/add-seed-cluster-CE/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1504 Add example for defaultValues for AppDefs
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-definition/_index.en.md
  content/kubermatic/v2.22/architecture/concept/kkp-concepts/applications/application-definition/_index.en.md
  content/kubermatic/v2.23/architecture/concept/kkp-concepts/applications/application-definition/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1505 Update documentation for OSM
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1507 Add OIDC provider name to UI config
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1508 update KKP 2.24 compat matrix, remove k8s 1.24 from supported versions
  content/kubermatic/main/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1510 Update docs after August patch release
  content/kubermatic/v2.21/release-notes/_index.en.md
  content/kubermatic/v2.22/release-notes/_index.en.md
  content/kubermatic/v2.23/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes
