Repository kubermatic/docs, pull requests merged in 2023-12, with the labels that each got.

#1583 Remove KubeCarrier from main menu
  data/mainMenu.yml
  themes/kubermatic-docs/static/img/menu/kubecarrier.jpeg
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1585 Document known issue with Cilium as Seed CNI
  content/kubermatic/main/architecture/known-issues/_index.en.md
  content/kubermatic/main/installation/upgrading/upgrade-from-2.23-to-2.24/_index.en.md
  content/kubermatic/v2.24/architecture/known-issues/_index.en.md
  content/kubermatic/v2.24/installation/upgrading/upgrade-from-2.23-to-2.24/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1513 Add storage requirements page that mentions etcd requirements
  content/kubermatic/main/architecture/requirements/storage/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1586 Use a single clusterwide Cilium NetworkPolicy as workaround
  content/kubermatic/main/architecture/known-issues/_index.en.md
  content/kubermatic/v2.24/architecture/known-issues/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1587 Fix Typo in KubeOne Main AddOns Section
  content/kubeone/main/guides/addons/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1588 Mention Cilium issue on Seed installation docs
  content/kubermatic/main/installation/install-kkp-ce/add-seed-cluster/_index.en.md
  content/kubermatic/v2.24/installation/install-kkp-CE/add-seed-cluster-CE/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1589 Merge sig-virtualization to sig-cluster-management
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1591 Use correct example syntax for backups-restic addon in KubeOne
  content/kubeone/main/examples/addons-backup/_index.en.md
  content/kubeone/v1.5/examples/addons-backup/_index.en.md
  content/kubeone/v1.6/examples/addons-backup/_index.en.md
  content/kubeone/v1.7/examples/addons-backup/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1592 Update release notes to include December 2023 changelogs
  content/kubermatic/v2.22/release-notes/_index.en.md
  content/kubermatic/v2.23/release-notes/_index.en.md
  content/kubermatic/v2.24/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes
