Repository kubermatic/docs, pull requests merged in 2023-06, with the labels that each got.

#1456 Document labels, kubelet and bastion_host_key in Terraform integration reference
  content/kubeone/main/references/terraform-integration/_index.en.md
  content/kubeone/v1.5/references/terraform-integration/_index.en.md
  content/kubeone/v1.6/references/terraform-integration/_index.en.md
Labels: lgtm, approved, size/M, needs-ok-to-test, dco-signoff: yes

#1455 Add auto deploy rule permission for vsphere
  content/kubermatic/main/architecture/supported-providers/vsphere/vsphere.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1457 Require setting grafana domain in mla values
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1459 Exclude CentOS stream versions from support matrix
  content/kubeone/main/architecture/requirements/machine-controller/vSphere/vSphere.en.md
  content/kubeone/v1.3/architecture/requirements/machine_controller/vSphere/vSphere.en.md
  content/kubeone/v1.4/architecture/requirements/machine_controller/vSphere/vSphere.en.md
  content/kubeone/v1.5/architecture/requirements/machine-controller/vSphere/vSphere.en.md
  content/kubeone/v1.6/architecture/requirements/machine-controller/vSphere/vSphere.en.md
  content/kubermatic/main/architecture/compatibility/OS-support-matrix/_index.en.md
  content/kubermatic/main/architecture/supported-providers/vsphere/vsphere.en.md
  content/kubermatic/v2.17/architecture/requirements/support_policy/OS_support_matrix/_index.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/OS_support_matrix/_index.en.md
  content/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/v2.19/architecture/support_policy/OS_support_matrix/_index.en.md
  content/kubermatic/v2.19/architecture/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/v2.20/architecture/support_policy/OS_support_matrix/_index.en.md
  content/kubermatic/v2.20/architecture/support_policy/provider_support_matrix/vSphere/vSphere.en.md
  content/kubermatic/v2.21/architecture/compatibility/OS-support-matrix/_index.en.md
  content/kubermatic/v2.21/architecture/supported-providers/vSphere/vSphere.en.md
  content/kubermatic/v2.22/architecture/compatibility/OS-support-matrix/_index.en.md
  content/kubermatic/v2.22/architecture/supported-providers/vsphere/vsphere.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1464 Update crd-ref-docs to v0.0.9
  hack/crd-ref-docs.yaml
  hack/render-crds.sh
Labels: lgtm, approved, size/S, dco-signoff: yes

#1465 Add docs for share cluster admin setting
  content/kubermatic/main/architecture/concept/kkp-concepts/user-interface/theming/with-src/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/user-interface/theming/without-src/_index.en.md
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/share-clusters-via-delegated-OIDC-authentication/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/interface/_index.en.md
  content/kubermatic/main/tutorials-howtos/dashboard-customization/_index.en.md
  static/img/kubermatic/main/ui/enable_share_cluster.png
  static/img/kubermatic/main/ui/interface.png
  static/img/kubermatic/main/ui/share_cluster.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1466 Update metering docs to include report types
  content/kubermatic/main/tutorials-howtos/metering/_index.en.md
  static/img/kubermatic/main/tutorials/metering_admin_panel_location.png
  static/img/kubermatic/main/tutorials/metering_report_configuration.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1467 Update custom links docs to include changelog setting
  content/kubermatic/main/cheat-sheets/changelog/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/custom-links/_index.en.md
  static/img/kubermatic/main/ui/custom_links.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1468 Add docs for importing vSphere kubeone cluster
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/vsphere/_index.en.md
  static/img/kubermatic/main/tutorials/kubeone_clusters/import_kubeone_cluster.png
  static/img/kubermatic/main/tutorials/kubeone_clusters/vsphere_credentials_step.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1460 Update KubeOne OS support matrix with Rocky Linux 8
  content/kubeone/main/architecture/compatibility/OS-support-matrix/_index.en.md
  content/kubeone/main/architecture/requirements/machine-controller/vSphere/vSphere.en.md
  content/kubeone/v1.6/architecture/compatibility/OS-support-matrix/_index.en.md
  content/kubeone/v1.6/architecture/requirements/machine-controller/vSphere/vSphere.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1469 Update outdated docs and fix broken images
  content/kubermatic/main/architecture/iam-role-based-access-control/groups-support/_index.en.md
  content/kubermatic/main/tutorials-howtos/CCM-migration/CCM-migration-via-UI/_index.en.md
  content/kubermatic/main/tutorials-howtos/OPA-integration/OPA-integration-Via-UI/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/cluster-settings/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/custom-links/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/opa-default-constraints/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/aws/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/azure/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/digitalocean/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/gcp/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/hetzner/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/openstack/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/setting-up-alertmanager-with-slack-notifications/_index.en.md
  content/kubermatic/main/tutorials-howtos/operating-system-manager/usage/_index.en.md
  static/img/kubermatic/main/architecture/group-rbac-view.png
  static/img/kubermatic/main/ui/machine_deployment.png
  static/img/kubermatic/main/ui/wizard_initial_nodes_step.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1470 fix the add project img
  static/img/kubermatic/main/tutorials/project_add.png
  static/img/kubermatic/v2.19/tutorials/project_add.png
  static/img/kubermatic/v2.20/tutorials/project_add.png
  static/img/kubermatic/v2.21/tutorials/project_add.png
  static/img/kubermatic/v2.22/tutorials/project_add.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1471 Remove redirection URL from header for preparing new themes section
  content/kubermatic/main/architecture/concept/kkp-concepts/user-interface/theming/_index.en.md
  content/kubermatic/main/tutorials-howtos/dashboard-customization/_index.en.md
  content/kubermatic/v2.21/architecture/concept/kkp-concepts/user-interface/theming/_index.en.md
  content/kubermatic/v2.22/architecture/concept/kkp-concepts/user-interface/theming/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1472 Add changelogs for KKP 2.22.4 and 2.21.10
  content/kubermatic/v2.21/release-notes/_index.en.md
  content/kubermatic/v2.22/release-notes/_index.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1473 Fixed details on role-definitions
  content/kubermatic/main/architecture/supported-providers/vsphere/vsphere.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1475 Update documentation for OSM
  content/operatingsystemmanager/compatibility/_index.en.md
  content/operatingsystemmanager/data/osp-ubuntu-swap-enabled.yaml
  content/operatingsystemmanager/references/crds/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1477 Improve documentation for vSphere network segmentation issue on VMXNET3 driver
  content/kubeone/main/guides/vsphere-template-vm/ubuntu/_index.en.md
  content/kubeone/v1.5/guides/vsphere-template-vm/ubuntu/_index.en.md
  content/kubeone/v1.5/known-issues/_index.en.md
  content/kubeone/v1.6/guides/vsphere-template-vm/ubuntu/_index.en.md
  content/kubeone/v1.6/known-issues/_index.en.md
  content/kubermatic/main/architecture/known-issues/_index.en.md
  content/kubermatic/main/architecture/supported-providers/vsphere/vsphere.en.md
  content/kubermatic/v2.21/architecture/known-issues/_index.en.md
  content/kubermatic/v2.21/architecture/supported-providers/vSphere/vSphere.en.md
  content/kubermatic/v2.22/architecture/known-issues/_index.en.md
  content/kubermatic/v2.22/architecture/supported-providers/vsphere/vsphere.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1476 Update OSP examples in KubeOne and KKP
  content/kubeone/main/architecture/operating-system-manager/usage/_index.en.md
  content/kubermatic/main/tutorials-howtos/operating-system-manager/usage/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1479 Update docs for import `openstack` KubeOne cluster
  content/kubermatic/main/tutorials-howtos/etcd-backups/_index.en.md
  content/kubermatic/main/tutorials-howtos/external-clusters/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-kubeone-integration/openstack/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/external-clusters/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/external-clusters/_index.en.md
  static/img/kubermatic/main/tutorials/kubeone_clusters/openstack_credentials_step.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1474 Make Seed config a sub-chapter of 'Custom Configuration'
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/OIDC-Provider-Configuration/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1485 Fix example for specifying default TLS certs for nginx
  content/kubermatic/main/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1483 Remove reference links from page headings
  content/kubermatic/main/architecture/concept/kkp-concepts/user-interface/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/user-interface/theming/_index.en.md
  content/kubermatic/main/architecture/monitoring-logging-alerting/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/_index.en.md
  content/kubermatic/v2.21/architecture/concept/kkp-concepts/user-interface/_index.en.md
  content/kubermatic/v2.21/architecture/concept/kkp-concepts/user-interface/theming/_index.en.md
  content/kubermatic/v2.21/architecture/monitoring-logging-alerting/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/administration/admin-panel/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/monitoring-logging-alerting/_index.en.md
  content/kubermatic/v2.22/architecture/concept/kkp-concepts/user-interface/_index.en.md
  content/kubermatic/v2.22/architecture/concept/kkp-concepts/user-interface/theming/_index.en.md
  content/kubermatic/v2.22/architecture/monitoring-logging-alerting/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/administration/admin-panel/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/monitoring-logging-alerting/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1486 Add `latest` pseudo-release URL that redirects to the latest release
  layouts/_default/home.redirects
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1488 Fix 'getting kubeone' zsh command completion
  content/kubeone/main/getting-kubeone/_index.en.md
  content/kubeone/v1.0/getting_kubeone/_index.en.md
  content/kubeone/v1.2/getting_kubeone/_index.en.md
  content/kubeone/v1.3/guides/getting_kubeone/_index.en.md
  content/kubeone/v1.4/getting_kubeone/_index.en.md
  content/kubeone/v1.5/getting-kubeone/_index.en.md
  content/kubeone/v1.6/getting-kubeone/_index.en.md
Labels: lgtm, ok-to-test, approved, size/S, dco-signoff: yes

#1489 Launch v2.23 documentation
  content/kubermatic/v2.22/release-notes/_index.en.md
  content/kubermatic/v2.23/data/kubermaticConfiguration.ce.yaml
  content/kubermatic/v2.23/data/kubermaticConfiguration.ee.yaml
  content/kubermatic/v2.23/data/kubermaticConfiguration.yaml
  content/kubermatic/v2.23/installation/upgrading/upgrade-from-2.22-to-2.23/_index.en.md
  content/kubermatic/v2.23/release-notes/_index.en.md
  data/products.yaml
Labels: lgtm, size/L, approved, dco-signoff: yes

#1490 Add warning regarding MinIO chart upgrade
  content/kubermatic/main/installation/upgrading/upgrade-from-2.22-to-2.23/_index.en.md
  content/kubermatic/v2.23/installation/upgrading/upgrade-from-2.22-to-2.23/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes
