Repository kubermatic/docs, pull requests merged in 2023-03, with the labels that each got.

#1399 Improve KubeVirt scheduling doc - part 2
  content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
  content/kubermatic/v2.22/architecture/supported-providers/kubevirt/kubevirt.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes, sig/virtualization

#1400 add KKP 2.23 upgrade stub
  content/kubermatic/main/installation/upgrading/upgrade-from-2.22-to-2.23/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1350 Iam doc
  content/kubermatic/main/architecture/iam-role-based-access-control/_index.en.md
  content/kubermatic/main/architecture/iam-role-based-access-control/groups-support/_index.en.md
  content/kubermatic/main/architecture/role-based-access-control/_index.en.md
  content/kubermatic/main/installation/install-kkp-EE/add-seed-cluster-EE/_index.en.md
  content/kubermatic/main/installation/upgrading/upgrade-from-2.20-to-2.21/_index.en.md
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/share-clusters-via-delegated-OIDC-authentication/_index.en.md
  content/kubermatic/main/tutorials-howtos/cluster-access/_index.en.md
  content/kubermatic/v2.22/architecture/iam-role-based-access-control/_index.en.md
  content/kubermatic/v2.22/architecture/iam-role-based-access-control/groups-support/_index.en.md
  content/kubermatic/v2.22/architecture/role-based-access-control/_index.en.md
  content/kubermatic/v2.22/installation/install-kkp-EE/add-seed-cluster-EE/_index.en.md
  content/kubermatic/v2.22/installation/upgrading/upgrade-from-2.20-to-2.21/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/OIDC-Provider-Configuration/share-clusters-via-delegated-OIDC-authentication/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/cluster-access/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1402 Update background image on homepage
  layouts/index.html
  static/img/main-background.svg
  themes/kubermatic-docs/assets/scss/_home.scss
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1320 Remove ARM64 limitation for Canal+ipvs from 2.21 docs
  content/kubermatic/v2.21/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1349 refine installation guide
  content/kubeone/main/architecture/requirements/machine-controller/_index.en.md
  content/kubermatic/main/architecture/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE/_index.en.md
  content/kubermatic/main/installation/install-kkp-CE/add-seed-cluster-CE/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/presets/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1407 Update changelogs after patch release
  content/kubermatic/v2.20/release-notes/_index.en.md
  content/kubermatic/v2.21/release-notes/_index.en.md
  content/kubermatic/v2.22/release-notes/_index.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1408 Fix multiline issue for notice shortcode
  themes/kubermatic-docs/assets/scss/_theme-kubermatic.scss
  themes/kubermatic-docs/assets/scss/_theme.scss
  themes/kubermatic-docs/layouts/shortcodes/notice.html
Labels: lgtm, approved, size/M, dco-signoff: yes

#1409 Update _index.en.md
  content/kubeone/v1.6/examples/addons-backup/_index.en.md
Labels: lgtm, ok-to-test, size/XS, approved, dco-signoff: yes

#1413 Expected skills and knowledge for the installation
  content/kubermatic/main/installation/install-kkp-CE/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1415 improve KKP AWS docs a bit
  content/kubermatic/main/architecture/supported-providers/aws/aws.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1416 clarify that we need no AWS root account access
  content/kubermatic/main/tutorials-howtos/administration/presets/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1418 Add cilium systemd to known issue
  content/kubeone/v1.6/known-issues/_index.en.md
  content/kubermatic/v2.22/architecture/known-issues/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes, sig/networking

#1425 Align with main for AWS requirements
  content/kubermatic/v2.22/installation/install-kkp-CE/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1426 Add AWS listing to EE page
  content/kubermatic/v2.22/architecture/enterprise-edition/_index.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1427 Add AWS listing to EE page
  content/kubermatic/main/architecture/enterprise-edition/_index.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1430 Update documentation for using custom theme for dashboard
  content/kubermatic/main/architecture/concept/kkp-concepts/user-interface/theming/with-src/_index.en.md
  content/kubermatic/main/tutorials-howtos/dashboard-customization/_index.en.md
  content/kubermatic/v2.21/architecture/concept/kkp-concepts/user-interface/theming/with-src/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/dashboard-customization/_index.en.md
  content/kubermatic/v2.22/architecture/concept/kkp-concepts/user-interface/theming/with-src/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/dashboard-customization/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes
