Repository kubermatic/docs, pull requests merged in 2023-10, with the labels that each got.

#1528 Add deprecation note to OpenVPN component in user clusters
  content/kubermatic/main/tutorials-howtos/networking/cni-cluster-network/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1530 Disable admin kubeconfig
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/interface/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/administration/admin-panel/interface/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/administration/admin-panel/interface/_index.en.md
  static/img/kubermatic/main/ui/disable_admin_kubeconfig.png
  static/img/kubermatic/v2.22/ui/disable_admin_kubeconfig.png
  static/img/kubermatic/v2.23/ui/disable_admin_kubeconfig.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1531 OSM: drop support for k8s 1.25 from compatibility matrix
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1532 Update changelogs after october patch releases
  content/kubermatic/v2.21/release-notes/_index.en.md
  content/kubermatic/v2.22/release-notes/_index.en.md
  content/kubermatic/v2.23/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1534 Remove auth.caBundle reference
  content/kubermatic/main/tutorials-howtos/OIDC-Provider-Configuration/share-clusters-via-delegated-OIDC-authentication/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/OIDC-Provider-Configuration/share-clusters-via-delegated-OIDC-authentication/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/OIDC-Provider-Configuration/share-clusters-via-delegated-OIDC-authentication/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1535 Add `kind: ConfigMap` in snippet for custom CA configuration
  content/kubermatic/main/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1536 Update documentation for disabling cert-manager integration
  content/kubermatic/main/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1538 Syncing with kubermatic/kubermatic@083c8ef39
  content/kubermatic/v2.23/references/crds/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1539 Syncing with kubermatic/kubermatic@083c8ef39
  content/kubermatic/v2.23/architecture/compatibility/KKP-components-versioning/_index.en.md
  content/kubermatic/v2.23/data/kubermaticConfiguration.ce.yaml
  content/kubermatic/v2.23/data/kubermaticConfiguration.ee.yaml
  content/kubermatic/v2.23/data/kubermaticConfiguration.yaml
  content/kubermatic/v2.23/data/seed.ce.yaml
  content/kubermatic/v2.23/data/seed.ee.yaml
  content/kubermatic/v2.23/data/seed.yaml
Labels: lgtm, approved, size/M, dco-signoff: yes

#1540 Update 2.22 documentation to disable cert-manager integration
  content/kubermatic/v2.22/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1543 Bump js lib for fixing security issue
  package-lock.json
Labels: lgtm, size/L, approved, dco-signoff: yes

#1533 Update Kubernetes support matrix for 2.24
  content/kubermatic/main/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1545 bump Hugo to 0.119.0
  .prow.yaml
  Makefile
  README.md
  hack/ci/verify-hugo.sh
  netlify.toml
Labels: lgtm, approved, size/S, dco-signoff: yes

#1544 mark CentOS as no longer supported on Hetzner in KKP 2.24+
  content/kubermatic/main/architecture/compatibility/OS-support-matrix/_index.en.md
  content/kubermatic/main/architecture/supported-providers/aws/_index.en.md
  content/kubermatic/main/architecture/supported-providers/azure/_index.en.md
  content/kubermatic/main/architecture/supported-providers/gcp/_index.en.md
  content/kubermatic/main/architecture/supported-providers/hetzner/_index.en.md
  content/kubermatic/main/architecture/supported-providers/kubevirt/_index.en.md
  content/kubermatic/main/architecture/supported-providers/nutanix/_index.en.md
  content/kubermatic/main/architecture/supported-providers/vmware-cloud-director/_index.en.md
  content/kubermatic/main/architecture/supported-providers/vsphere/_index.en.md
  content/kubermatic/main/installation/upgrading/upgrade-from-2.21-to-2.22/_index.en.md
  content/kubermatic/main/installation/upgrading/upgrade-from-2.22-to-2.23/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1496 Thanos integration
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/customization/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/customization/thanos.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1546 Fix typo: `tains` -> `taints`
  content/kubeone/v1.7/guides/all-in-one-node/_index.en.md
Labels: lgtm, size/XS, approved, needs-ok-to-test, dco-signoff: yes

#1547 Remove Zenhub
  Zenhub.md
Labels: kind/cleanup, lgtm, approved, size/S, dco-signoff: yes

#1549 Drop centos support for Hetzner
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1551 Syncing with kubermatic/kubermatic@0721d71c6
  content/kubermatic/v2.23/architecture/compatibility/KKP-components-versioning/_index.en.md
  content/kubermatic/v2.23/data/kubermaticConfiguration.ce.yaml
  content/kubermatic/v2.23/data/kubermaticConfiguration.ee.yaml
  content/kubermatic/v2.23/data/kubermaticConfiguration.yaml
  content/kubermatic/v2.23/data/seed.ce.yaml
  content/kubermatic/v2.23/data/seed.ee.yaml
  content/kubermatic/v2.23/data/seed.yaml
  content/kubermatic/v2.23/references/crds/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1552 Syncing with kubermatic/kubermatic@bfbf995e4
  content/kubermatic/v2.22/architecture/compatibility/KKP-components-versioning/_index.en.md
  content/kubermatic/v2.22/data/addondata.go
  content/kubermatic/v2.22/data/kubermaticConfiguration.ce.yaml
  content/kubermatic/v2.22/data/kubermaticConfiguration.ee.yaml
  content/kubermatic/v2.22/data/kubermaticConfiguration.yaml
  content/kubermatic/v2.22/data/seed.ce.yaml
  content/kubermatic/v2.22/data/seed.ee.yaml
  content/kubermatic/v2.22/data/seed.yaml
  content/kubermatic/v2.22/references/crds/_index.en.md
  data/kubermatic/v2.22/runbook.json
Labels: lgtm, size/L, approved, dco-signoff: yes

#1554 Update documentation to disable cert-manager integration
  content/kubermatic/main/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/KKP-configuration/custom-certificates/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1553 Documentation for KubeLB
  content/kubelb/_index.en.md
  content/kubelb/data/create-kubelb-sa.sh
  content/kubelb/installation/_index.en.md
  content/kubelb/usage/_index.en.md
  content/kubermatic/main/tutorials-howtos/kubelb/_index.en.md
  data/products.yaml
  static/img/Docs-KubeLB-share.jpg
  static/img/kubelb/common/architecture.png
  static/img/kubelb/common/logo.png
  static/img/kubermatic/main/tutorials/kubelb/kubelb_dashboard.png
Labels: lgtm, size/L, approved, dco-signoff: yes
