Repository kubermatic/docs, pull requests merged in 2024-08, with the labels that each got.

#1724 Add known issue regarding AWS and Ubuntu for KKP
  content/kubermatic/v2.23/architecture/known-issues/_index.en.md
  content/kubermatic/v2.24/architecture/known-issues/_index.en.md
  content/kubermatic/v2.25/architecture/known-issues/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1726 Uncollapse sections on selection
  themes/kubermatic-docs/layouts/partials/menu.html
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1730 KubeLB: Finalize release notes
  content/kubelb/main/release-notes/_index.en.md
  content/kubelb/main/tutorials/observability/_index.en.md
  content/kubelb/v1.1/ce-ee-matrix/_index.en.md
  content/kubelb/v1.1/installation/management-cluster/_index.en.md
  content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/release-notes/_index.en.md
  content/kubelb/v1.1/tutorials/gatewayapi/_index.en.md
  content/kubelb/v1.1/tutorials/observability/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1731 Remove MLA from comparison matrix
  content/kubelb/main/ce-ee-matrix/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1732 Kubelb: mention prefix for tenants
  content/kubelb/main/installation/tenant-cluster/_index.en.md
  content/kubelb/main/tutorials/tenants/_index.en.md
  content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/tutorials/tenants/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1733 Use enable-gateway-api instead of disable-gateway-api
  content/kubelb/main/installation/management-cluster/_index.en.md
  content/kubelb/main/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/installation/management-cluster/_index.en.md
  content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/tutorials/gatewayapi/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1735 Update install docs for KubeLB
  content/kubelb/main/installation/management-cluster/_index.en.md
  content/kubelb/main/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/installation/management-cluster/_index.en.md
  content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1736 Add redirects for KubeLB pages
  layouts/_default/home.redirects
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1734 Publish KubeLB v1.1
  data/products.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1737 Update the Kubernetes compatibility matrix for supported KubeOne versions
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/v1.7/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/v1.8/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1739 correct description for automatic node updates
  content/kubermatic/main/tutorials-howtos/administration/version-and-upgrade-configuration/_index.en.md
  content/kubermatic/v2.14/advanced/versions_updates/_index.en.md
  content/kubermatic/v2.15/advanced/versions_updates/_index.en.md
  content/kubermatic/v2.16/advanced/versions_updates/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/upgrading/version-and-upgrade-configuration/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/administration/version-and-upgrade-configuration/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/administration/version-and-upgrade-configuration/_index.en.md
  content/kubermatic/v2.24/tutorials-howtos/administration/version-and-upgrade-configuration/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/administration/version-and-upgrade-configuration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes
