Repository kubermatic/docs, pull requests merged in 2024-03, with the labels that each got.

#1625 OSM: flatcar is now supported for VMware Cloud Director
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1623 Remove k8s 1.26 from OSM compatibility matrix
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1627 Update CRD references for OSM
  content/operatingsystemmanager/references/crds/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1628 Fix broken image links in application docs
  content/kubermatic/main/tutorials-howtos/applications/add-applications-to-cluster/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/update-application/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1624 fix app name: cert-manager is the official, real name
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/cert-manager/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1607 Adding application catalog to EE page
  content/kubermatic/main/architecture/enterprise-edition/_index.md
  content/kubermatic/v2.24/architecture/enterprise-edition/_index.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1601 Replace broken link to architecture image in K1 v1.6/v1.7/main docs
  content/kubeone/main/architecture/operating-system-manager/_index.en.md
  content/kubeone/main/architecture/operating-system-manager/images/architecture.png
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
  content/kubeone/main/tutorials/creating-clusters/images/architecture.png
  content/kubeone/v1.5/architecture/operating-system-manager/_index.en.md
  content/kubeone/v1.5/architecture/operating-system-manager/images/architecture.png
  content/kubeone/v1.6/architecture/operating-system-manager/_index.en.md
  content/kubeone/v1.6/architecture/operating-system-manager/images/architecture.png
  content/kubeone/v1.7/architecture/operating-system-manager/_index.en.md
  content/kubeone/v1.7/architecture/operating-system-manager/images/architecture.png
  static/img/kubeone/main/operating-system-manager/architecture.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1629 Update KubeOne 1.8 supported versions
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1630 rip out kubecarrier docs, gently without removing them
  PROCESS.md
  README.md
  content/_index.md
  data/products.yaml
  hack/README.md
  hack/prepare-release.sh
  layouts/index.html
Labels: lgtm, approved, size/M, dco-signoff: yes

#1632 Update example base domain url to kkp.example.com
  content/kubermatic/main/installation/install-kkp-ce/_index.en.md
  content/kubermatic/v2.22/installation/install-kkp-CE/_index.en.md
  content/kubermatic/v2.23/installation/install-kkp-CE/_index.en.md
  content/kubermatic/v2.24/installation/install-kkp-CE/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1633 Docs for KubeLB v0.7.0
  content/kubelb/data/create-kubelb-sa.sh
  content/kubelb/installation/_index.en.md
  content/kubelb/references/crds/_index.en.md
  content/kubelb/usage/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1634 Fix example for propagatedAnnotations
  content/kubelb/usage/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1635 Add Flatcar to supported OSes for GCP and VCD
  content/kubermatic/main/architecture/compatibility/os-support-matrix/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1639 Minor updates to the KKP docs
  content/kubermatic/main/installation/install-kkp-ce/_index.en.md
  content/kubermatic/main/installation/install-kkp-ce/add-seed-cluster/_index.en.md
  content/kubermatic/main/installation/install-kkp-ee/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/add-applications-to-cluster/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/v2.24/installation/install-kkp-EE/_index.en.md
  static/img/kubermatic/common/applications/default-applications-catalog.png
  static/img/kubermatic/v2.24/architecture/concepts/applications/default-applications-catalog.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1643 Add doc for Nvidia GPU Operator
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/argocd/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/k8sgpt/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/nvidia-gpu-operator/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/argocd/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/k8sgpt/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/kubevirt/_index.en.md
  content/kubermatic/v2.25/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/v2.25/architecture/concept/kkp-concepts/applications/default-applications-catalog/argocd/_index.en.md
  content/kubermatic/v2.25/architecture/concept/kkp-concepts/applications/default-applications-catalog/k8sgpt/_index.en.md
  content/kubermatic/v2.25/architecture/concept/kkp-concepts/applications/default-applications-catalog/nvidia-gpu-operator/_index.en.md
  static/img/kubermatic/v2.24/architecture/concepts/applications/default-applications-catalog/01-select-application-k8sgpt-app.png
  static/img/kubermatic/v2.24/architecture/concepts/applications/default-applications-catalog/01-select-application-kubevirt-app.png
  static/img/kubermatic/v2.24/architecture/concepts/applications/default-applications-catalog/02-settings-k8sgpt-app.png
  static/img/kubermatic/v2.24/architecture/concepts/applications/default-applications-catalog/02-settings-kubevirt-app.png
  static/img/kubermatic/v2.24/architecture/concepts/applications/default-applications-catalog/03-applicationvalues-k8sgpt-app.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1646 Edge provider documentation
  content/kubermatic/main/architecture/compatibility/os-support-matrix/_index.en.md
  content/kubermatic/main/architecture/supported-providers/_index.en.md
  content/kubermatic/main/architecture/supported-providers/edge/_index.en.md
  content/kubermatic/v2.25/architecture/compatibility/os-support-matrix/_index.en.md
  content/kubermatic/v2.25/architecture/supported-providers/_index.en.md
  content/kubermatic/v2.25/architecture/supported-providers/edge/_index.en.md
  static/img/kubermatic/main/architecture/supported-providers/edge/edge-machine-deployment-window.png
  static/img/kubermatic/v2.25/main/architecture/supported-providers/edge/edge-machine-deployment-window.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1647 Add MLA-minio upgrade notes for 2.25
  content/kubermatic/v2.25/installation/upgrading/upgrade-from-2.24-to-2.25/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1642 feat: clarify infrastructure requirements
  content/kubeone/main/architecture/requirements/infrastructure-management/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1644 fix: ID of the cluster is required instead of the name
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1648 Minor fix to Master/Seed MLA Health Check docs
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/health-assessment/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/monitoring-logging-alerting/master-seed/health-assessment/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/monitoring-logging-alerting/master-seed/health-assessment/_index.en.md
  content/kubermatic/v2.24/tutorials-howtos/monitoring-logging-alerting/master-seed/health-assessment/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/monitoring-logging-alerting/master-seed/health-assessment/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1651 Fix leftover from copy-paste (2.24 instead of 2.25) in upgrade guide
  content/kubermatic/main/installation/upgrading/upgrade-from-2.24-to-2.25/_index.en.md
  content/kubermatic/v2.25/installation/upgrading/upgrade-from-2.24-to-2.25/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1637 Add CIS Benchmark documentation to KubeOne
  content/kubeone/main/guides/cis-benchmarking/_index.en.md
  content/kubeone/main/guides/cis-benchmarking/cis1.8-kubeone1.7-k8s1.27/_index.en.md
  content/kubeone/v1.7/guides/cis-benchmarking/_index.en.md
  content/kubeone/v1.7/guides/cis-benchmarking/cis1.8-kubeone1.7-k8s1.27/_index.en.md
  hack/kube-bench-k1/README.md
  hack/kube-bench-k1/additional_details_cis-1.8.json
  hack/kube-bench-k1/configurable_controls_cis-1.8.json
  hack/kube-bench-k1/create_md.py
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1652 KKP base domain update
  content/kubermatic/main/architecture/concept/kkp-concepts/kkp-security/securing-system-services/_index.en.md
  content/kubermatic/main/installation/install-kkp-ce/_index.en.md
  content/kubermatic/main/installation/install-kkp-ce/add-seed-cluster/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-configuration/custom-certificates/_index.en.md
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/installation/_index.en.md
  content/kubermatic/v2.25/architecture/concept/kkp-concepts/kkp-security/securing-system-services/_index.en.md
  content/kubermatic/v2.25/installation/install-kkp-ce/_index.en.md
  content/kubermatic/v2.25/installation/install-kkp-ce/add-seed-cluster/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/kkp-configuration/custom-certificates/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/monitoring-logging-alerting/master-seed/installation/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes
