Repository kubermatic/docs, pull requests merged in 2024-01, with the labels that each got.

#1595 KubeOne: document known issues fixed in KubeOne 1.7.2
  content/kubeone/main/known-issues/_index.en.md
  content/kubeone/v1.7/known-issues/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1598 Include k8s 1.29 in compatibility matrix for OSM
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1599 Flatcar is now supported on GCE
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1604 Add AWS to supported providers for KubeOne CCM migration
  content/kubeone/main/guides/ccm-csi-migration/_index.en.md
  content/kubeone/v1.7/guides/ccm-csi-migration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1605 Update secret generation snippet to generic variant
  content/kubermatic/main/installation/install-kkp-ce/_index.en.md
  content/kubermatic/v2.22/installation/install-kkp-CE/_index.en.md
  content/kubermatic/v2.23/installation/install-kkp-CE/_index.en.md
  content/kubermatic/v2.24/installation/install-kkp-CE/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1603 Update manual etcd restore procedure
  content/kubermatic/main/cheat-sheets/etcd/legacy-restore/_index.en.md
  content/kubermatic/main/cheat-sheets/etcd/replace-a-member/_index.en.md
  content/kubermatic/main/installation/install-kkp-ce/add-seed-cluster/_index.en.md
  content/kubermatic/v2.22/cheat-sheets/etcd/legacy-restore/_index.en.md
  content/kubermatic/v2.22/cheat-sheets/etcd/replace-a-member/_index.en.md
  content/kubermatic/v2.23/cheat-sheets/etcd/legacy-restore/_index.en.md
  content/kubermatic/v2.23/cheat-sheets/etcd/replace-a-member/_index.en.md
  content/kubermatic/v2.23/installation/install-kkp-CE/add-seed-cluster-CE/_index.en.md
  content/kubermatic/v2.24/cheat-sheets/etcd/legacy-restore/_index.en.md
  content/kubermatic/v2.24/cheat-sheets/etcd/replace-a-member/_index.en.md
  content/kubermatic/v2.24/installation/install-kkp-CE/add-seed-cluster-CE/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1608 Updated release notes to include Jan 2024 changelogs
  content/kubermatic/v2.22/release-notes/_index.en.md
  content/kubermatic/v2.23/release-notes/_index.en.md
  content/kubermatic/v2.24/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes
