Repository kubermatic/docs, pull requests merged in 2024-10, with the labels that each got.

#1759 Fix more typos
  content/kubermatic/main/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/main/tutorials-howtos/external-clusters/eks/_index.en.md
  content/kubermatic/v2.14/advanced/addons/_index.en.md
  content/kubermatic/v2.15/advanced/addons/_index.en.md
  content/kubermatic/v2.16/advanced/addons/_index.en.md
  content/kubermatic/v2.17/guides/addons/_index.en.md
  content/kubermatic/v2.18/guides/addons/_index.en.md
  content/kubermatic/v2.19/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.20/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/external_clusters/eks/_index.en.md
  content/kubermatic/v2.21/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/external-clusters/eks/_index.en.md
  content/kubermatic/v2.22/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/external-clusters/eks/_index.en.md
  content/kubermatic/v2.23/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/external-clusters/eks/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.24/tutorials-howtos/external-clusters/eks/_index.en.md
  content/kubermatic/v2.25/architecture/concept/kkp-concepts/addons/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/external-clusters/eks/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1750 Added a tutorial page for VPA in kkp
  content/kubermatic/main/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-autoscaler/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-autoscaler/cluster-autoscaler/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-autoscaler/vertical-pod-autoscaler/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1764 Customizable presets
  content/kubermatic/main/tutorials-howtos/administration/presets/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/presets/images/cluster-creation-customizable-presets.png
  content/kubermatic/main/tutorials-howtos/administration/presets/images/customizable-preset.png
  content/kubermatic/v2.26/tutorials-howtos/administration/presets/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/administration/presets/images/cluster-creation-customizable-presets.png
  content/kubermatic/v2.26/tutorials-howtos/administration/presets/images/customizable-preset.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1763 Copy audit webhook docs to v2.26
  content/kubermatic/main/tutorials-howtos/audit-logging/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/audit-logging/01-webhook-backend-cluster.png
  content/kubermatic/v2.26/tutorials-howtos/audit-logging/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1765 Hide 2.26 documentation from docs.kubermatic.com until the release is out
  data/products.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1713 Velero migration instructions
  content/kubermatic/main/installation/upgrading/upgrade-from-2.25-to-2.26/_index.en.md
  content/kubermatic/v2.26/architecture/supported-providers/kubevirt/_index.en.md
  content/kubermatic/v2.26/how-to-contribute/_index.en.md
  content/kubermatic/v2.26/installation/install-kkp-ce/add-seed-cluster/_index.en.md
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.20-to-2.21/_index.en.md
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.21-to-2.22/_index.en.md
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.22-to-2.23/_index.en.md
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.23-to-2.24/_index.en.md
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.24-to-2.25/_index.en.md
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.25-to-2.26/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/networking/ipam/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1766 remove oauth upgrade hint from the KKP 2.26 upgrade guide
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.25-to-2.26/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1767 backported VPA documentation to v2.26 docs as well
  content/kubermatic/v2.26/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/kkp-autoscaler/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/kkp-autoscaler/cluster-autoscaler/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/kkp-autoscaler/vertical-pod-autoscaler/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1696 Add machine controller documentation
  config.toml
  content/_index.md
  content/machine-controller/_index.en.md
  content/machine-controller/main/_index.en.md
  content/machine-controller/main/cloud-providers/_index.en.md
  content/machine-controller/main/cloud-providers/anexia/_index.en.md
  content/machine-controller/main/cloud-providers/kubevirt/_index.en.md
  content/machine-controller/main/cloud-providers/nutanix/_index.en.md
  content/machine-controller/main/cloud-providers/openstack/_index.en.md
  content/machine-controller/main/cloud-providers/vmware-cloud-director/_index.en.md
  content/machine-controller/main/cloud-providers/vsphere/_index.en.md
  content/machine-controller/main/cloud-providers/vsphere/template-vm/_index.en.md
  content/machine-controller/main/cloud-providers/vsphere/template-vm/ova/_index.en.md
  content/machine-controller/main/cloud-providers/vsphere/template-vm/qcow2/_index.en.md
  content/machine-controller/main/cloud-providers/vsphere/template-vm/rockylinux/_index.en.md
  content/machine-controller/main/cloud-providers/vsphere/template-vm/ubuntu/_index.en.md
  content/machine-controller/main/developing/_index.en.md
  content/machine-controller/main/developing/creating-providers/_index.en.md
  content/machine-controller/main/operating-systems/_index.en.md
  content/machine-controller/main/operating-systems/rhel/_index.en.md
  content/operatingsystemmanager/guides/custom-registry/_index.en.md
  data/products.yaml
  hack/verify-filenames.sh
  layouts/shortcodes/render_external_code.html
  static/img/share-machine-controller.png
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1769 Reorder products in navigation menu
  data/products.yaml
Labels: lgtm, approved, size/M, dco-signoff: yes

#1770 Fix broken link for KubeOne docs
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.4/tutorials/creating_clusters/_index.en.md
  content/kubeone/v1.5/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.6/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.7/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.8/tutorials/creating-clusters/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1771 KubeLB v1.1.2
  content/kubelb/v1.1/installation/management-cluster/_index.en.md
  content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1772 show KKP 2.26 docs
  data/products.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1777 Add KKP v2.26 release notes
  content/kubermatic/main/release-notes/_index.en.md
  content/kubermatic/v2.26/release-notes/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1778 kubelb: tenant/global configuration precedence
  content/kubelb/main/tutorials/config/_index.en.md
  content/kubelb/main/tutorials/tenants/_index.en.md
  content/kubelb/v1.1/tutorials/config/_index.en.md
  content/kubelb/v1.1/tutorials/tenants/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1773 Update Kubernetes support matrix for KKP 2.26
  content/kubermatic/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubermatic/v2.26/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1780 Removed old KKP release known issues
  content/kubermatic/main/architecture/known-issues/_index.en.md
  content/kubermatic/v2.26/architecture/known-issues/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1781 remove misleading dex migration note for KKP 2.26
  content/kubermatic/main/installation/upgrading/upgrade-from-2.25-to-2.26/_index.en.md
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.25-to-2.26/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1784 fix typo in velero upgrade docs
  content/kubermatic/main/installation/upgrading/upgrade-from-2.25-to-2.26/_index.en.md
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.25-to-2.26/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1782 Regenerate 2.26 CRD reference
  content/kubermatic/v2.26/references/crds/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1783 Delete Bare metal via KubeVirt from providers
  content/kubermatic/main/architecture/supported-providers/_index.en.md
  content/kubermatic/v2.26/architecture/supported-providers/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1785 Add baremetal provider docs
  content/kubermatic/main/architecture/supported-providers/_index.en.md
  content/kubermatic/main/architecture/supported-providers/baremetal/_index.en.md
  content/kubermatic/main/architecture/supported-providers/baremetal/baremetal-machine-initial-node.png.png
  content/kubermatic/v2.26/architecture/supported-providers/_index.en.md
  content/kubermatic/v2.26/architecture/supported-providers/baremetal/_index.en.md
  content/kubermatic/v2.26/architecture/supported-providers/baremetal/baremetal-machine-initial-node.png.png
Labels: lgtm, size/L, approved, dco-signoff: yes

#1787 fix yet another typo in Velero upgrade notes
  content/kubermatic/v2.26/installation/upgrading/upgrade-from-2.25-to-2.26/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1786 Adjust docs after the apiserver allowlist revert
  content/kubermatic/main/tutorials-howtos/networking/apiserver-policies/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/networking/apiserver-policies/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1788 KubeLB: Documentation enhancements
  content/kubelb/main/architecture/application-load-balancing/_index.en.md
  content/kubelb/main/installation/tenant-cluster/_index.en.md
  content/kubelb/main/tutorials/ingress/_index.en.md
  content/kubelb/main/tutorials/loadbalancer/_index.en.md
  content/kubelb/v1.1/architecture/application-load-balancing/_index.en.md
  content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/tutorials/ingress/_index.en.md
  content/kubelb/v1.1/tutorials/loadbalancer/_index.en.md
  content/kubermatic/main/tutorials-howtos/kubelb/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/kubelb/_index.en.md
  static/img/kubelb/common/architecture.png
  static/img/kubelb/v1.1/architecture.png
  static/img/kubelb/v1.1/kubelb-high-level-architecture.png
  static/img/kubelb/v1.1/layer7-architecture.png
Labels: lgtm, size/L, approved, dco-signoff: yes
