Repository kubermatic/docs, pull requests merged in 2024-09, with the labels that each got.

#1741 Docs for KubeLB v1.1.1
  content/kubelb/main/compatibility-matrix/_index.en.md
  content/kubelb/main/installation/management-cluster/_index.en.md
  content/kubelb/main/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/compatibility-matrix/_index.en.md
  content/kubelb/v1.1/installation/management-cluster/_index.en.md
  content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1742 Fix cluster autoscaler docs
  content/kubeone/main/guides/autoscaler-addon/_index.en.md
  content/kubeone/v1.8/guides/autoscaler-addon/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1743 Update KubeLB tutorial in KKP
  content/kubermatic/main/tutorials-howtos/kubelb/_index.en.md
  content/kubermatic/main/tutorials-howtos/kubelb/kubelb-dashboard.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1744 KKP: options for web terminal
  content/kubermatic/main/tutorials-howtos/project-and-cluster-management/web-terminal/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1745 KKP: Support for configuring API server service type for the user clusters
  content/kubermatic/main/tutorials-howtos/networking/apiserver-policies/_index.en.md
  content/kubermatic/main/tutorials-howtos/networking/expose-strategies/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1746 KKP: annotation settings for dashboard
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/cluster-settings/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/cluster-settings/images/annotation-settings.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1747 OSM: Update supported k8s versions
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1740 AWS permission fix for kubeone, based on #1555
  content/kubeone/main/architecture/requirements/machine-controller/aws/_index.en.md
  content/kubeone/v1.7/architecture/requirements/machine-controller/aws/aws.en.md
  content/kubeone/v1.8/architecture/requirements/machine-controller/aws/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1748 KubeLB: add note regarding compatibility
  content/kubelb/v1.1/tutorials/kkp/_index.en.md
  content/kubermatic/v2.24/tutorials-howtos/kubelb/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/kubelb/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1749 Default and enforced applications
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/applications/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/applications/images/applications.png
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/custom-links/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/default-enforced-applications/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1751 Remove changelog related docs
  content/kubermatic/main/architecture/concept/kkp-concepts/user-interface/_index.en.md
  content/kubermatic/main/cheat-sheets/changelog/_index.en.md
  content/kubermatic/main/cheat-sheets/changelog/changelog.png
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/custom-links/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1752 Add note for KubeLB version in KKP docs
  content/kubermatic/main/tutorials-howtos/kubelb/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1753 KKP UI: Limit operating systems
  content/kubermatic/main/tutorials-howtos/administration/limit-allowed-operating-systems/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/limit-allowed-operating-systems/images/admin-panel.png
  content/kubermatic/main/tutorials-howtos/administration/limit-allowed-operating-systems/images/create-cluster-wizard.png
  content/kubermatic/main/tutorials-howtos/administration/limit-allowed-operating-systems/images/project-settings.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1754 KKP UI: Admin settings to enable/disable cluster backup
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/interface/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/interface/images/enable-cluster-backup.png
Labels: lgtm, size/XS, approved, dco-signoff: yes
