Repository kubermatic/docs, pull requests merged in 2024-06, with the labels that each got.

#1661 Migrate KDP documentation
  content/_index.md
  content/developer-platform/_index.en.md
  content/developer-platform/platform-users/_index.en.md
  content/developer-platform/platform-users/consuming-services/_index.en.md
  content/developer-platform/platform-users/rbac/_index.en.md
  content/developer-platform/service-providers/_index.en.md
  content/developer-platform/service-providers/crossplane/_index.en.md
  content/developer-platform/service-providers/publish-resources/_index.en.md
  content/developer-platform/service-providers/servlet/_index.en.md
  content/developer-platform/tutorials/_index.en.md
  content/developer-platform/tutorials/kcp-command-line/_index.en.md
  content/developer-platform/tutorials/your-first-service/_index.en.md
  content/kubermatic/main/_index.en.md
  content/kubermatic/v2.17/_index.en.md
  content/kubermatic/v2.18/_index.en.md
  content/kubermatic/v2.18/startio/_index.en.md
  content/kubermatic/v2.19/_index.en.md
  content/kubermatic/v2.19/installation/start_kkp/_index.en.md
  content/kubermatic/v2.20/_index.en.md
  content/kubermatic/v2.20/installation/start_kkp/_index.en.md
  content/kubermatic/v2.21/_index.en.md
  content/kubermatic/v2.21/installation/start-kkp/_index.en.md
  content/kubermatic/v2.22/_index.en.md
  content/kubermatic/v2.23/_index.en.md
  content/kubermatic/v2.24/_index.en.md
  content/kubermatic/v2.25/_index.en.md
  data/products.yaml
  static/img/Docs-KKP-share.jpg
  static/img/Docs-KubeCarrier-share.jpg
  static/img/Docs-KubeLB-share.jpg
  static/img/Docs-KubeOne-share.jpg
  static/img/Docs-OSM-share.jpg
  static/img/KubeCarrier-logo.svg
  static/img/kkp-platform.png
  static/img/logo-kubeone.svg
  static/img/logo-kubermatic.jpg
  static/img/logo-kubermatic.svg
  static/img/operating-system-manager-logo.svg
  static/img/share-developer-platform.png
  static/img/share-kubecarrier.png
  static/img/share-kubelb.png
  static/img/share-kubeone.png
  static/img/share-kubermatic.png
  static/img/share-operatingsystemmanager.png
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1699 KKP: Remove references for CoreOS
  content/kubermatic/main/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/dynamic-data-centers/_index.en.md
  content/kubermatic/v2.17/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/v2.17/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
  content/kubermatic/v2.18/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/v2.18/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
  content/kubermatic/v2.19/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
  content/kubermatic/v2.20/architecture/requirements/cluster_requirements/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/administration/dynamic_data_centers/_index.en.md
  content/kubermatic/v2.21/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/administration/dynamic-data-centers/_index.en.md
  content/kubermatic/v2.22/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/administration/dynamic-data-centers/_index.en.md
  content/kubermatic/v2.23/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/administration/dynamic-data-centers/_index.en.md
  content/kubermatic/v2.24/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/v2.24/tutorials-howtos/administration/dynamic-data-centers/_index.en.md
  content/kubermatic/v2.25/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/administration/dynamic-data-centers/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1700 Minor fix to custom resources state metrics
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/customization/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/monitoring-logging-alerting/master-seed/customization/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1704 Update Helm Integration Documentation Page
  content/kubeone/main/guides/helm-integration/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1703 Extend KDP docs with more information on creating a new service
  content/developer-platform/tutorials/your-first-service/_index.en.md
  content/developer-platform/tutorials/your-first-service/kubeconfig-view.png
  content/developer-platform/tutorials/your-first-service/service-context-menu.png
  content/developer-platform/tutorials/your-first-service/service-creation-wizard.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1705 Sync main menu
  .codespell.exclude
  config.toml
  data/mainMenu.yml
  data/mobileMenu.yml
  themes/kubermatic-docs/assets/scss/_main-header.scss
  themes/kubermatic-docs/layouts/partials/main-header.html
  themes/kubermatic-docs/static/img/icons/list-icon.svg
  themes/kubermatic-docs/static/img/icons/network-icon.svg
  themes/kubermatic-docs/static/img/icons/star-icon.svg
  themes/kubermatic-docs/static/img/menu/kkp-features.svg
  themes/kubermatic-docs/static/img/menu/kubelb.jpg
  themes/kubermatic-docs/static/img/menu/kubermatic-kubernetes-platform.jpg
  themes/kubermatic-docs/static/img/menu/managed-custom-kubernetes.jpeg
  themes/kubermatic-docs/static/img/menu/managed-kubermatic-kubeone.jpeg
  themes/kubermatic-docs/static/img/menu/mobile-menu-arrow.svg
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1706 KDP: Update documentation for consuming services
  content/developer-platform/platform-users/consuming-services/_index.en.md
  content/developer-platform/platform-users/consuming-services/add-service-wizard.png
  content/developer-platform/platform-users/consuming-services/service-catalog.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1697 update compatibility matrix for kubeone with kubernetes 1.30
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/v1.8/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes
