Repository kubermatic/docs, pull requests merged in 2024-11, with the labels that each got.

#1789 fix(typo): fix typo for kkp local installation
  content/kubermatic/v2.23/installation/local-kkp-installation/_index.en.md
  content/kubermatic/v2.24/installation/local-kkp-installation/_index.en.md
  content/kubermatic/v2.25/installation/local-installation/_index.en.md
  content/kubermatic/v2.26/installation/local-installation/_index.en.md
Labels: lgtm, ok-to-test, size/XS, approved, dco-signoff: yes

#1792 KubeLB: Update architecture diagram
  static/img/kubelb/v1.1/kubelb-high-level-architecture.png
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1768 Create Feature Stages page in Main, 2.25 and 2.26
  content/kubermatic/main/architecture/feature-stages/_index.en.md
  content/kubermatic/v2.25/architecture/feature-stages/_index.en.md
  content/kubermatic/v2.26/architecture/feature-stages/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1797 Add guide to use servlet without KDP and update servlet docs
  content/developer-platform/service-providers/publish-resources/_index.en.md
  content/developer-platform/service-providers/servlet/_index.en.md
  content/developer-platform/tutorials/servlet-without-kdp/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1799 Finalize the KubeOne 1.9 documentation
  content/kubeone/main/architecture/compatibility/os-support-matrix/_index.en.md
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/main/guides/addons/_index.en.md
  content/kubeone/main/guides/ccm-csi-migration/_index.en.md
  content/kubeone/main/guides/ccm-csi-migration/troubleshooting/_index.en.md
  content/kubeone/main/guides/using-terraform-configs/_index.en.md
  content/kubeone/main/known-issues/_index.en.md
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
  content/kubeone/main/tutorials/upgrading-clusters/_index.en.md
  content/kubeone/main/tutorials/upgrading/upgrading-from-1.5-to-1.6/_index.en.md
  content/kubeone/main/tutorials/upgrading/upgrading-from-1.7-to-1.8/_index.en.md
  content/kubeone/main/tutorials/upgrading/upgrading-from-1.8-to-1.9/_index.en.md
  content/kubeone/v1.9/architecture/compatibility/os-support-matrix/_index.en.md
  content/kubeone/v1.9/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/v1.9/guides/addons/_index.en.md
  content/kubeone/v1.9/guides/ccm-csi-migration/_index.en.md
  content/kubeone/v1.9/guides/ccm-csi-migration/troubleshooting/_index.en.md
  content/kubeone/v1.9/guides/using-terraform-configs/_index.en.md
  content/kubeone/v1.9/known-issues/_index.en.md
  content/kubeone/v1.9/tutorials/creating-clusters/_index.en.md
  content/kubeone/v1.9/tutorials/upgrading-clusters/_index.en.md
  content/kubeone/v1.9/tutorials/upgrading/upgrading-from-1.5-to-1.6/_index.en.md
  content/kubeone/v1.9/tutorials/upgrading/upgrading-from-1.7-to-1.8/_index.en.md
  content/kubeone/v1.9/tutorials/upgrading/upgrading-from-1.8-to-1.9/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1800 Add KubeOne v1.9 to products.yaml
  content/kubeone/main/known-issues/_index.en.md
  content/kubeone/v1.9/known-issues/_index.en.md
  data/products.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1790 Update Kubevirt Provider
  content/kubermatic/main/architecture/supported-providers/kubevirt/_index.en.md
  content/kubermatic/v2.26/architecture/supported-providers/kubevirt/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1795 Add Tinkerbell to Editions in 2.26
  content/kubermatic/v2.26/architecture/editions/_index.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1796 Add Tinkerbell to Editions in main
  content/kubermatic/main/architecture/editions/_index.md
Labels: lgtm, size/XS, approved, dco-signoff: yes
