Repository kubermatic/docs, pull requests merged in 2024-02, with the labels that each got.

#1611 Adding EE label to meta
  content/kubermatic/main/tutorials-howtos/kubelb/_index.en.md
  content/kubermatic/v2.24/tutorials-howtos/kubelb/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1600 Update cilium network policy issue docs
  content/kubermatic/main/architecture/known-issues/_index.en.md
  content/kubermatic/main/installation/upgrading/upgrade-from-2.23-to-2.24/_index.en.md
  content/kubermatic/v2.24/architecture/known-issues/_index.en.md
  content/kubermatic/v2.24/installation/upgrading/upgrade-from-2.23-to-2.24/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1613 Update kubelb version
  content/kubelb/installation/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1612 Update support matrix for KKP 2.25 and Kubernetes 1.29
  content/kubermatic/main/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1610 Added documentation for Default Application Catalog
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/argocd/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/cert-manager/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/falco/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/flux2/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/k8sgpt/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/kube-vip/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/kubevirt/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/metallb/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/nginx/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/trivy-operator/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/trivy/_index.en.md
  content/kubermatic/main/installation/install-kkp-ee/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/argocd/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/cert-manager/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/falco/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/flux2/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/k8sgpt/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/kube-vip/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/kubevirt/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/metallb/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/nginx/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/trivy-operator/_index.en.md
  content/kubermatic/v2.24/architecture/concept/kkp-concepts/applications/default-applications-catalog/trivy/_index.en.md
  content/kubermatic/v2.24/installation/install-kkp-EE/_index.en.md
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-argocd-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-cert-manager-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-falco-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-flux2-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-k8sgpt-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-kube-vip-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-metallb-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-nginx-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-trivy-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/01-select-application-trivy-operator-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/02-seetings-metallb-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/02-settings-argocd-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/02-settings-cert-manager-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/02-settings-falco-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/02-settings-k8sgpt-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/02-settings-kube-vip-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/02-settings-nginx-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/02-settings-trivy-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/02-settings-trivy-operator-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/03-applicationvalues-argocd-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/03-applicationvalues-cert-manager-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/03-applicationvalues-k8sgpt-app.png
  static/img/kubermatic/common/applications/default-apps-catalog/03-applicationvalues-trivy-operator-app.png
Labels: size/XL, lgtm, approved, dco-signoff: yes

#1609 document certificate renewal within kubeone
  content/kubeone/main/guides/certificate-management/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1617 KubeLB: propgate annotaitons from services to load balancers
  content/kubelb/usage/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1618 Updated release notes to include Feb 2024 changelogs
  content/kubermatic/v2.22/release-notes/_index.en.md
  content/kubermatic/v2.23/release-notes/_index.en.md
  content/kubermatic/v2.24/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1620 Document custom state metrics option for seed/master
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/customization/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1619 Update AppDoc to 2.25
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-definition/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-installation/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/add-applications-to-cluster/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/add-remove-application-version/_index.en.md
  content/kubermatic/main/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  static/img/kubermatic/common/applications/appdef-customizations.png
  static/img/kubermatic/common/applications/default-application-catalogue.png
Labels: lgtm, approved, size/M, dco-signoff: yes
