Repository kubermatic/docs, pull requests merged in 2024-05, with the labels that each got.

#1676 update Master/Seed MLA installation documentation - kubermatic-installer
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/master-seed/installation/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1675 add changelog for 2.23.15, 2.24.8, 2.25.3
  content/kubermatic/v2.23/release-notes/_index.en.md
  content/kubermatic/v2.24/release-notes/_index.en.md
  content/kubermatic/v2.25/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1672 [KKP] add notes about usercluster MLA cortex being slow
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1677 KubeOne: remove duplicate word 'applied'
  content/kubeone/main/architecture/_index.en.md
  content/kubeone/v1.3/architecture/_index.en.md
  content/kubeone/v1.4/architecture/_index.en.md
  content/kubeone/v1.5/architecture/_index.en.md
  content/kubeone/v1.6/architecture/_index.en.md
  content/kubeone/v1.7/architecture/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1678 Add known issue regarding Azure and Ubuntu for KKP
  content/kubermatic/v2.23/architecture/known-issues/_index.en.md
  content/kubermatic/v2.24/architecture/known-issues/_index.en.md
  content/kubermatic/v2.25/architecture/known-issues/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1683 Minor fix to cluster autoscaler docs
  content/kubermatic/main/tutorials-howtos/kkp-autoscaler/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/KKP-autoscaler/_index.en.md
  content/kubermatic/v2.24/tutorials-howtos/KKP-autoscaler/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/kkp-autoscaler/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1685 Refresh KubeOne docs ahead of 1.8.0
  content/kubeone/main/architecture/compatibility/os-support-matrix/_index.en.md
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubeone/main/architecture/operating-system-manager/usage/_index.en.md
  content/kubeone/main/architecture/requirements/machine-controller/vsphere/_index.en.md
  content/kubeone/main/architecture/support-policy/_index.en.md
  content/kubeone/main/cheat-sheets/production-recommendations/_index.en.md
  content/kubeone/main/examples/addons-calico-vxlan/_index.en.md
  content/kubeone/main/getting-kubeone/_index.en.md
  content/kubeone/main/guides/addons/_index.en.md
  content/kubeone/main/guides/autoscaler-addon/_index.en.md
  content/kubeone/main/guides/ccm-csi-migration/_index.en.md
  content/kubeone/main/guides/containerd-migration/_index.en.md
  content/kubeone/main/guides/credentials/_index.md
  content/kubeone/main/guides/encryption-providers/_index.en.md
  content/kubeone/main/guides/mirror-registries/_index.en.md
  content/kubeone/main/guides/registry-configuration/_index.en.md
  content/kubeone/main/tutorials/creating-clusters-baremetal/_index.en.md
  content/kubeone/main/tutorials/creating-clusters-oidc/_index.en.md
  content/kubeone/main/tutorials/creating-clusters/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1686 Update the known issues document for KubeOne 1.8
  content/kubeone/main/known-issues/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1684 Render release notes via remote URLs
  content/kubermatic/v2.20/release-notes/_index.en.md
  content/kubermatic/v2.21/release-notes/_index.en.md
  content/kubermatic/v2.22/release-notes/_index.en.md
  content/kubermatic/v2.23/release-notes/_index.en.md
  content/kubermatic/v2.24/release-notes/_index.en.md
  content/kubermatic/v2.25/release-notes/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1687 Add upgrade guide from KubeOne 1.7 to 1.8
  content/kubeone/main/tutorials/upgrading/upgrading-from-1.7-to-1.8/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1690 Update commands for KubeLB
  content/kubelb/ce/installation/_index.en.md
  content/kubelb/ee/installation/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1691 Fixed edit the page branch link and KKP version
  config.toml
  content/kubermatic/v2.25/architecture/known-issues/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1681 Changing the architecture images
  content/kubermatic/main/architecture/combined-master-seed.png
  content/kubermatic/main/architecture/dedicated-seeds.png
  static/img/kubermatic/v2.25/architecture/combined-master-seed.png
  static/img/kubermatic/v2.25/architecture/dedicated-seeds.png
Labels: kind/cleanup, lgtm, size/XS, kind/documentation, approved, dco-signoff: yes

#1692 Fix typo in _index.en.md
  content/kubeone/v1.8/examples/addons-backup/_index.en.md
Labels: lgtm, size/XS, approved, needs-ok-to-test, dco-signoff: yes

#1693 Drop connection keep-alived header from external markdown shortcode
  layouts/shortcodes/render_external_markdown.html
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1694 Update link to oauth2-proxy providers doc
  content/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/v2.18/guides/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/v2.19/tutorials_howtos/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/v2.20/tutorials_howtos/monitoring_logging_alerting/user_cluster/admin_guide/_index.en.md
  content/kubermatic/v2.21/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/v2.24/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes
