Repository kubermatic/docs, pull requests merged in 2025-06, with the labels that each got.

#1882 add a notice info for mirror-binaries
  content/kubermatic/main/installation/offline-mode/_index.en.md
  content/kubermatic/v2.27/installation/offline-mode/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1883 Update documentation for Dex
  content/kubermatic/main/installation/install-kkp-ce/_index.en.md
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1888 Add docs for uploading backups
  content/kubermatic/main/tutorials-howtos/cluster-backup/_index.en.md
  content/kubermatic/main/tutorials-howtos/cluster-backup/images/upload-backups-button.png
  content/kubermatic/main/tutorials-howtos/cluster-backup/images/upload-backups-dialog.png
Labels: lgtm, approved, size/S, dco-signoff: yes

#1891 Update the Seed MLA Alertmanager upgrade docs
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1895 Fix typos in the KubeLB documentation
  content/kubelb/main/architecture/_index.en.md
  content/kubelb/main/architecture/application-load-balancing/_index.en.md
  content/kubelb/main/architecture/layer-4-load-balancing/_index.en.md
  content/kubelb/main/installation/_index.en.md
  content/kubelb/v1.0/architecture/_index.en.md
  content/kubelb/v1.0/installation/_index.en.md
  content/kubelb/v1.1/architecture/_index.en.md
  content/kubelb/v1.1/architecture/application-load-balancing/_index.en.md
  content/kubelb/v1.1/architecture/layer-4-load-balancing/_index.en.md
  content/kubelb/v1.1/installation/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1885 update KNP-Agent configuration settings in issues page
  content/kubermatic/main/architecture/known-issues/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1901 Add --limit-apps flag usage to default app catalog section
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/main/installation/install-kkp-ee/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1903 add localai app to default catalog docs
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/local-ai/01-select-local-ai-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/local-ai/02-settings-local-ai-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/local-ai/03-applicationvalues-local-ai-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/local-ai/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1910 Rearrange the Dex migration section in Upgrading to KKP 2.28 docs
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
  content/kubermatic/v2.28/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes
