Repository kubermatic/docs, pull requests merged in 2025-01, with the labels that each got.

#1806 Update supported CNI versions doc
  content/kubermatic/main/tutorials-howtos/networking/cni-cluster-network/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/networking/cni-cluster-network/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/networking/cni-cluster-network/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1723 Added kkp-management via argocd tutorial
  content/kubermatic/main/images/tutorials/gitops-argocd/kkp-gitops-argocd.png
  content/kubermatic/main/tutorials-howtos/gitops-argocd/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1807 feat: add flag to skip TLS verification
  content/kubeone/v1.9/examples/addons-backup/_index.en.md
Labels: lgtm, size/XS, approved, needs-ok-to-test, dco-signoff: yes

#1808 add explanation for oidc refresh token issue
  content/kubermatic/main/architecture/known-issues/_index.en.md
  content/kubermatic/v2.24/architecture/known-issues/_index.en.md
  content/kubermatic/v2.25/architecture/known-issues/_index.en.md
  content/kubermatic/v2.26/architecture/known-issues/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1810 Document Kubevirt Namespaced Mode
  content/kubermatic/main/architecture/supported-providers/kubevirt/_index.en.md
  content/kubermatic/v2.26/architecture/supported-providers/kubevirt/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1811 Os compatibility update
  content/kubermatic/main/architecture/compatibility/os-support-matrix/_index.en.md
  content/kubermatic/v2.26/architecture/compatibility/os-support-matrix/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes
