Repository kubermatic/docs, pull requests merged in 2025-07, with the labels that each got.

#1915 add docs for kubevirt ee netpol mode
  content/kubermatic/main/architecture/supported-providers/kubevirt/_index.en.md
  content/kubermatic/v2.28/architecture/supported-providers/kubevirt/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1917 Klll unsupported kubeone API references
  content/kubeone/main/references/kubeone-cluster-v1beta1/_index.en.md
  content/kubeone/v1.10/references/kubeone-cluster-v1beta1/_index.en.md
  content/kubeone/v1.11/references/kubeone-cluster-v1beta1/_index.en.md
Labels: lgtm, size/XXL, approved, dco-signoff: yes

#1918 Update 'Add or Remove an Application Version' page
  content/kubermatic/main/tutorials-howtos/applications/add-remove-application-version/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1924 Update release process
  content/kubermatic/main/release/_index.en.md
  content/kubermatic/v2.28/release/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1928 chore: Update structure for Cluster settings docs
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/cluster-settings/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/cluster-settings/images/defaults-cluster-settings.png
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/cluster-settings/images/static-labels.png
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/cluster-settings/images/user-projects-limit.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1937 add ref for creating a kubernetes cluster with kubeone in docs
  content/kubeone/main/architecture/_index.en.md
  content/kubeone/main/cheat-sheets/_index.en.md
  content/kubeone/main/creating-clusters/_index.en.md
  content/kubeone/main/examples/_index.en.md
  content/kubeone/main/guides/_index.en.md
  content/kubeone/main/references/_index.en.md
  content/kubeone/main/tutorials/_index.en.md
  content/kubeone/v1.11/architecture/_index.en.md
  content/kubeone/v1.11/cheat-sheets/_index.en.md
  content/kubeone/v1.11/creating-clusters/_index.en.md
  content/kubeone/v1.11/examples/_index.en.md
  content/kubeone/v1.11/guides/_index.en.md
  content/kubeone/v1.11/references/_index.en.md
  content/kubeone/v1.11/tutorials/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1938 KKP UI: Add Docs for Delete / View Preset Linkages
  content/kubermatic/main/tutorials-howtos/administration/presets/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/presets/images/delete-preset-action-item.png
  content/kubermatic/main/tutorials-howtos/administration/presets/images/delete-preset-warning.png
  content/kubermatic/main/tutorials-howtos/administration/presets/images/delete-preset-with-no-associations.png
  content/kubermatic/main/tutorials-howtos/administration/presets/images/view-preset-linkages.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1939 Setup documentation for the KDP spec generator
  content/developer-platform/setup/ai-agent/_index.en.md
  content/developer-platform/setup/ai-agent/ai-agent-button.png
  content/developer-platform/setup/ai-agent/ai-agent-example-response.png
  content/developer-platform/setup/ai-agent/ai-agent-prompt-example.png
Labels: lgtm, size/L, approved, dco-signoff: yes
