Repository kubermatic/docs, pull requests merged in 2025-09, with the labels that each got.

#1976 Update spec generator ingress config instructions for KDP
  content/developer-platform/setup/ai-agent/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1975 Update supported k8s version matrix for operating-system-manager
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/operatingsystemmanager/compatibility/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1969 Update kkp 2.28 upgrade doc to include workaround for kvirt csi driver breaking change.
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
  content/kubermatic/v2.28/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1985 Use trivy instead of kube-bench for CIS benchmarks
  content/kubeone/main/security/cis-benchmarking/_index.en.md
  content/kubeone/main/security/cis-benchmarking/kubeone1.11-k8s1.33/_index.en.md
  content/kubeone/v1.11/guides/cis-benchmarking/cis1.23-kubeone1.11-k8s1.33/_index.en.md
  hack/cis-benchmark/README.md
  hack/cis-benchmark/generate_markdown.sh
  hack/cis-benchmark/output.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1986 Fix post-kubermatic-update-docs job for KKP release 2.27 and 2.26
  hack/render-crds.sh
Labels: lgtm, approved, size/S, dco-signoff: yes

#1989 Fixed typo in comment of custom OSP snippet
  content/operatingsystemmanager/data/osp-ubuntu-swap-enabled.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1981 Update k8s compatibility matrix in KubeOne
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1982 Bump hugo image version to 0.150.0-0
  .prow.yaml
  Makefile
  netlify.toml
Labels: lgtm, size/XS, approved, dco-signoff: yes
