Repository kubermatic/docs, pull requests merged in 2025-03, with the labels that each got.

#1831 add page for app templating in ee edition
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-templating/_index.en.md
  content/kubermatic/v2.27/architecture/concept/kkp-concepts/applications/application-templating/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1833 Update KubeLB Gateway Class docs
  content/kubelb/main/tutorials/config/_index.en.md
  content/kubelb/main/tutorials/gatewayapi/_index.en.md
  content/kubelb/main/tutorials/tenants/_index.en.md
  content/kubelb/v1.1/tutorials/config/_index.en.md
  content/kubelb/v1.1/tutorials/gatewayapi/_index.en.md
  content/kubelb/v1.1/tutorials/tenants/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1836 use main branch in prometheus AppDef examples
  content/kubermatic/main/tutorials-howtos/applications/create-application-catalog/_index.en.md
  content/kubermatic/v2.21/data/applicationDefinition.yaml
  content/kubermatic/v2.21/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/v2.22/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/v2.23/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/v2.24/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/v2.25/tutorials-howtos/applications/create-application-catalogue/_index.en.md
  content/kubermatic/v2.26/tutorials-howtos/applications/create-application-catalog/_index.en.md
  content/kubermatic/v2.27/tutorials-howtos/applications/create-application-catalog/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1834 Add kubeone example how to use mirror.gcr.io
  content/kubeone/main/guides/mirror-registries/_index.en.md
  content/kubeone/v1.9/guides/mirror-registries/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-configuration/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-configuration/registry-mirrors/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-configuration/seed/_index.en.md
  content/kubermatic/v2.27/tutorials-howtos/kkp-configuration/_index.en.md
  content/kubermatic/v2.27/tutorials-howtos/kkp-configuration/registry-mirrors/_index.en.md
  content/kubermatic/v2.27/tutorials-howtos/kkp-configuration/seed/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1837 Remove excessive back-ticks
  content/kubermatic/main/tutorials-howtos/kkp-configuration/registry-mirrors/_index.en.md
  content/kubermatic/v2.27/tutorials-howtos/kkp-configuration/registry-mirrors/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1840 Small typo fix
  content/kubermatic/main/tutorials-howtos/kkp-configuration/registry-mirrors/_index.en.md
  content/kubermatic/v2.27/tutorials-howtos/kkp-configuration/registry-mirrors/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1835 KKP: Add a draft/template for KKP upgrade docs
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.xx/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1841 Fixed typo
  content/kubermatic/main/tutorials-howtos/gitops-argocd/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1844 KubeLB v1.1.3
  content/kubelb/main/installation/management-cluster/_index.en.md
  content/kubelb/main/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/installation/management-cluster/_index.en.md
  content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/release-notes/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1839 (kkp): Update known issues page, regarding Konnectivity
  content/kubermatic/main/architecture/known-issues/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1846 rephrase KDP docs, s/Servlet/api-syncagent/g
  content/developer-platform/_index.en.md
  content/developer-platform/platform-users/consuming-services/_index.en.md
  content/developer-platform/service-providers/api-syncagent/_index.en.md
  content/developer-platform/service-providers/crossplane/_index.en.md
  content/developer-platform/service-providers/publish-resources/_index.en.md
  content/developer-platform/tutorials/agent-without-kdp/_index.en.md
  content/developer-platform/tutorials/servlet-without-kdp/_index.en.md
  content/developer-platform/tutorials/your-first-service/_index.en.md
Labels: size/XL, lgtm, approved, dco-signoff: yes

#1842 Migration document for Node Exporter Helm Chart
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.xx/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1850 fix sync for KKP
  hack/convert-runbook.sh
  hack/render-crds.sh
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1851 Improve KKP runbook versioning
  Makefile
  data/kubermatic/v2.26/main/runbook.json
  hack/convert-runbook.sh
  hack/render-crds.sh
Labels: lgtm, approved, size/S, dco-signoff: yes

#1847 improve app documentation
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-templating/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-autoscaler/cluster-autoscaler/_index.en.md
  content/kubermatic/v2.27/architecture/concept/kkp-concepts/applications/application-templating/_index.en.md
  content/kubermatic/v2.27/tutorials-howtos/kkp-autoscaler/cluster-autoscaler/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes
