Repository kubermatic/docs, pull requests merged in 2025-02, with the labels that each got.

#1814 (fix): minor typos and broken links in docs
  content/kubermatic/main/architecture/concept/kkp-concepts/cluster-templates/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/kkp-security/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/kkp-security/securing-system-services/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/resource-quotas/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/service-account/_index.en.md
  content/kubermatic/main/architecture/requirements/cluster-requirements/_index.en.md
  content/kubermatic/v2.26/architecture/concept/kkp-concepts/cluster-templates/_index.en.md
  content/kubermatic/v2.26/architecture/concept/kkp-concepts/kkp-security/_index.en.md
  content/kubermatic/v2.26/architecture/concept/kkp-concepts/kkp-security/securing-system-services/_index.en.md
  content/kubermatic/v2.26/architecture/concept/kkp-concepts/resource-quotas/_index.en.md
  content/kubermatic/v2.26/architecture/concept/kkp-concepts/service-account/_index.en.md
  content/kubermatic/v2.26/architecture/requirements/cluster-requirements/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1815 Document vmEvictionStrategy for KubeVirt
  content/kubermatic/main/architecture/supported-providers/kubevirt/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1816 Document ccmZoneAndRegionEnabled
  content/kubermatic/main/architecture/supported-providers/kubevirt/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1819 deprecate autoscaler addon + add autoscaler default app
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/argocd/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/cluster-autoscaler/01-select-application-cluster-autoscaler-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/cluster-autoscaler/02-settings-cluster-autoscaler-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/cluster-autoscaler/03-applicationvalues-cluster-autoscaler-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/cluster-autoscaler/_index.en.md
  content/kubermatic/main/tutorials-howtos/kkp-autoscaler/cluster-autoscaler/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1818 add aikit app to default app catalogue
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/aikit/01-select-application-aikit-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/aikit/02-settings-aikit-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/aikit/03-applicationvalues-aikit-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/aikit/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1822 Mirroring Images with KubermaticConfiguration
  content/kubermatic/main/installation/offline-mode/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1820 Introduce k8sgpt-operator as an application from the default app catalog
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/_index.en.md
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/k8sgpt-operator/01-select-application-k8sgpt-operator-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/k8sgpt-operator/02-settings-k8sgpt-operator-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/k8sgpt-operator/03-applicationvalues-k8sgpt-operator-app.png
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/default-applications-catalog/k8sgpt-operator/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1823 Add docs for admin announcements feature
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/admin-announcements/_index.en.md
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/admin-announcements/images/announcement-banner.png
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/admin-announcements/images/announcements-dialog.png
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/admin-announcements/images/announcements-list.png
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/admin-announcements/images/announcements-page.png
  content/kubermatic/main/tutorials-howtos/administration/admin-panel/admin-announcements/images/help-panel.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1825 document kubevirt csiDriverOperator
  content/kubermatic/main/architecture/supported-providers/kubevirt/_index.en.md
  content/kubermatic/v2.27/architecture/supported-providers/kubevirt/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1826 add KKP 2.27 release notes
  content/kubermatic/v2.27/release-notes/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1828 Add docs for importing external backups
  content/kubermatic/main/tutorials-howtos/cluster-backup/_index.en.md
  content/kubermatic/main/tutorials-howtos/cluster-backup/images/enable-backup-edit-cluster.png
  content/kubermatic/main/tutorials-howtos/cluster-backup/images/enable-backup-kkp.png
  content/kubermatic/main/tutorials-howtos/cluster-backup/images/enable-backup-new-cluster.png
  content/kubermatic/main/tutorials-howtos/cluster-backup/images/import-external-backups-button.png
  content/kubermatic/main/tutorials-howtos/cluster-backup/images/import-external-backups-dialog.png
  content/kubermatic/v2.27/tutorials-howtos/cluster-backup/_index.en.md
  content/kubermatic/v2.27/tutorials-howtos/cluster-backup/images/enable-backup-edit-cluster.png
  content/kubermatic/v2.27/tutorials-howtos/cluster-backup/images/enable-backup-kkp.png
  content/kubermatic/v2.27/tutorials-howtos/cluster-backup/images/enable-backup-new-cluster.png
  content/kubermatic/v2.27/tutorials-howtos/cluster-backup/images/import-external-backups-button.png
  content/kubermatic/v2.27/tutorials-howtos/cluster-backup/images/import-external-backups-dialog.png
Labels: lgtm, approved, size/M, dco-signoff: yes

#1827 docs(upgrade): add upgrade doc for v2.26 to v2.27
  content/kubermatic/main/installation/upgrading/upgrade-from-2.26-to-2.27/_index.en.md
  content/kubermatic/v2.27/installation/upgrading/upgrade-from-2.26-to-2.27/_index.en.md
Labels: size/XL, lgtm, approved, dco-signoff: yes
