Repository kubermatic/docs, pull requests merged in 2025-05, with the labels that each got.

#1862 Update Audit Logging page
  content/kubermatic/main/tutorials-howtos/audit-logging/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1852 Update _index.en.md fix loki-ingester storage customization part
  content/kubermatic/v2.25/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/_index.en.md
Labels: lgtm, approved, needs-ok-to-test, size/S, dco-signoff: yes

#1857 added alertmanager upgrade documentation
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
  content/kubermatic/v2.27/installation/upgrading/upgrade-from-2.26-to-2.27/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1864 Update Audit Logging page with the new environment variable support
  content/kubermatic/main/tutorials-howtos/audit-logging/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1867 Add Seed Level Audit Logging doc
  content/kubermatic/main/tutorials-howtos/audit-logging/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1868 Add upgrade guide for blackbox-exporter in 2.28
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1869 Updated k8s compatability matrix
  content/kubermatic/main/architecture/compatibility/supported-versions/_index.en.md
  content/kubermatic/v2.27/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1871 Minor enhancements to KubeLB docs
  content/kubelb/main/installation/management-cluster/_index.en.md
  content/kubelb/main/installation/tenant-cluster/_index.en.md
  content/kubelb/v1.1/installation/management-cluster/_index.en.md
  content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1872 vsphere permissions doc update
  content/kubermatic/main/architecture/supported-providers/vsphere/_index.en.md
  content/kubermatic/v2.26/architecture/supported-providers/vsphere/_index.en.md
  content/kubermatic/v2.27/architecture/supported-providers/vsphere/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1873 Documenting DisableDefaultOperatingSystemProfiles Feature
  content/kubermatic/main/references/crds/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1876 (kkp-upgrade-guideline-v2.28) document incoming Azure Basic LB SKU deprecation
  content/kubermatic/main/installation/upgrading/upgrade-from-2.27-to-2.28/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1875 kubelb: enable for all datacenters
  content/kubermatic/main/tutorials-howtos/kubelb/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1878 update k1 compability matrix
  content/kubeone/main/architecture/compatibility/supported-versions/_index.en.md
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1863 Update the installation guide to use New Dex Chart
  content/kubermatic/main/architecture/concept/kkp-concepts/kkp-security/securing-system-services/_index.en.md
  content/kubermatic/main/installation/install-kkp-ce/_index.en.md
  content/kubermatic/main/tutorials-howtos/oidc-provider-configuration/share-clusters-via-delegated-oidc-authentication/_index.en.md
  content/kubermatic/v2.27/installation/install-kkp-ce/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes
