Repository kubermatic/docs, pull requests merged in 2025-08, with the labels that each got.

#1941 Remove duplicate "Publishing Resources" content from Crossplane KDP docs
  content/developer-platform/service-providers/crossplane/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1920 Improved the language for ApplicationInstallation page
  content/kubermatic/main/architecture/concept/kkp-concepts/applications/application-installation/_index.en.md
Labels: lgtm, approved, size/M, dco-signoff: yes

#1898 Add note in docs about splitting large ID tokens into multiple cookies
  content/kubermatic/main/tutorials-howtos/oidc-provider-configuration/_index.en.md
  content/kubermatic/v2.28/tutorials-howtos/oidc-provider-configuration/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1945 KubeV docs
  content/kubermatic-virtualization/_index.md
  content/kubermatic-virtualization/main/_index.en.md
  content/kubermatic-virtualization/main/architecture/_index.en.md
  content/kubermatic-virtualization/main/architecture/compatibility/_index.en.md
  content/kubermatic-virtualization/main/architecture/compatibility/kubev-components-versioning/_index.en.md
  content/kubermatic-virtualization/main/architecture/compatibility/operating-system/_index.en.md
  content/kubermatic-virtualization/main/architecture/concepts/_index.en.md
  content/kubermatic-virtualization/main/architecture/concepts/compute/_index.en.md
  content/kubermatic-virtualization/main/architecture/concepts/compute/virtual-machines/_index.en.md
  content/kubermatic-virtualization/main/architecture/concepts/networks/_index.en.md
  content/kubermatic-virtualization/main/architecture/concepts/networks/vms-networks-assignment/_index.en.md
  content/kubermatic-virtualization/main/architecture/concepts/networks/vpc-subnets/_index.en.md
  content/kubermatic-virtualization/main/architecture/concepts/storage/_index.en.md
  content/kubermatic-virtualization/main/architecture/kube-v-architecture.png
  content/kubermatic-virtualization/main/architecture/requirements/_index.en.md
  content/kubermatic-virtualization/main/architecture/requirements/high-availability-deployment/_index.en.md
  content/kubermatic-virtualization/main/architecture/requirements/single-node-deployment/_index.en.md
  content/kubermatic-virtualization/main/installation/_index.en.md
  data/products.yaml
Labels: size/XL, dco-signoff: yes

#1947 Add KDP to products.yaml (make it visible on landing page)
  data/products.yaml
  static/img/developer-platform/common/logo.svg
Labels: lgtm, approved, size/S, dco-signoff: yes

#1953 Fix indentation of ClusterIssuer
  content/developer-platform/setup/quickstart/data/letsencrypt.cluster-issuer.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1958 Update OSM compatibility matrix in KKP docs
  content/kubermatic/main/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
  content/kubermatic/v2.28/tutorials-howtos/operating-system-manager/compatibility/_index.en.md
Labels: lgtm, approved, size/S, dco-signoff: yes

#1960 Increase memory limits for markdown-lint job
  .prow.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1963 Set AI agent feature to false in the quickstart
  content/developer-platform/setup/quickstart/data/kdp-dashboard.values.yaml
Labels: lgtm, size/XS, approved, dco-signoff: yes

#1961 add kubev installer doc
  .prow.yaml
  content/kubermatic-virtualization/main/installation/_index.en.md
  content/kubermatic-virtualization/main/installation/assets/0-welcome-page.png
  content/kubermatic-virtualization/main/installation/assets/1-network-page.png
  content/kubermatic-virtualization/main/installation/assets/2-lb-page.png
  content/kubermatic-virtualization/main/installation/assets/3-node-count.png
  content/kubermatic-virtualization/main/installation/assets/4-node-config-page.png
  content/kubermatic-virtualization/main/installation/assets/5-csi-page.png
  content/kubermatic-virtualization/main/installation/assets/6-review-page.png
Labels: size/L, dco-signoff: yes

#1967 Add ubuntu os kkp requirements
  content/kubermatic/main/architecture/compatibility/os-support-matrix/ubuntu-requirements/_index.en.md
  content/kubermatic/v2.28/architecture/compatibility/os-support-matrix/ubuntu-requirements/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#1853 Fix configuration snippet for refresh token issue workaround
  content/kubermatic/main/architecture/known-issues/_index.en.md
  content/kubermatic/v2.24/architecture/known-issues/_index.en.md
  content/kubermatic/v2.25/architecture/known-issues/_index.en.md
  content/kubermatic/v2.26/architecture/known-issues/_index.en.md
  content/kubermatic/v2.27/architecture/known-issues/_index.en.md
  content/kubermatic/v2.28/architecture/known-issues/_index.en.md
Labels: lgtm, size/L, approved, dco-signoff: yes
